### ISSUE TITLE
how can i thoroughly change (key “C-x”) in ivy-minibuffer-map?

### ISSUE THREAD

**Issue by ichirika** [abo-abo/swiper#1282] opened 2017-11-14 03:07 UTC
one thing very interesting, i tried to

`(define-key ivy-minibuffer-map (kbd "C-x") 'ivy-kill-line)
`
..well then i restart my emacs, 
the first time i use the ivy to complete something, 
i type C-x indeed can kill the line,

**but ,the second time i use the ivy, the C-x became a suffix.** 
what the fuxk... then i tried which-key-mode, 
i found these keys on suffix of C-x in ivy-minibuffer

C-x 8(iso-transl-ctl-8-map) -> (many strange chars inside..)
C-x @ -> (S -> event-apply-shift-modifier)(h -> event-apply-hyper-modifier)....etc something like this
C-x r -> (some functions on rectangle..)

but i **never defined them**... what the fuxk...

also tried many other ways, like **minor-mode-overriding-map-alist,**
and the **minor-mode-hack,** but none of them works...
also tried this one 
   ` (defvar ivy-minibuffer-map (let ((map (make-sparse-keymap)))define xxxxx)
`

anyone can help me out.. i just want to **use C-x in ivy-minibuffer-map to kill the line.**
emmm.i think maybe this is caused by some other minor modes. emmmm. confused.

**Comment by abo-abo** [comment] 2017-11-14 18:05
> (define-key ivy-minibuffer-map (kbd "C-x") 'ivy-kill-line)

This works fine for me, the problem is likely in your config. If you can reproduce this with `emacs -Q`, report here.

Also, please use a more civil language when commenting on issues in the future.

**Comment by ichirika** [comment] 2017-11-14 20:30
Thanks for your reply, 
Oh. And I'll be careful ,

**Comment by ichirika** [comment] 2017-11-14 21:57
yeah~i also think the problem is in my config, it seems to be overwritten by other minor-mode-map, 
and i also tried  to bind "C-x" in ido-mode, i cant even use C-x to kill-line the first time.

i tried the method you gave here ,https://github.com/abo-abo/swiper/issues/327,
as you mentioned,
> All minor modes are in a list of priority, you need to raise ivy-mode above rsk-minor-mode.

i think this must be a breakthrough point, 
i tried to raise the ido-mode in ido-setup-hook, then ido-mode can use C-x to kill-line the first time, 
the second time is still like ivy, 

i'm thinking about if there's a way can run this raise-minor-mode every time i use the ivy and ido? 
or ..maybe the way i use raise-minor-mode is run,

i run this
`(raise-minor-mode-map-alist 'ido)` in  `ido-setup-hook`

and 

`(raise-minor-mode-map-alist 'ivy-mode)`
`(raise-minor-mode-map-alist 'ivy-minibuffer)` 
out of any hook,

i also tried to bind C-x in helm-map, then it can works every time,
somehow confused me, lol...

**Comment by abo-abo** [comment] 2017-11-15 18:22
You can try to bisect your config. Comment out half of it, see if the bug is still there. Keep dividing in two until you find it.

**Comment by ichirika** [comment] 2017-11-15 21:43
Thanks for suggestion  , i'll give it a try . :D

**Comment by abo-abo** [comment] 2018-02-19 19:15
Closing the issue, since it's more Emacs-related than Ivy-related.

**Closed by abo-abo** 2018-02-19 19:15 UTC
