### ISSUE TITLE
Error running counsel-describe-function and counsel-describe-variable

### ISSUE THREAD

**Issue by yorodm** [abo-abo/swiper#1651] opened 2018-07-05 17:27 UTC
Emacs version: 26.1
Counsel: 20180703.840
Running `counsel-describe-function` or `counsel-describe-variable` shows an error message.
```
ivy--recompute-index: Wrong type argument: stringp, nil
```

**Comment by manuel-uberti** [comment] 2018-07-05 17:39
[This commit](https://github.com/abo-abo/swiper/commit/e1c9fab9604cbce43678c19773cb2e9fc98cb478) should have fixed this problem. Could you try updating `ivy`?

**Comment by basil-conto** [comment] 2018-07-05 20:01
This sounds like a duplicate of #1647.

**Comment by abo-abo** [comment] 2018-07-05 20:32
Seen the same error message when mering the fix to #1647. Closing as duplicate (and fixed).

**Closed by abo-abo** 2018-07-05 20:32 UTC
