### ISSUE TITLE
lagging with ivy-mode

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/swiper#1571] opened 2018-05-14 06:38 UTC
I am using GNU Emacs 25.3 on terminal of Ubuntu 16.04. After a few days, the emacs is lagging when do some operations with `ivy`, `swiper` or `counsel`. If I restart the Emacs daemon, the issue disappeared and occurs again after a few days. My config is: https://github.com/seagle0128/.emacs.d. 

I did the profiling and attach the screenshot here. It seems `ivy--add-face` caused high CPU.

![emacs_hang](https://user-images.githubusercontent.com/140797/39981618-e37e0fba-5783-11e8-8e84-18229c0c89ca.png)

**Comment by basil-conto** [comment] 2018-05-14 16:04
> After a few days, the emacs is lagging when do some operations with `ivy`, `swiper` or `counsel`.

**Only** these packages?

>If I restart the Emacs daemon, the issue disappeared and occurs again after a few days.

I wonder if it's an issue with increasing non-garbage-collectible memory usage, more strings, symbols, etc. I'm not sure, though.

**Comment by abo-abo** [comment] 2018-05-14 18:12
> I wonder if it's an issue with increasing non-garbage-collectible memory usage, more strings, symbols, etc. I'm not sure, though

Me too. I wonder how can Ivy produce strings that aren't garbage-collectible. There's no global var that keeps references to the strings, and no circular references.

**Comment by seagle0128** [comment] 2018-05-15 03:53
I didn't reproduced with `emacs -Q` with `ivy`. Actually my college and I encountered this issue with my config  https://github.com/seagle0128/.emacs.d. The issue only occurs after a few days, and was  observed in daemon mode. Not sure for GUI mode. In my experience, the issue disappeared once I disabled `ivy-mode` and `counsel-mode`. Occurs again if enable.

**Comment by basil-conto** [comment] 2018-05-15 08:48
> The issue only occurs after a few days, and was observed in daemon mode. Not sure for GUI mode.

Just to be clear, when you say "daemon mode", are you referring to a daemon Emacs session, to Emacs running in the TTY, or both? Because daemon and GUI are not mutually exclusive.

**Comment by seagle0128** [comment] 2018-05-15 08:55
@basil-conto I am running Emacs in terminal via SSH, with `server-start` in `init.el`. Generally `emacsclient` is used to open the files. Hope it's clear.

**Comment by c0001** [comment] 2018-06-15 21:02
I found this problem too, also be referring to ivy--add-face, and set the large garbage-collection counts.

I follow the advice by : 
> I wonder if it's an issue with increasing non-garbage-collectible memory usage, more strings, symbols, etc. I'm not sure, though

And waiting for testing the truth whether about this refer.

emacs-version： 26.1
operatioin-system: win10-18030

Usage-like: GUI emacs

**Comment by basil-conto** [comment] 2018-06-15 21:10
> I wonder how can Ivy produce strings that aren't garbage-collectible. There's no global var that keeps references to the strings, and no circular references.

I was mostly speculating, but possibilities include `ivy-last`, increasingly large `obarray` and history lists, and memory leaks.

**Comment by c0001** [comment] 2018-06-16 16:00
Just refer  to the main topic question of this issue, I think the core direction was not whether is daemon or not, because it was found on daily using in GUI side without tramp and any other server reference, just daily usage problem.

So this may the bug by the underlying implementation mechanism of ivy.

>I was mostly speculating, but possibilities include ivy-last, increasingly large obarray and history lists, and memory leaks, no?

Above studying may the cause which I thought too.

**Comment by abo-abo** [comment] 2018-06-18 09:04
> I was mostly speculating, but possibilities include

> ivy-last

This gets overwritten by the new `ivy-last` on each completion. The last one is garbage-collected.

> increasingly large obarray

Might be worth looking into. I have `(length obarray)` at 15121 now.

> history lists

Probably not an issue.

> and memory leaks

If there's a memory leak, it's an Emacs issue that we should report. As far as I understand, there's nothing Elisp can do to cause a memory leak.

**Comment by basil-conto** [comment] 2018-06-18 11:18
> This gets overwritten by the new `ivy-last` on each completion. The last one is garbage-collected.

Sure, but each `ivy-last` value is still able to hog a decent amount of memory, which is what I was listing.

> I have `(length obarray)` at 15121 now.

But AIUI each `obarray` slot can hold multiple interned symbols, so is the overall length of the `obarray` vector representative enough?

> As far as I understand, there's nothing Elisp can do to cause a memory leak.

This is also my understanding, though Elisp can still be written in a leak-y way, e.g. by leaving lots of live markers lying around.

**Comment by c0001** [comment] 2018-06-26 17:20
# Hi mainaner:

Sorry for the long time testing and nothing to feedback!

In the begining, what I thought was the binary-code version cross different emacs-version using caused this problem and with the mechanism of ivy also.

The experience for this debugging of above was takes for about 5 days, of course through limitting the adapted binary-code file for each emacs-version independently but problem occur again tonight. It almostly destroyed the native core stable emotion in my-mind, and then with the attempt for checking the raw-code of ivy, I found follow suspicious code-block:

``` emacs-lisp
(defun ivy--add-face (str face)
  "Propertize STR with FACE.
`font-lock-append-text-property' is used, since it's better than
`propertize' or `add-face-text-property' in this case."
  (require 'colir) ;;=============>***NOTICE THIS ONE****
  (condition-case nil
      (progn
        (colir-blend-face-background 0 (length str) face str)
        (let ((foreground (face-foreground face)))
          (when foreground
            (add-face-text-property
             0 (length str)
             `(:foreground ,foreground)
             nil
             str))))
    (error
     (ignore-errors
       (font-lock-append-text-property 0 (length str) 'face face str))))
  str)
```

With the speculation for this `(require 'colir)`, I adding 'adviced' to  `ivy--add-face` with 'override' optioin for commented this line in the current session (which have the lagging performance now, not to restart emacs), everything has gone!!! GOD!!!!!! TKS.

So the main hole of this issue may be this one , why use 'require' in the frequency-used funcition? I don't understand (I'm the newbie for emacs-lisp).

If this was the trigger , hope for fix it in the next gen or not : could you anwser me that why be that?

Thanks a lot for creating ivy --- the best completion tool in emacs for me  😸 💯  .

**Comment by abo-abo** [comment] 2018-06-26 20:44
> why use 'require' in the frequency-used function?

Indeed, calls to `require` aren't free. And it does call `Fcons`. I'll move the `require` outside.

Thanks for your work on investigating the source of the bug.

**Comment by abo-abo** [comment] 2018-06-26 20:49
@c0001 The `require` is now moved outside, you can remove your advice. Please test for a few days and let us know if the issue is gone.

**Comment by c0001** [comment] 2018-06-27 12:10
@abo-abo I'd cloned swiper  repo for further testing this minor improvement.

According to the cycle of previous testing experience, it may used 5 days with none-closed emacs session for this testing.

Thanks for replying and I will submit the newest report here after testing again.

**Comment by c0001** [comment] 2018-06-30 23:37
@abo-abo  I'd test fiew days and the bug haven't occurred again til now.

**Comment by basil-conto** [comment] 2018-07-01 05:35
If the problem really does lie with repeated calls to `require`, I'd <kbd>M-x</kbd>`report-emacs-bug`<kbd>RET<kbd>.

**Comment by c0001** [comment] 2018-07-01 06:58
> If the problem really does lie with repeated calls to require, I'd `M-x` report-emacs-bug `RET`.

Did it mean that calling  `require`  repeated will not cause this in the original design concept ?  If indeed for this aspect, the bug was long time remaining and without paid attention by Emacs developer organization , reporting this to them was necessary.

**Comment by abo-abo** [comment] 2018-07-03 15:31
@basil-conto Agreed about the memory leak. But still, the code of `require` has to have this code:

    tem = Fmemq (feature, Vfeatures);

And I have this on my system:

    (length features)
    ;; => 667

We don't want to call `memq` on a large list in a loop. And if `require` would be implemented via hash table lookup (which is faster than lists for collections larger than 100 items), we would still probably want to avoid that in a loop.

**Comment by hesampakdaman** [comment] 2018-08-28 14:28
I've had performance issues with GUI `Emacs 26` and the profiler indicates that it was `ivy-read` that consumed all the CPU power. However, I have multiple displays and the issue only occurs on monitors where I had had used `emacsclient` in a shell. Therefore, I tested using `Emacs` without `(server-start)` in my config and the issue _seems_ to have disappeared.

**Comment by abo-abo** [comment] 2018-09-06 15:28
It seems like this is fixed now, so I'll close it. If it's still an issue, please create a new ticket referencing this one.

**Closed by abo-abo** 2018-09-06 15:28 UTC
