### ISSUE TITLE
How to create a custom ivy-read function?

### ISSUE THREAD

**Issue by SreenivasVRao** [abo-abo/swiper#2824] opened 2021-03-09 00:07 UTC
Hi abo-abo - thank you so much for swiper/counsel/ivy. Love using this setup!

I tried writing a simple ivy-read function:

```
(setq counsel-remote-compile-history '())
(defun counsel-remote-compile (&optional dir)
  (interactive)
  (ivy-read "Run on Dev-Desk: "
            (remove-duplicates counsel-remote-compile-history)
            :action (lambda (x) (let* ((remotehost "/ssh:user@hostname.com:")
                                       (remotepath (get-package-dir (buffer-file-name)))
                                       (default-directory (concat remotehost remotepath)))
                                  (counsel-compile--action x)))
            :keymap counsel-compile-map
            :history 'counsel-remote-compile-history
            :caller 'counsel-remote-compile))
```

But the `remove-duplicates` command doesn't seem to work.

I see the following in the list I defined. It seems like there are a lot of duplicates and anything I type, gets pushed into the history, instead of only the commands executed. (`bb c`, `bb`, `do`, `dock` etc are partial input to get the completion I needed)

```
(#("bb clean && bb release" 0 22
   (ivy-index 8))
 #("do" 0 2
   (ivy-index 0))
 "docker logs DiagnosticsHubService -f"
 #("rde" 0 3
   (ivy-index 0))
 "rde wflow run" "rde wflow run"
 #("bb " 0 3
   (ivy-index 2))
 #("d" 0 1
   (ivy-index 1))
 "docker logs DiagnosticsHubService -f"
 #("rde wflow run" 0 13
   (ivy-index 2))
 #("dock" 0 4
   (ivy-index 0))
 "docker logs DiagnosticsHubService -f" "bb release"
 #("docker logs DiagnosticsHubService -f" 0 36
   (ivy-index 0))
 #("bb c" 0 4
   (ivy-index 0))
 #("rd" 0 2
   (ivy-index 0))
 "rde stack stop && rde stack build && rde stack start"
 #("bb rele" 0 7
   (ivy-index 0))
 #("rde stack stop && rde stack build && rde stack start" 0 52
   (ivy-index 0))
 #("bb release" 0 10
   (ivy-index -1))
 #("bb run build:noUpload" 0 21
   (ivy-index 0)))
```

**Comment by basil-conto** [comment] 2021-03-10 21:04
Does the duplication still happen if you don't use the internal function `counsel-compile--action`?

**Comment by basil-conto** [comment] 2021-03-10 23:07
> What function should I use instead?

Whichever does what you're after, of course ;).

Have you tried calling the built-in `compile` function directly?

**Comment by SreenivasVRao** [comment] 2021-03-11 01:16
I did try that. I still see multiple entries, including partial inputs I
supplied to filter the list.

**Comment by basil-conto** [comment] 2021-03-11 12:04
Sorry, could you please try to provide a more detailed, ideally reproducible, description of your issue?  "It doesn't work for me" isn't much to go off, and so far it sounds to me like there is something in your local configuration leading to this issue.  Can you reproduce it from `emacs -Q` or `make plain`?

Here's what I tried:

1. `emacs -Q`
2. `M-x package-initialize RET`
3. ```el
   (require 'counsel)

   (defvar my-remote-compile-history ())

   (defun my-remote-compile ()
     (interactive)
     (ivy-read "" (delete-dups (copy-sequence my-remote-compile-history))
               :action #'compile
               :keymap counsel-compile-map
               :history 'my-remote-compile-history
               :caller 'my-remote-compile)
     (message ">>> history: %s" my-remote-compile-history))
   ```
4. `M-x eval-buffer RET`
5. `M-x my-remote-compile RET true RET`
6. `M-x my-remote-compile RET false RET`
7. `M-x my-remote-compile RET echo ohce RET`
8. `M-x my-remote-compile RET RET`
9. `C-h e`

   The printed `*Messages*` are as expected:

   ```
   >>> history: (true)
   Compilation finished
   >>> history: (false true)
   Compilation exited abnormally with code 1
   >>> history: (echo ohce false true)
   Compilation finished
   >>> history: (echo ohce false true)
   Compilation finished
   ```

Emacs version: `GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2021-03-11`
Ivy version: `ivy-0.13.4.0.20210310.115948`
Counsel version: `counsel-0.13.4.0.20210310.175314`

**Comment by nbfalcon** [comment] 2021-03-20 09:58
@SreenivasVRao you'll need to use `(remove-duplicates counsel-remote-compile-history :test #'string=)`, since `remove-duplicates` compares using `eq` by default, which requires that the strings in the history point to the same underlying objects, not only that their contents are identical.
```emacs-lisp
(string= "ab" "ab") ; true
(eq "ab" "ab") ; false, different string objects
```

As a side note, `cl` is deprecated, so you should use `cl-remove-duplicates` instead.

**Comment by basil-conto** [comment] 2021-03-20 11:16
Ouch, I forgot `cl-lib` defaults to `eql` equality.  Thanks for pointing that out.

You can also use `equal` or `equal-including-properties` instead of `string=` depending on your needs.

Is there anything left to solve here, or can this issue be closed?

**Comment by SreenivasVRao** [comment] 2021-03-20 21:54
Thanks to both of you for the helpful tips! :)

This is what I came up with initially:

```
(defun counsel-remote-compile ()
  (interactive)
  (ivy-read "Run on Dev-Desk: "
            (cl-delete-duplicates counsel-remote-compile-history :test #'string=)
            :action (lambda (x) (let* ((remotehost "/ssh:user@hostname:")
                                       (remotepath (sreeni-get-package-dir (buffer-file-name)))
                                       (default-directory (concat remotehost remotepath)))
                                  (compile x)))
            :keymap counsel-compile-map
            :history 'counsel-remote-compile-history
            :caller 'counsel-remote-compile))
```

1. `string=` nearly worked. But I was still seeing values like the following for `counsel-remote-compile-history`
```
(#("bb clean && bb release" 0 22
   (ivy-index 8))
 #("do" 0 2
   (ivy-index 0)))
```

If you compare it to Basil's example above, it should just be `("bb clean && bb release" "do")`
Not sure where the extra stuff is coming from. But duplicates were being filtered out. 

I was still seeing partial input being added to the history variable even if I chose an element from the list.
I read the implementation of `counsel-compile` and found `add-to-history` being used.

I modified the function as follows:

```

(defun counsel-remote-compile ()
  (interactive)
  (ivy-read "Run on Dev-Desk: "
            (cl-delete-duplicates counsel-remote-compile-history :test #'string=)
            :action (lambda (x) (let* ((remotehost "/ssh:user@hostname:")
                                       (remotepath (sreeni-get-package-dir (buffer-file-name)))
                                       (default-directory (concat remotehost remotepath)))
                                  (compile x)
                                  (add-to-history 'counsel-remote-compile-history x)
                                  ))
            :keymap counsel-compile-map
            :caller 'counsel-remote-compile))
```

Note that instead of the `:history` arg, I modify it in the `:action`.  And this works perfectly :)

**Comment by nbfalcon** [comment] 2021-03-20 22:03
@SreenivasVRao what you are seeing are so-called "string properties": strings (and buffers) can have property names associated with values in certain ranges. Some properties are recognized by various parts of emacs, e.g. `face` to handle display.

**Comment by basil-conto** [comment] 2021-03-20 22:26
> This is what I came up with initially:

Note that `cl-delete-duplicates` is a destructive operation that can leave its argument in an unexpected state. To avoid subtle surprises, better to either use `cl-remove-duplicates` instead, or assign the result of the destructive operation back to the variable being modified, i.e. write `(setq x (cl-delete-duplicates x ...))` instead of just `(cl-delete-duplicates x ...)`.

For more info on this, see [`(info "(elisp) Sets And Lists")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Sets-And-Lists.html).

> I read the implementation of `counsel-compile` and found `add-to-history` being used.

But your last two examples don't make use of `counsel-compile`, so that can't possibly be related, right?

> Not sure where the extra stuff is coming from.

Like @nbfalcon said, those are just string properties added and used internally by `ivy-read`, and you can safely ignore them.  They don't affect string equality or identity under `eq`, `equal`, or `string=`, only under `equal-including-properties`:

```el
(equal "foo" #("foo" 0 3 (prop val))) ;; => t
(equal-including-properties "foo" #("foo" 0 3 (prop val))) ;; => nil
(message #("foo" 0 3 (prop val))) ;; prints "foo"

For more info on this, see [`(info "(elisp) Text Props and Strings")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Props-and-Strings.html).

> Note that instead of the `:history` arg, I modify it in the `:action`. And this works perfectly :)

So given the above this is (and should be) unnecessary, and I'm therefore closing this report.

Thanks!

**Closed by basil-conto** 2021-03-20 22:26 UTC
Labels: question, support
