### ISSUE TITLE
seemingly random loss of font-lock in candidates

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#29] opened 2015-03-23 03:49 UTC
Tested with different themes, solarized-dark, solaried-light, and the default, with and without customized swiper/ivy faces:
![screen shot 2015-03-22 at 1 08 22 pm](https://cloud.githubusercontent.com/assets/4935788/6773940/7508be78-d0d5-11e4-8c0e-61d0811d6ed0.png)
![screen shot 2015-03-22 at 1 09 33 pm](https://cloud.githubusercontent.com/assets/4935788/6773938/7507e840-d0d5-11e4-86bc-99a3de1f3dc1.png)
![screen shot 2015-03-22 at 1 10 08 pm](https://cloud.githubusercontent.com/assets/4935788/6773936/75066290-d0d5-11e4-908d-94a41021bdc0.png)
![screen shot 2015-03-22 at 8 41 12 pm](https://cloud.githubusercontent.com/assets/4935788/6773937/750751f0-d0d5-11e4-8501-3d9ec19daa3a.png)
![screen shot 2015-03-22 at 8 43 41 pm](https://cloud.githubusercontent.com/assets/4935788/6773939/75086fa4-d0d5-11e4-8501-7719047cad4f.png)

**Comment by abo-abo** [comment] 2015-03-23 07:50
What's your Emacs version? The font-lock things are version-dependent.

**Comment by zhaojiangbin** [comment] 2015-03-23 16:25
I am using 24.4, the "Emacs Mac Port": https://github.com/railwaycat/emacs-mac-port

The exact version info is:

GNU Emacs 24.4.4 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2014-11-21 on Atago.local

It's a minor issue. It does not really bother me much. I have not been able to reduce the reproduction to the minimum. If you don't have the facility to reproduce it, by all means ignore the issue.

**Comment by abo-abo** [comment] 2015-03-23 16:38
I can't reproduce on GNU/Linux Emacs 24.4.91.2.
Do you get it consistently for some file, or does it just come and go?

**Comment by zhaojiangbin** [comment] 2015-03-23 16:50
It just comes and goes.

**Comment by tsdh** [comment] 2015-04-18 05:41
I have that, too, with the emacs git HEAD of today (c05d1f047b3fd14df2169e41abc7c554704c2804).

But AFAICS, only the matches aren't fontified whose originals haven't been fontified yet, too.  I.e., it is a large buffer where `swiper-font-lock-ensure` didn't do its action because `(buffer-size)` is larger than 100000.  As soon as I've visited some match and thus JIT lock fontified the region around it, it'll show up fontified in the matches in the next `swiper` invocation.

@zhaojiangbin Can't that be the reason for your observations, too?  Or do you encounter a situation where some candidate that was fontified by `swiper` invocation N isn't fontified anymore with invocation N+1?

**Comment by zhaojiangbin** [comment] 2015-04-19 23:55
@tsdh It is probably not my case.

If you look at the screenshots attached above, in particular the first and third, you can see that some of the matched lines were fontified in the original buffer while the corresponding candidates were not.

And those elisp buffers are never that large.

**Comment by zhaojiangbin** [comment] 2015-04-20 00:05
@tsdh Sorry I spoke too soon.

I tested it again. It does appear to be what you were observing: As I visit more regions in the original buffer to have lines fontified, more candidates in subsequent invocations of swiper show up fontified, even though that the size of original buffer does not need to be greater than 100k in my tests.

**Comment by tsdh** [comment] 2015-04-20 06:09
@zhaojiangbin Yeah, jit-lock only fontifies the regions which are currently visible (plus a bit more to find some safe anchoring point for font-lock).  So even in a small 100 LOC elisp buffer, if your emacs window fits only 50 lines, the other 50 aren't fontified unless you scroll to it.  In the buffer < 100k chars case, swiper forces fontification of the complete buffer.  But if the buffer size is slightly above, it should exhibit the behavior I sketched above.

BTW: One can use stealth JIT lock in order to make emacs fontify currently invisible regions when it is idle.  See `jit-lock-stealth-time` and `jit-lock-stealth-nice`.

**Comment by abo-abo** [comment] 2015-04-20 08:17
> BTW: One can use stealth JIT lock in order to make emacs fontify currently invisible regions when it is idle. See jit-lock-stealth-time and jit-lock-stealth-nice.

Thanks, I'll keep it in mind.

**Comment by basil-conto** [comment] 2018-08-09 12:45
Why is this considered a bug? Is `swiper` expected to ensure all locations corresponding to its candidates are fontified? Wouldn't that be costly? If such behaviour is really desirable, should it come with a toggle option?

**Comment by abo-abo** [comment] 2018-08-09 15:19
OK, after some time of thinking about it, maybe it's time to close this issue.

I think the summary is that `swiper` can try to call `font-lock-ensure` on small buffers of selected `major-mode`s. But for the sake of performance, it's not a strict requirement to have the faces.

**Closed by abo-abo** 2018-08-09 15:19 UTC
Labels: bug

**Comment by basil-conto** [comment] 2018-08-09 15:28
> I think the summary is that swiper can try to call `font-lock-ensure` on small buffers of selected `major-mode`s. But for the sake of performance, it's not a strict requirement to have the faces.

A compromise could be to wait until the number of candidates falls under an arbitrary threshold and only call `font-lock-ensure` on the relevant lines. Obviously this would need to be profiled to determine whether it actually improves on anything.

**Comment by abo-abo** [comment] 2018-08-09 15:37
> A compromise could be to wait until the number of candidates falls under an arbitrary threshold and only call font-lock-ensure on the relevant lines. Obviously this would need to be profiled to determine whether it actually improves on anything.

I remember trying to do partial font locking of only the visible candidates back in 2015. It turned out to be as expensive (or more) as font-locking the whole buffer at once.

**Comment by basil-conto** [comment] 2018-08-09 16:44
Fair enough, thanks.
