### ISSUE TITLE
Counsel-ag won't work with french accented characters

### ISSUE THREAD

**Issue by pseudomyne** [abo-abo/swiper#2819] opened 2021-02-28 09:59 UTC
Hi. 
... But ag (from command line, or with ag-project in emacs) does work with french accented characters. 
Emacs 27.1 | Counsel version: 0.13.0

**Comment by basil-conto** [comment] 2021-03-01 13:24
Could you please describe what you tried, what you saw, and what you expected?  It's not clear which behaviour you are expected from `counsel-ag`.  Thanks.

**Comment by pseudomyne** [comment] 2021-03-02 10:20
Haven't tried anything particular. I have insufficient elisp knowledge to guess what could be wrong. What I expect is **counsel-ag** to return results when searching for keywords containing accented characters (it does not), just as it works with non-accented characters. 
What I'm quite sure of, though, is, as I said, the issue is **counsel** related, since **ag-project** works fine when searching for accented characters.

**Comment by basil-conto** [comment] 2021-03-02 11:44
Thanks for elaborating.

The problem is that `counsel-ag` still uses shell commands rather than calling `ag` directly (which is what `counsel-rg` does, for example).  This means that search strings like `café` are converted into `caf\é` by `shell-quote-argument`.  The solution is to make `counsel-ag` behave more like `counsel-rg`.  I'll try fixing this soon if no-one beats me to it.

**Comment by basil-conto** [comment] 2021-03-10 17:33
Sorry, I was wrong: this is actually a bug with `ag` when doing case-insensitive search.

You can verify this for yourself by trying `ag -i café` in a directory that contains a file with the string `café`.

So I suggest you use `counsel-rg` instead, if possible.

I'd still like to update `counsel-ag` to use processes instead of the shell by default, though.

**Comment by basil-conto** [comment] 2021-03-10 17:41
> So I suggest you use counsel-rg instead, if possible (and maybe report his upstream, if it hasn't been already).

Another workaround is to append ` -- -s` or ` -- -S` to the end of your search string when calling `counsel-ag` interactively.  Or, to do this permanently, add `-s` or `-S` to the end of your `counsel-ag-base-command`.

**Comment by basil-conto** [comment] 2021-03-10 18:02
Yet another workaround is to bind `ivy-case-fold-search` to `nil` around `counsel-ag`, e.g. using [function advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html).

In theory, `counsel-ag` could try to detect non-ASCII characters, and not add the `-i` flag in this case, but I'm not convinced we should go to so much effort to work around what is clearly a bug in `ag`, especially since the case-sensitivity behaviour may be surprising.

What do you think?

**Comment by pseudomyne** [comment] 2021-03-11 08:22
I have tried some of the workarounds you proposed, and still have problems ;)
- `counsel-rg` gives no results for « café », although `rgrep` returns 35 candidates, as many as `ag-project` does ; 
- `counsel-ag -s`  returns no results from `M-x counsel-ag`, and no more when I append `counsel-ag-based-command` with `-s` ; 
- _weird_ : `M-x counsel-ag café -` (with no s) returns 7 results ! 

Thanks for pointing to **rgrep**, which is a lot faster.

**Comment by basil-conto** [comment] 2021-03-11 12:33
> I have tried some of the workarounds you proposed, and still have problems ;)

Life would be boring otherwise!

> * `counsel-rg` gives no results for « café », although `rgrep` returns 35 candidates, as many as `ag-project` does ;

`counsel-rg` calls `rg`, aka `ripgrep`: https://github.com/BurntSushi/ripgrep

`rgrep` is the same as `grep -r`.

How are you running this?  Here's what I tried:

1. `cd "$(mktemp --directory)"`
2. `printf 'café\nκαφέ\n' > foo`
3. `ag café`

   Result:
   ```
   foo
   1:café
   ```

4. `ag -i café`

   Result: Exit with status 1

5. `ag --version`

   Result:
   ```
   ag version 2.2.0

   Features:
     +jit +lzma +zlib
   ```

6. `rgrep café`

   Result: `foo:café`

7. `rgrep -i café`

   Result: `foo:café`

8. `rgrep --version`

   Result: `grep (GNU grep) 3.6`

9. `rg café`

   Result:
   ```
   foo
   1:café
   ```

10. `rg -i café`

    Result:
    ```
    foo
    1:café
    ```

11. `rg --version`

    Result:
    ```
    ripgrep 12.1.1
    -SIMD -AVX (compiled)
    +SIMD +AVX (runtime)
    ```

As you can see, `ag -i` is the only one that fails to find `café`.

> * `counsel-ag -s`  returns no results from `M-x counsel-ag`, and no more when I append `counsel-ag-based-command` with `-s` ;
> * _weird_ : `M-x counsel-ag café -` (with no s) returns 7 results !

Continuing from the same directory as before:

12. `emacs -Q`
13. `M-x package-initialize RET`
14. `M-x counsel-ag RET`
15. `caf`

    Result: `foo:1:1:café`

16. `é`

    Result: `No matches found`

17. ` -- -s`

    Result: `foo:1:1:café`

18. `C-g`
19. `M-: (cl-callf append counsel-ag-base-command (list "-s")) RET`

    Result: `("ag" "--vimgrep" "%s" "-s")`

20. `M-x counsel-ag RET`
21. `café`

    Result: `foo:1:1:café`

22. `C-g`
23. `M-x counsel-rg RET`
24. `café`

    Result: `foo:1:café`

25. `C-g`
26. `M-x emacs-version RET`

    Result: `GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2021-03-11`

27. `M-: (package-desc-version (cadr (assq 'ivy package-alist))) RET`

    Result: `(0 13 4 0 20210310 115948)`

28. `M-: (package-desc-version (cadr (assq 'counsel package-alist))) RET`

    Result: `(0 13 4 0 20210310 175314)`

(These are the latest versions of `ivy` and `counsel` installed from GNU-devel ELPA: https://elpa.gnu.org/devel/)

> Thanks for pointing to **rgrep**, which is a lot faster.

Did you mean `rg`? Because both `ag` and `rg` try to be faster than `rgrep` by using concurrency :).

**Comment by pseudomyne** [comment] 2021-03-12 12:48
:) Alas your answer gets too prolific and specific for my time / skills ratio. 
One day I'll learn how to do proper `emacs -Q` issue tracking...

(yes I guess I meant `rgrep` which I got through `pacman -S ripgrep` ; ` (counsel) M-x` proposes `rgrep`, not `rg` here)

**Comment by basil-conto** [comment] 2021-03-12 13:33
> (yes I guess I meant `rgrep` which I got through `pacman -S ripgrep` ; ` (counsel) M-x` proposes `rgrep`, not `rg` here)

`M-x rgrep RET` is a built-in Emacs command that invokes `rgrep`, aka `grep -r`.

`M-x counsel-rg RET` is a command provided by `counsel.el` that invokes `rg`, aka `ripgrep`.

So `rg = ripgrep`, `rgrep = grep -r`, and `rg ≠ rgrep`.

Confusing, I know :).

Anyway, since this is an issue with `ag` only, and you are able to install `rg`, I'm closing this issue for now.  If you or anyone else wants to report this to `ag`'s issue tracker, submit a patch for `counsel-ag` to work around this, or argue that `counsel-ag` should work around this, then please feel free to do so, and we can think about reopening this issue then.

**Closed by basil-conto** 2021-03-12 13:33 UTC
Labels: wontfix, upstream
