### ISSUE TITLE
Cannot move to same file with `dired-do-rename'

### ISSUE THREAD

**Issue by jdahm** [abo-abo/swiper#39] opened 2015-04-19 19:59 UTC
Using `ivy-mode` with `dired-do-rename` leads to an error: "Cannot move to same file: ..." even when the filename I select with `ivy-read` is clearly different.

**Comment by abo-abo** [comment] 2015-04-19 20:13
I can't reproduce. Can you generate a minimal example, like a directory with 1-2 files and a sequence of actions that leads to a bug?

**Comment by jdahm** [comment] 2015-04-19 20:35
Thanks for the quick response. I've narrowed down the problem: it only happens when you try to rename/move a file out of its current directory. For instance:

1. mkdir ~/tmp/ && cd ~/tmp/
2. touch test.txt

In dired: renaming ~/tmp/test.txt to ~/tmp/test1.txt works and updating the dired buffer shows the file. Renaming it to ~/test.txt gives an error: "Cannot move to the same file: /home/jdahm/tmp/test.txt". Seems like it's getting the wrong string: thinks you want to rename it to the existing filename, not the new one.

**Comment by abo-abo** [comment] 2015-04-19 21:30
Should be fixed now, let me know if there are any other problems.

**Closed** 2015-04-19 21:29 UTC
