### ISSUE TITLE
[Question] How to select the initial inputs

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/swiper#1875] opened 2018-12-27 15:38 UTC
Hello, Thanks for the amazing package! I am enjoying it.

I have a question: After passing `initial-input` to `ivy-read`, how to SELECT the `initial-input` by elisp?

This is a similar requirement with https://github.com/abo-abo/swiper/issues/1867. I've used the workaround via `advice` long time ago, but I think this proposal is better:
 - If region is active, use the selected text for `counsel-*g` and `counsel-git-grep` and all other search tools 
- otherwise use the symbol at point as default search pattern
- then select the pattern in prompt of mini-buffer for changing it easily

It should look like:

![image](https://user-images.githubusercontent.com/140797/50485465-6f170b80-0a30-11e9-8c57-bce7c394d623.png)

Thanks in advance!

**Comment by Alexander-Shukaev** [comment] 2019-01-31 12:15
The solution was drafted in #1871 but was later closed by its author for no obvious reasons.  Somebody has to take it up, perhaps by merely forking the already done changes, incorporating the code review comments and resubmitting another PR.  I don't have time at the moment to work on it and unless nobody takes it up, I'll do it myself at some point later.

**Comment by seagle0128** [comment] 2019-01-31 13:22
@Alexander-Shukaev thank you form the following up.

**Comment by seagle0128** [comment] 2019-02-05 16:09
@abo-abo I just want to know how to select the initial input in ivy via Elise. Thr case is just an example. Thanks!

**Comment by seagle0128** [comment] 2019-02-06 14:56
> Try:
> 
> ```emacs-lisp
> (let ((ivy-initial-inputs-alist '((counsel-git-grep . "test"))))
>   (counsel-git-grep))
> ```

This is not working as the screenshot.

**Comment by abo-abo** [comment] 2019-02-06 16:46
Please elaborate, I don't see how this is any different from the screenshot.

**Comment by contrapunctus-1** [comment] 2020-04-12 04:12
I'm not sure if what I'm facing is a similar issue, or how well the given solutions would work for it.

If I rename a file using `rename-file` or `picpocket-rename` (which calls `(read-file-name "Prompt: " nil file-name nil file-name)`), I'd like to edit the file name itself, which is the default input. Ivy (v20200319 from MELPA) currently seems to not insert that text by default. Pressing TAB, of course, just selects the candidate instead of letting you edit it. (In this case resulting in an 'attempt to rename file to itself' error)

Is there a reason to not insert the default text when the caller provides it? If that is not workable, maybe there could be a way to blacklist the use of Ivy for certain commands?

**Comment by abo-abo** [comment] 2020-04-28 17:21
@contrapunctus-1 I tried <kbd>M-x</kbd> `rename-file`. It will call `ivy-completing-read` twice, first for the file to rename, second for the file to rename to. I chose `~/Downloads/temp.org`, and for the second completion the initial-input was `~/Downloads`, which `ivy-mode` did use. Please open a new issue with a reproducible scenario, if you can.

@seagle0128 I'm closing this issue, since it's been a long time, and it's still not clear what the question is.

**Closed by abo-abo** 2020-04-28 17:21 UTC
