### ISSUE TITLE
counsel-find-file open *.ts file hang need 'C-g' to reopen again

### ISSUE THREAD

**Issue by lvii** [abo-abo/swiper#1572] opened 2018-05-14 15:43 UTC
Hi, 

I used [purcell-emacs.d](https://github.com/purcell/emacs.d/) with `emacs 25.3.1` under Fedora 28.

When I opened my **angular**  typescript code `.ts`  files with `C-x C-f (counsel-find-file)` , minibuffer frozen on opening file path. I have to use `C-g` to close **minibuffer** and reopen the file again with `C-x C-f (counsel-find-file)`. 

`C-x C-f (counsel-find-file)` opened `.html`, `.sh`, `.md` flies only need once,  minibuffer would NOT hang.

**Comment by basil-conto** [comment] 2018-05-14 15:55
Can you please provide more detailed steps, i.e. precisely which keys you type, when you type them, when Emacs freezes, and how you know that Emacs has frozen?

Have you tried reproducing this without `purcell-emacs.d`? How do you know the issue lies with `counsel-find-file` and not `purcell-emacs.d`?

Are the TypeScript files you are opening on a local or remote system?

Please post the backtrace obtained from <kbd>M-x</kbd>`toggle-debug-on-quit`<kbd>RET</kbd> followed by your reproduction scenario. There's a decent chance the issue lies in your configuration, rather than with Counsel, so please try to provide as excruciatingly many details as you can provide; otherwise debugging this will be very hard, if not impossible.

**Comment by basil-conto** [comment] 2018-05-14 15:55
Looks like you've opened a duplicate issue with both projects: https://github.com/purcell/emacs.d/issues/580.

**Comment by lvii** [comment] 2018-05-15 03:55
@basil-conto 

I run emacs in docker and the code base dir was **mounted** by docker.

I run emacs **without** `purcell-emacs.d` and install `counsel` and `ng2-mode` packages manually. There would be **NO problem**.

When I switch back `purcell-emacs.d` config and with `M-x toggle-debug-on-quit RET`.

`C-x C-f` opened file hang without any timeout, here was the screenshot.

![Imgur](https://i.imgur.com/ZGXgkc1.png)

`C-g` showed the debug messages below: http://ix.io/1alV

```
Debugger entered--Lisp error: (quit)
  file-directory-p("/node_modules/.bin/")
  add-node-modules-path()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook typescript-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook typescript-mode-hook))
  run-mode-hooks(typescript-mode-hook)
  typescript-mode()
  set-auto-mode-0(typescript-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer app.module.ts> "/home/py/code/django/zerone/angular/zerone/src/app/app.module.ts" nil nil "/home/py/code/django/zerone/angular/zerone/src/app/app.module.ts" (1076405032 2050))
  find-file-noselect("/home/py/code/django/zerone/angular/zerone/src/app/app.module.ts" nil nil nil)
  find-file("/home/py/code/django/zerone/angular/zerone/src/app/app.module.ts")
  counsel-find-file-action("/home/py/code/django/zerone/angular/zerone/src/app/app.module.ts")
  ivy-call()
  #[642 "\306\307\"A@\306\310\"A@\306\311\"A@\306\312\"A@\306\313\"A@\306\314\"A@\306\315\"A@\306\316\"A@\306	\317\"A@\306\n\320\"A@\306\321\"A@C\306\f\322\"A@\306
\323\"A@\306\324\"A@\306\325\"A@\211\203\222�\211@\326>\203z�\211AA\262\202g�\327>A@\203\211�\330\262\202g�\331\332@\"\210\202g�\210\333\334\335\336\"\335	\"\335\"#!\211\203\322�\337!\203\274�\340\341\342BBBB\202\320�\204\311�\340\343BB\202\320�\333\334\"!\262\210\335\n\"\211\203\n\330\211\211\203\211@\211\344\232\203\361�\211B\202\377�\211A\204\377�\211@@ DBA\266\202\202\336�\210\202\f\345\210\346 \205\f\335
\206\"\337!\205\"\"\347 ?\205:@\206:A\236\2069\336A\236A\203S\350B\"\211\203L\211A\202NC\262\202UC@D\351\352\353 \354 p\330\242E\330&&\355\f!\210\356\357\360\361\351
!\362\"\363$\216\364\330C\211\356\357\365\361\351\"\366\"\367$\240\210\356\357\370\361\351!\371\"\367$\216\372\373\242\"\210\206\313\374FGC\375 \203\337\330\202\352H\204\350\376\202\352HHI\203 JG\340U\203 \f\357HK>\204
\377\201Q�\201R�\fD\"\210\f\211\201S�J@I\266\201T�L\202H\201U�\f\357HK>\2049\377\201Q�\201R�\fD\"\210\f\363H\201V�M\"\330%\210L\201T�=\203\223N\203r\f\357HK>\204j\377\201Q�\201R�\fD\"\210\f\201S�H\202tO\211\201W�\232\204\222\201X�\201Y�P#\201Z�JA\"BL\210\210\f\357HK>\204\247\377\201Q�\201R�\fD\"\210\f\201S�H,\262)\266\202)\201[� \210\f\357HK>\204\314\377\201Q�\201R�\fD\"\210\f\201S�HG\357V\203\372\201\\�\357\340\201]�\f\357HK>\204\363\377\201Q�\201R�\fD\"\210\f\201S�H$\210*\266\204\207" [ivy--actions-list this-command ivy--sources-list ivy--extra-candidates ivy-last ivy--display-transformers-list plist-member :predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller :allow-other-keys) :allow-other-keys nil error "Keyword argument %s not one of (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller)" delete-dups append plist-get t functionp 1 "o" ("default") ("o" identity "default") (original-source) ((original-source)) active-minibuffer-window window-minibuffer-p assoc vector cl-struct-ivy-state selected-frame selected-window ivy--reset-state make-byte-code 0 "\304\305\306\"\210\307\310!\311!\203�\211 \210\210\300	\312H\n>\204\"�\313\314\315	D\"\210	\316H\240\203-�\300\242 \210\317=?\2056�\320 \207" vconcat ...] 48 ("/root/.emacs.d/elpa-25.3/ivy-20180513.1037/ivy.elc" . 75464)]("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
  apply(#[642 "\306\307\"A@\306\310\"A@\306\311\"A@\306\312\"A@\306\313\"A@\306\314\"A@\306\315\"A@\306\316\"A@\306	\317\"A@\306\n\320\"A@\306\321\"A@C\306\f\322\"A@\306
\323\"A@\306\324\"A@\306\325\"A@\211\203\222�\211@\326>\203z�\211AA\262\202g�\327>A@\203\211�\330\262\202g�\331\332@\"\210\202g�\210\333\334\335\336\"\335	\"\335\"#!\211\203\322�\337!\203\274�\340\341\342BBBB\202\320�\204\311�\340\343BB\202\320�\333\334\"!\262\210\335\n\"\211\203\n\330\211\211\203\211@\211\344\232\203\361�\211B\202\377�\211A\204\377�\211@@ DBA\266\202\202\336�\210\202\f\345\210\346 \205\f\335
\206\"\337!\205\"\"\347 ?\205:@\206:A\236\2069\336A\236A\203S\350B\"\211\203L\211A\202NC\262\202UC@D\351\352\353 \354 p\330\242E\330&&\355\f!\210\356\357\360\361\351
!\362\"\363$\216\364\330C\211\356\357\365\361\351\"\366\"\367$\240\210\356\357\370\361\351!\371\"\367$\216\372\373\242\"\210\206\313\374FGC\375 \203\337\330\202\352H\204\350\376\202\352HHI\203 JG\340U\203 \f\357HK>\204
\377\201Q�\201R�\fD\"\210\f\211\201S�J@I\266\201T�L\202H\201U�\f\357HK>\2049\377\201Q�\201R�\fD\"\210\f\363H\201V�M\"\330%\210L\201T�=\203\223N\203r\f\357HK>\204j\377\201Q�\201R�\fD\"\210\f\201S�H\202tO\211\201W�\232\204\222\201X�\201Y�P#\201Z�JA\"BL\210\210\f\357HK>\204\247\377\201Q�\201R�\fD\"\210\f\201S�H,\262)\266\202)\201[� \210\f\357HK>\204\314\377\201Q�\201R�\fD\"\210\f\201S�HG\357V\203\372\201\\�\357\340\201]�\f\357HK>\204\363\377\201Q�\201R�\fD\"\210\f\201S�H$\210*\266\204\207" [ivy--actions-list this-command ivy--sources-list ivy--extra-candidates ivy-last ivy--display-transformers-list plist-member :predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller :allow-other-keys) :allow-other-keys nil error "Keyword argument %s not one of (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller)" delete-dups append plist-get t functionp 1 "o" ("default") ("o" identity "default") (original-source) ((original-source)) active-minibuffer-window window-minibuffer-p assoc vector cl-struct-ivy-state selected-frame selected-window ivy--reset-state make-byte-code 0 "\304\305\306\"\210\307\310!\311!\203�\211 \210\210\300	\312H\n>\204\"�\313\314\315	D\"\210	\316H\240\203-�\300\242 \210\317=?\2056�\320 \207" vconcat ...] 48 ("/root/.emacs.d/elpa-25.3/ivy-20180513.1037/ivy.elc" . 75464)] ("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file))
  ivy-historian--nadvice/ivy-read(#[642 "\306\307\"A@\306\310\"A@\306\311\"A@\306\312\"A@\306\313\"A@\306\314\"A@\306\315\"A@\306\316\"A@\306	\317\"A@\306\n\320\"A@\306\321\"A@C\306\f\322\"A@\306
\323\"A@\306\324\"A@\306\325\"A@\211\203\222�\211@\326>\203z�\211AA\262\202g�\327>A@\203\211�\330\262\202g�\331\332@\"\210\202g�\210\333\334\335\336\"\335	\"\335\"#!\211\203\322�\337!\203\274�\340\341\342BBBB\202\320�\204\311�\340\343BB\202\320�\333\334\"!\262\210\335\n\"\211\203\n\330\211\211\203\211@\211\344\232\203\361�\211B\202\377�\211A\204\377�\211@@ DBA\266\202\202\336�\210\202\f\345\210\346 \205\f\335
\206\"\337!\205\"\"\347 ?\205:@\206:A\236\2069\336A\236A\203S\350B\"\211\203L\211A\202NC\262\202UC@D\351\352\353 \354 p\330\242E\330&&\355\f!\210\356\357\360\361\351
!\362\"\363$\216\364\330C\211\356\357\365\361\351\"\366\"\367$\240\210\356\357\370\361\351!\371\"\367$\216\372\373\242\"\210\206\313\374FGC\375 \203\337\330\202\352H\204\350\376\202\352HHI\203 JG\340U\203 \f\357HK>\204
\377\201Q�\201R�\fD\"\210\f\211\201S�J@I\266\201T�L\202H\201U�\f\357HK>\2049\377\201Q�\201R�\fD\"\210\f\363H\201V�M\"\330%\210L\201T�=\203\223N\203r\f\357HK>\204j\377\201Q�\201R�\fD\"\210\f\201S�H\202tO\211\201W�\232\204\222\201X�\201Y�P#\201Z�JA\"BL\210\210\f\357HK>\204\247\377\201Q�\201R�\fD\"\210\f\201S�H,\262)\266\202)\201[� \210\f\357HK>\204\314\377\201Q�\201R�\fD\"\210\f\201S�HG\357V\203\372\201\\�\357\340\201]�\f\357HK>\204\363\377\201Q�\201R�\fD\"\210\f\201S�H$\210*\266\204\207" [ivy--actions-list this-command ivy--sources-list ivy--extra-candidates ivy-last ivy--display-transformers-list plist-member :predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller :allow-other-keys) :allow-other-keys nil error "Keyword argument %s not one of (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller)" delete-dups append plist-get t functionp 1 "o" ("default") ("o" identity "default") (original-source) ((original-source)) active-minibuffer-window window-minibuffer-p assoc vector cl-struct-ivy-state selected-frame selected-window ivy--reset-state make-byte-code 0 "\304\305\306\"\210\307\310!\311!\203�\211 \210\210\300	\312H\n>\204\"�\313\314\315	D\"\210	\316H\240\203-�\300\242 \210\317=?\2056�\320 \207" vconcat ...] 48 ("/root/.emacs.d/elpa-25.3/ivy-20180513.1037/ivy.elc" . 75464)] "Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
  apply(ivy-historian--nadvice/ivy-read #[642 "\306\307\"A@\306\310\"A@\306\311\"A@\306\312\"A@\306\313\"A@\306\314\"A@\306\315\"A@\306\316\"A@\306	\317\"A@\306\n\320\"A@\306\321\"A@C\306\f\322\"A@\306
\323\"A@\306\324\"A@\306\325\"A@\211\203\222�\211@\326>\203z�\211AA\262\202g�\327>A@\203\211�\330\262\202g�\331\332@\"\210\202g�\210\333\334\335\336\"\335	\"\335\"#!\211\203\322�\337!\203\274�\340\341\342BBBB\202\320�\204\311�\340\343BB\202\320�\333\334\"!\262\210\335\n\"\211\203\n\330\211\211\203\211@\211\344\232\203\361�\211B\202\377�\211A\204\377�\211@@ DBA\266\202\202\336�\210\202\f\345\210\346 \205\f\335
\206\"\337!\205\"\"\347 ?\205:@\206:A\236\2069\336A\236A\203S\350B\"\211\203L\211A\202NC\262\202UC@D\351\352\353 \354 p\330\242E\330&&\355\f!\210\356\357\360\361\351
!\362\"\363$\216\364\330C\211\356\357\365\361\351\"\366\"\367$\240\210\356\357\370\361\351!\371\"\367$\216\372\373\242\"\210\206\313\374FGC\375 \203\337\330\202\352H\204\350\376\202\352HHI\203 JG\340U\203 \f\357HK>\204
\377\201Q�\201R�\fD\"\210\f\211\201S�J@I\266\201T�L\202H\201U�\f\357HK>\2049\377\201Q�\201R�\fD\"\210\f\363H\201V�M\"\330%\210L\201T�=\203\223N\203r\f\357HK>\204j\377\201Q�\201R�\fD\"\210\f\201S�H\202tO\211\201W�\232\204\222\201X�\201Y�P#\201Z�JA\"BL\210\210\f\357HK>\204\247\377\201Q�\201R�\fD\"\210\f\201S�H,\262)\266\202)\201[� \210\f\357HK>\204\314\377\201Q�\201R�\fD\"\210\f\201S�HG\357V\203\372\201\\�\357\340\201]�\f\357HK>\204\363\377\201Q�\201R�\fD\"\210\f\201S�H$\210*\266\204\207" [ivy--actions-list this-command ivy--sources-list ivy--extra-candidates ivy-last ivy--display-transformers-list plist-member :predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller :allow-other-keys) :allow-other-keys nil error "Keyword argument %s not one of (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller)" delete-dups append plist-get t functionp 1 "o" ("default") ("o" identity "default") (original-source) ((original-source)) active-minibuffer-window window-minibuffer-p assoc vector cl-struct-ivy-state selected-frame selected-window ivy--reset-state make-byte-code 0 "\304\305\306\"\210\307\310!\311!\203�\211 \210\210\300	\312H\n>\204\"�\313\314\315	D\"\210	\316H\240\203-�\300\242 \210\317=?\2056�\320 \207" vconcat ...] 48 ("/root/.emacs.d/elpa-25.3/ivy-20180513.1037/ivy.elc" . 75464)] ("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file))
  ivy-read("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (27 keymap (25 . counsel-yank-directory)) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
  counsel-find-file()
  funcall-interactively(counsel-find-file)
  call-interactively(counsel-find-file nil nil)
  command-execute(counsel-find-file)


```

**Comment by basil-conto** [comment] 2018-05-15 09:00
I suggest closing this issue until further notice for the following issues:

1. This issue duplicates https://github.com/purcell/emacs.d/issues/580.
2. Having duplicate issues increases the chances of important and relevant information being posted to only one of the issue trackers.
3. More information has already been posted to https://github.com/purcell/emacs.d/issues/580.
3. The backtrace posted here, as well as the extra information posted to https://github.com/purcell/emacs.d/issues/580, both seem to suggest the underlying issue is not with Counsel.

**Closed** 2018-05-15 10:37 UTC
