### ISSUE TITLE
ivy-completion-in-region-action doesn't properly replace things

### ISSUE THREAD

**Issue by agzam** [abo-abo/swiper#2454] opened 2020-02-11 23:04 UTC
I'm seeing some annoying behavior, but I cannot reproduce it for all major modes and it doesn't seem to be deterministic. 

What happens is that when getting to Ivy from Company popup - `C-/` and then selecting a candidate, then pressing `RET`, it deletes more content than required. In some cases it doesn't delete everything that is supposed to be replacing.

I think `ivy-completion-beg` is not working properly maybe?

Here's for example what happens in clojure-mode

![ivy-completion](https://user-images.githubusercontent.com/1091022/74288409-2b896a80-4ce1-11ea-8344-a411ed141dd9.gif)

upd: I was also able to reproduce it in markdown-mode

**Comment by agzam** [comment] 2020-02-11 23:44
it seems counsel-company needs to update `ivy-completion-beg`, because when I eval `(goto-char ivy-completion-beg)` it doesn't jump to the correct position, it jumps to previous last position.

**Comment by agzam** [comment] 2020-02-12 01:55
I might have improved it by simply rearranging things inside cond

```
(defun counsel-company ()
    "Complete using `company-candidates'."
    (interactive)
    (company-mode 1)
    (unless company-candidates
      (company-complete))
    (let ((len (cond (company-prefix
                      (length company-prefix))
                     (company-common
                      (length company-common)))))
      (when len
        (setq ivy-completion-beg (- (point) len))
        (setq ivy-completion-end (point))
        (ivy-read "Candidate: " company-candidates
                  :action #'ivy-completion-in-region-action
                  :caller 'counsel-company))))
```
currently it's like this: https://github.com/abo-abo/swiper/blob/22028d46476036a8277bdfcb9f506d9657e5b7a5/counsel.el#L396-L411

**Comment by basil-conto** [comment] 2020-05-03 13:25
Could this by any chance be a duplicate of #2385, which was fixed three days ago? In particular, the `cond` expression is slightly different now.

**Comment by abo-abo** [comment] 2020-05-12 14:34
I tested it just now, and I think it's already fixed. Please re-open if that's not the case.

**Closed by abo-abo** 2020-05-12 14:34 UTC
