### ISSUE TITLE
org-set-tags behaviour is broken with swiper

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#177] opened 2015-07-24 12:54 UTC
Single tag setting with `C-q` (calls `org-set-tags` in org-mode buffer) works OK. However setting multiple tags is broken: 
1. org-mode offers ido completion with `org-completion-use-ido`, but it is also broken - `tab` will not let selecting the next candidate, but inserts `:` instead. So, I set `org-completion-use-ido` to `nil`
2. Org then falls back, it seems, to the value of `org-completion-fallback-command` which is `hippie-expand`. This works more or less, allowing `tab` selection of next tag candidate of `org-set-tags`
3. I used `helm` for  a while, which also did not allow multiple tag candidate selection, but at least it offered  `helm-completing-read-handlers-alist` which allowed exclusion of `org-set-tags`.

Now, `ivy-completing-read` also does not allow multiple comma or colon separated tag selection from the completion list (because it looks like `ivy-partial-or-done` binding the `Tab`).

Is there a way to fix this, so that ideally `ivy-completing-read` allows comma or colon separated candidates for some functions which need it?
If this is not possible, could you please consider including an option to exclude certain functions from `ivy-completing-read`?

**Comment by abo-abo** [comment] 2015-07-24 13:37
> Now, ivy-completing-read also does not allow multiple comma or colon separated tag selection from the completion list (because it looks like ivy-partial-or-done binding the Tab).

I understand that you don't get completion on the second tag. But does it still work if you enter the tag manually?

> Is there a way to fix this, so that ideally ivy-completing-read allows comma or colon separated candidates for some functions which need it?

There's no great way to fix this problem without changing it: the problem is ill-posed. This is due to a single candidate selection interface being used by Org to select multiple things.  However, the problem can be made well posed by splitting `org-set-tags` into `org-add-tag` and `org-remove-tag`.  I could add a `counsel-add-remove-tag` function that adds/removes tags one-by-one, if you want.  Also asking @joedicastro, since he raised a similar issue in #91.

> If this is not possible, could you please consider including an option to exclude certain functions from ivy-completing-read?

Of course, such an option should definitely be added.

**Comment by srustamo** [comment] 2015-07-24 13:48
> I understand that you don't get completion on the second tag. But does it still work if you enter the tag > manually?

The `swiper` behaves in following way:
1. if there are no tags at all on an org headline, swiper offer vertical list of tags for selection. Only one tag can be selected from here, after which it exists, inserting that tag on the headline.
2. if there is at least one tag already present and `org-set-tags` is called, swiper does not enter into vertical mode, instead there is usual ido style completion list. See [screenshot](http://i.imgur.com/7WsGIAP.png?1).

**Comment by srustamo** [comment] 2015-07-24 13:59
>There's no great way to fix this problem without changing it: the problem is ill-posed. This is due to a >single candidate selection interface being used by Org to select multiple things. However, the problem >can be made well posed by splitting org-set-tags into org-add-tag and org-remove-tag. I could add a >counsel-add-remove-tag function that adds/removes tags one-by-one, if you want. Also asking >@joedicastro, since he raised a similar issue in #91.

I can't at this point imagine how what you suggest would work, but please add `counsel-add-remove-tag` as I have gut feeling that it would work :smile:

**Comment by abo-abo** [comment] 2015-07-24 15:16
Give it a try, and let me know what you think. Remember:

- <kbd>C-m</kbd> selects and exits
- <kbd>C-M-m</kbd> selects without exiting, so you can select multiple tags.

**Comment by srustamo** [comment] 2015-07-24 16:02
I cloned the repo, the latest commit shows `counsel-org-tag`. I assume this is the function. I put the `counsel.el` file in `swiper-20150724.739` directory in elpa on the path. Byte compiled it. However, I don't see any org-tags related added functions. 

I'm sure I'm doing something wrong. Help, please.

**Comment by srustamo** [comment] 2015-07-24 16:45
OK, I just loaded the `counsel.el` without compiling it. The function showed up. 
However:
1. Running `C-q` in an org file on a heading, which has a tag, does not show the vertical list of tag candidates. The existing tag is shown followed by [No match].
2. If no tags are on the headline, a vertical list of tags is shown. Selecting one, then pressing `C-m` puts the selected tag on a headline. However, `C-M-m` returns `M-RET is undefined`.

**Comment by abo-abo** [comment] 2015-07-24 16:58
> Running C-q in an org file on a heading

I didn't bind it to <kbd>C-q</kbd>. You can call it with <kbd>M-x</kbd> `counsel-org-tag`.
Or bind it later as:

    (define-key org-mode-map (kbd "C-q") 'counsel-org-tag)

Although it's not recommended to override <kbd>C-q</kbd> - `quoted-insert` is an important command.

**Comment by srustamo** [comment] 2015-07-24 17:08
Ah, amazing. This works. :smile: A bit counter-intuitive the way the last candidate is shown as No matches. See [screenshot](http://i.imgur.com/zFmRJuL.png).

**Comment by abo-abo** [comment] 2015-07-24 17:12
> A bit counter-intuitive the way the last candidate is shown as No matches. See screenshot.

That shouldn't happen. Can you provide a test file for which this happens?

**Comment by srustamo** [comment] 2015-07-24 17:25
a simple one line org heading file like this produces [No matches] when `counsel-org-tag` is called and `shell` is typed. 

`**** test						   :RM_Kitchen:shell:`
I suspect you will need to have in your system some agenda files with `shell` tag to populate the list of candidates.

**Comment by abo-abo** [comment] 2015-07-24 18:04
This is what I get:
![counsel-org-tag-1](https://cloud.githubusercontent.com/assets/2937359/8881324/2dbb4c36-323f-11e5-80a8-775f247d0410.png)

**Comment by srustamo** [comment] 2015-07-27 07:11
Could you please share how you set up your tags in *Customize group: org-tags* (or however in other way you set up the tags)?

These seem to be the issues with candidates for `counsel-org-tag`:

1. How the tag candidates list gets populated. It looks `counsel-org-tag` double (triple, etc) lists certain tags, which appear in different agenda files (I set `org-complete-tags-always-offer-all-agenda-tags` to `t`). 
2. If I have `org-tag-persistent-alist` populated with some tags, these also are included as candidates, double, triple etc, listing such tags, if they also appear in other agenda files).
3. I can't comment on [No match] at the end of the list, although there are clearly matches, as the list is not empty.

**Comment by srustamo** [comment] 2015-07-27 07:33
A bit more background to [No matches]: it looks like this is not limited to `counsel-org-tag`. Hitting `C-s` in *Packages* buffer, for example, also shows (No matches), where there clearly are matches. See [screenshot](http://i.imgur.com/a9lnoai.png).

**Comment by abo-abo** [comment] 2015-07-27 08:16
I have no special setup for tags. Just navigate to a heading in a file (not in agenda) and change the tags.

As for `[No matches]` it may come from `icomplete-mode`; do you have that on?

**Comment by srustamo** [comment] 2015-07-27 08:31
Indeed, I did. Disabled it, no more [No match]. I suppose the multiple instances of the same tag in the vertical selection list is `org-mode` issue. 

Thank you for your help.

**Comment by abo-abo** [comment] 2015-07-27 09:00
> I suppose the multiple instances of the same tag in the vertical selection list is org-mode issue.

I'm using `org-get-tags-string` almost plainly: it's probably Org that is introducing the duplicates.  If you give me a minimal example of when the duplicates occur, I can debug this issue.

**Comment by srustamo** [comment] 2015-07-27 09:52
I created to files: test.org and test2.org.
Each of them has only one heading with only one tag:

test.org

**** test							       :tag1:

test2.org

**** test2								   :: :tag2:
(incidentally, `counsel-org-tag` when removing the last tag leaves behind `::`).

There are only these two files in org-agenda: 
`org-agenda-files is a variable defined in org.el.
Its value is ("~/test.org" "~/test2.org")
Original value was nil`

`org-complete-tags-always-offer-all-agenda-tags` is set to `t`.

Now, if you are in test2.org buffer and call `counsel-org-tag`, three tags are shown (i.e. tag2 is duplicated). Screenshot below.

<img width="503" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/8903081/bdca2316-346e-11e5-838e-9ccf1bb8a744.png">

**Comment by srustamo** [comment] 2015-07-27 13:55
Also, `counsel-org-tag` returns error when run on an item of org-agenda: `user-error: Not on a heading`

**Comment by abo-abo** [comment] 2015-07-27 14:46
The duplicates should be gone now.

**Comment by kaushalmodi** [comment] 2015-07-27 17:09
Sorry, now I am onto this issue. I am using the `counsel.el` with duplicates fix. I do not see the duplicates if I call `counsel-org-tag` in the org file buffer. But I see the duplicates when I call the same fn from capture buffer.

I later realized that the duplicates happen when in fact I have `org-complete-tags-always-offer-all-agenda-tags` set to `t`... and I had this in my config:

```el
    (add-hook 'org-capture-mode-hook
              (lambda () (setq-local org-complete-tags-always-offer-all-agenda-tags t)))
```

If I did `(setq org-complete-tags-always-offer-all-agenda-tags t)`, I got duplicates when calling `counsel-org-tag` in both file buffer and capture buffer.

Duplicates are gone in all cases if I don't set `org-complete-tags-always-offer-all-agenda-tags` to `t` at all, either globally or locally.

**Comment by abo-abo** [comment] 2015-07-28 12:06
Can't reproduce the duplicates with the test1.org and test2.org.

And I don't see how there can be duplicates anyway:

    (ivy-read (counsel-org-tag-prompt)
              (lambda (str &rest _unused)
                (delete-dups
                 (all-completions str 'org-tags-completion-function)))
              :history 'org-tags-history
              :action 'counsel-org-tag-action)

The only source of candidates is this call:

    (delete-dups
     (all-completions str 'org-tags-completion-function))

Even if `org-tags-completion-function` were to return duplicates, they are removed.

**Comment by srustamo** [comment] 2015-07-28 13:40
The duplicates are gone indeed. I also don't have problems reported by @kaushalmodi in capture buffer calling `counsel-org-tag`. The only problem remaining it seems is calling it within org-agenda buffer after `C-c a` (runs the command org-agenda).

As reported earlier,  "Also, counsel-org-tag returns error when run on an item of org-agenda: user-error: Not on a heading. C-q works here as described earlier."

**Comment by abo-abo** [comment] 2015-07-28 13:43
> As reported earlier, "Also, counsel-org-tag returns error when run on an item of org-agenda: user-error: Not on a heading. C-q works here as described earlier."

OK, this is expected, since <kbd>C-c C-q</kbd> is bound to two different command when in a buffer or agenda. I've modeled only the first one. I can work on the second one later.

**Comment by kaushalmodi** [comment] 2015-07-28 13:47
> The duplicates are gone indeed. 

I concur. Not sure why I saw that yesterday.

**Comment by srustamo** [comment] 2015-07-28 14:14
@abo-abo Thank you for your time!

**Comment by srustamo** [comment] 2015-07-28 14:24
If you could also please look at org-agenda command for assigning tags to multiple org-agenda list items? 

After `C-c a`, agenda buffer is shown, here, `M` marks items, `B` acts on marked items, showing commands in minibuffer. `+` or `-` is supposed to add or remove tags from the marked items.

**Comment by abo-abo** [comment] 2015-07-28 16:14
Please try the new command in agenda.

**Comment by kaushalmodi** [comment] 2015-07-28 18:25
Thanks. It works great, but not on the marked items. 

But the `C-c C-q` work great in both agenda and org buffers with this:

```el
    (with-eval-after-load 'org
      (bind-key "C-c C-q" #'counsel-org-tag org-mode-map))
    (with-eval-after-load 'org-agenda
      (bind-key "C-c C-q" #'counsel-org-tag-agenda org-agenda-mode-map))
```

**Comment by abo-abo** [comment] 2015-07-28 18:50
> but not on the marked items.

You mean marked with a region? I have left that feature out so far, since I've never used it before.

**Comment by kaushalmodi** [comment] 2015-07-28 18:53
> You mean marked with a region? 

No, marked using `m` and other keys (like in `dired`, `ibuffer`, etc).

You can add/remove flags on multiple items in the agenda by selecting them using `m`, then `B` (`org-agenda-bulk-action`) and then `+` (to add tags) or `-` (to remove tags).

**Comment by abo-abo** [comment] 2015-07-28 18:57
> But I honestly believe this should go as a separate issue item requesting this feature.

Yes, that would be good. Also with a minimal example, since I'm still not completely sure how this marking is supposed to work.

**Comment by srustamo** [comment] 2015-07-29 06:44
`counsel-org-tag-agenda` works with a minor quirk:
I have the following: `org-use-tag-inheritance is a variable defined in org.el. Its value is t`.
This allows not to set tags to subheadings, saving some typing and time.

However, it seems to append an extra `:` to the last tag in the list in agenda view. Having two `:` breaks `org-use-tag-agenda` so, that it does not list the tags already on the heading or subheading. This means removal of such tags is impossible.

[Here](https://gist.github.com/c778af0b361ccc5c0d5e.git) is a test file with relevant tags. These are scheduled, so they appear in the agenda. Once in the agenda, the tag on the subheading looks like so:

<img width="972" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/8951405/d749c750-35e6-11e5-8b14-d48fb193d1a3.png">

**Comment by srustamo** [comment] 2015-07-29 06:53
>>    But I honestly believe this should go as a separate issue item requesting this feature.

>Yes, that would be good. Also with a minimal example, since I'm still not completely sure how this marking is supposed to work.

The `org-agenda-bulk-action` could indeed be a separate issue. I thought that it calls the the same 'org-set-tag', hence did not think it needs to spawn the issue list. @kaushalmodi, could you start that issue, perhaps?

**Comment by abo-abo** [comment] 2015-07-29 13:25
I just tried `org-agenda-bulk-action`, and it works with `ivy-mode` on in the same way as with `ivy-mode` off.  It doesn't offer any tags for completion, but at least if you input the correct tag, it makes the correct change.

**Comment by srustamo** [comment] 2015-07-29 15:18
Yeah, this was a bit cheeky on my part, I should have told you that. I thought you could find a work-around. I did ask this question [here](http://stackoverflow.com/questions/29741633/org-agenda-bulk-action-b-tag-selection-does-not-offer-completion). There is a bit larger tag issue asked on the org mailings list and copied [here](http://stackoverflow.com/questions/28535230/org-use-fast-tag-selection-quote-auto-breaks-tab-completion-non-ascii-tag). 

If there is no quick fix using 'counsel', this issue may indeed belong elsewhere.

**Comment by srustamo** [comment] 2015-07-29 17:13
>counsel-org-tag-agenda works with a minor quirk:
>I have the following: org-use-tag-inheritance is a variable defined in org.el. Its value is t.
>This allows not to set tags to subheadings, saving some typing and time.
>
>However, it seems to append an extra : to the last tag in the list in agenda view. Having two : breaks counsel-org-tag-agenda so, that it does not list the tags already on the subheading. This means removal of such tags is impossible.
>
>Here is a test file with relevant tags. These are scheduled, so they appear in the agenda. Once in the agenda, the tag on the subheading looks like so:

I occurred to me that this behaviour is intended. If org-use-tag-inheritance is t, then subheadings should not be candidates for tag removal. I have not tested a scenario, where an additional to iherited tags is added. This I will test tomorrow.

**Comment by srustamo** [comment] 2015-07-29 17:13
>counsel-org-tag-agenda works with a minor quirk:
>I have the following: org-use-tag-inheritance is a variable defined in org.el. Its value is t.
>This allows not to set tags to subheadings, saving some typing and time.
>
>However, it seems to append an extra : to the last tag in the list in agenda view. Having two : breaks counsel-org-tag-agenda so, that it does not list the tags already on the subheading. This means removal of such tags is impossible.
>
>Here is a test file with relevant tags. These are scheduled, so they appear in the agenda. Once in the agenda, the tag on the subheading looks like so:

It occurred to me that this behaviour is intended. If org-use-tag-inheritance is t, then subheadings should not be candidates for tag removal. I have not tested a scenario, where an additional to iherited tags is added. This I will test tomorrow.

**Comment by srustamo** [comment] 2015-07-30 06:23
Looks like the non-inherited tags show up for removal as expected.

**Comment by abo-abo** [comment] 2015-07-30 08:36
OK, this thread has become too long to bear.
As a summary:

1. `counsel-org-tag` should work now in files and in agenda for adding tags.
2. `ivy-mode` doesn't give completion candidates (but still works) for agenda bulk action.
3. `counsel-org-tag` has some trouble with `org-use-tag-inheritance`.

I'm closing this issue since it was mainly related to item 1 and is now fixed.  Feel free to open new issues for items 2 and 3. But add good minimal examples, since I'm not actually using tags in my Org workflow, so I'm not familiar with all these settings and situations.

**Closed by abo-abo** 2015-07-30 08:36 UTC

**Comment by bright-star** [comment] 2016-12-07 17:54
Are there official docs/snippets for setting up (1.)? I've been looking through these associated issues and can't get the completion to work.

**Comment by narendraj9** [comment] 2017-11-16 19:11
How can I remove tags with `counsel-org-tag` or `counsel-org-tag-agenda`?

**Comment by abo-abo** [comment] 2017-11-16 19:13
@narendraj9 select them again, it's a toggle. <kbd>C-M-m</kbd> is useful here.

**Comment by narendraj9** [comment] 2017-11-16 19:17
@abo-abo Thanks, it works. I started using `ivy`, `swiper` and `counsel` today. Where can I find more about bindings like `C-M-m`?

**Comment by narendraj9** [comment] 2017-11-16 19:18
Thanks for these wonderful packages! :)

**Comment by abo-abo** [comment] 2017-11-16 19:26
> Where can I find more bindings like C-M-m?

The manual is at http://oremacs.com/swiper/. Also here: https://github.com/abo-abo/swiper/blob/master/doc/ivy.org.
