### ISSUE TITLE
counsel-git-grep exits at .csv files

### ISSUE THREAD

**Issue by eeenilsson** [abo-abo/swiper#1289] opened 2017-11-17 08:33 UTC
Using counsel-git-grep and scrolling through list with C-M-n will stop when encountering a .csv file and try to open it. Thereafter the cursor moves from the mini-buffer. This breaks workflow a bit.

**Comment by abo-abo** [comment] 2017-11-17 10:12
Can you reproduce with `emacs -Q`?

**Comment by eeenilsson** [comment] 2017-11-17 12:35
`emacs -Q `does not reproduce it. The error seems to be due to a condlict with "openwith.el". Disabling the latter removes the error (unfortunately for me since I need to open .csv files in an external program).

Thanks for a great package!

**Comment by abo-abo** [comment] 2017-11-17 19:57
You can probably configure `counsel-git-grep` to not trigger `openwith`. What's your config of `openwith`?

**Comment by eeenilsson** [comment] 2017-11-18 12:28
My openwith config:

```
; openwith ======
(require 'openwith)
(openwith-mode t)
(setq openwith-associations '(
			      ;; ("\\.pdf\\'" "xdg-open" (file))
			      ;; ("\\.pdf\\'" "okular" (file))			      
			      ("\\.docx\\'" "xdg-open" (file))
			      ("\\.doc\\'" "xdg-open" (file))
			      ("\\.csv\\'" "xdg-open" (file)) 
			      ("\\.xls*\\'" "xdg-open" (file))
			      ("\\.html\\'" "xdg-open" (file))
			      )
      ) ; "xdg-open" will use system default
```

Simply commenting out the .csv option did not help. (ie scrolling in counsel-git-grep still exited when viewing the  next file in emacs).

**Comment by basil-conto** [comment] 2018-04-24 08:25
A very quick skim of `openwith` suggests the following culprit: https://github.com/emacsmirror/openwith/blob/1dc89670822966fab6e656f6519fdd7f01e8301a/openwith.el#L116-L118

I don't think Ivy/Swiper can or should do anything about this; it sounds like something that can be fixed with `openwith`.

**Comment by abo-abo** [comment] 2018-04-25 10:09
@basil-conto Thanks for chiming in. @eeenilsson Please check if the issue can be fixed using the suggestion. I'll close this issue since it seems solvable and I'd like to keep the total issue count down.

**Closed by abo-abo** 2018-04-25 10:09 UTC
Labels: question

**Comment by basil-conto** [comment] 2018-05-27 15:33
@eeenilsson Unless I'm missing something, the suggestion is to file an issue with the `openwith` package, as signalling an `error` on success (see the linked lines) does not seem like TRT. Given that the `openwith` package seems unmaintained, however, you can try the following advice in the meantime:

```el
(define-advice openwith-file-handler (:around (fn &rest args) my-ignore-errors)
  "Wrap a call to FN on ARGS with `ignore-errors'."
  (ignore-errors (apply fn args)))
```

Disclaimer: guaranteed 100% untested.

**Comment by eeenilsson** [comment] 2018-05-27 15:47
Thanks for the clarification! (bit of a noob here). Have not revisited this for some time, but now when I test it (after updating my system & packages for other reasons) it seems to have been fixed (or possibly it is OS-dependent, but I dont have the facilities to test that at the moment). Keeping your code on ignoring errors - may come in handy anyway. Will post on openwith if the problem reappears on other machines. Best wishes.
