### ISSUE TITLE
counsel-git-grep: sometimes the matched line is not visible when called by C-M-n or C-M-p

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#104] opened 2015-05-12 23:26 UTC
![screen shot 2015-05-12 at 4 08 34 pm](https://cloud.githubusercontent.com/assets/4935788/7600564/421fe98c-f8c1-11e4-9a5f-2f2d9dc7dc5e.png)

I was using `C-M-n` to call out the matched file. The matched line was just below the window bottom to be visible. The matched file was opened in the right hand window, the match line was number 383 while the window was only showing up to line 382.

What's interesting is that, depending on the command that visits them, `C-M-n` or `C-M-p`, sometimes an invisible match can become visible.

In the two screenshots below, the first shows that the current selection was __not__ visible in the file buffer window when visited by `C-M-n`, while the second shows the same candidate became visible when visited by `C-M-p`.

![screen shot 2015-05-12 at 4 16 25 pm](https://cloud.githubusercontent.com/assets/4935788/7600735/ff407b70-f8c2-11e4-86f0-f91773e8407e.png)

![screen shot 2015-05-12 at 4 17 48 pm](https://cloud.githubusercontent.com/assets/4935788/7600715/b7c02250-f8c2-11e4-8262-72c272948003.png)

All the screenshots were taken from same `counsel-git-grep` session.

**Comment by abo-abo** [comment] 2015-05-13 08:23
I can't reproduce this. Can you give a recipe of this happening for `emacs -Q` with a repository that I can access?

**Comment by zhaojiangbin** [comment] 2015-05-13 17:36
I will see if this happens again in my own git repos. Then I can try to set up a reproduction.

**Comment by abo-abo** [comment] 2015-06-09 08:14
Closing an outdated issue without a recipe. Feel free to reopen when you have a recipe.

**Closed by abo-abo** 2015-06-09 08:14 UTC
