### ISSUE TITLE
Make Ivy's completion algorithm "compatible" to the default one and Helm's

### ISSUE THREAD

**Issue by d125q** [abo-abo/swiper#746] opened 2016-10-30 09:27 UTC
In Ivy (using `counsel-M-x`), typing `M-x cust group` gives `customize-apropos-group` as the top candidate, whereas the default completion (`M-x cust-group`) gives `customize-group`.  Helm also has this behavior, i.e., it gives the completion candidates in the same order as the default completion.

**Comment by abo-abo** [comment] 2016-10-30 10:11
Can't reproduce.

**Comment by d125q** [comment] 2016-10-30 10:40
See the outputs of `counsel-M-x` and `helm-M-x` below.
![counsel-M-x](https://cloud.githubusercontent.com/assets/7765538/19836024/70519aaa-9e95-11e6-9653-c4202367a013.png)
![helm-M-x](https://cloud.githubusercontent.com/assets/7765538/19836030/99118874-9e95-11e6-858a-7d7a691603ee.png)

**Comment by abo-abo** [comment] 2016-10-30 11:16
I get a similar screenshot, except it's correct for me. Can you reproduce with `emacs -Q`?

**Comment by d125q** [comment] 2016-10-30 11:37
Yes, I can.  In fact, the above screenshot was done with `--no-site-file --no-init-file` (the colors come from X resources).

**Comment by d125q** [comment] 2016-10-30 11:39
Another example, this time with `cust var`:
![counsel-M-x](https://cloud.githubusercontent.com/assets/7765538/19836344/ea55b34c-9e9d-11e6-8cc9-b321acbaef74.png)
![helm-M-x](https://cloud.githubusercontent.com/assets/7765538/19836345/ed80e410-9e9d-11e6-9240-b52aa603e594.png)

**Comment by rdotdk** [comment] 2016-10-30 12:47
I'm able to reproduce this issue. Typing ```M-x customize variable ``` gives ``` customize-save-variable ``` as first in the list and ``` customize-variable ``` as second in the list. Same for ``` M-x customize group ```. @abo-abo can you please make sure you don't have any other ivy settings. I'm able to reproduce this with the following code,

``` elisp
(package-initialize)
(ivy-mode 1)
```

Similarly ``` M-x eval buffer ``` shows ```checkdoc-eval-current-buffer``` as first in the list and ```eval-buffer``` as second in the list. To get ```eval-buffer``` as first in the list, i have to type ```M-x eval-b```

**Comment by abo-abo** [comment] 2016-10-30 13:33
Here's what's happening in `counsel-M-x`:

    (let* ((cands (all-completions "" obarray #'commandp))
           (cands (cl-remove-if-not
                   (lambda (s)
                     (string-match "^cust.*var" s))
                   cands)))
      cands)
    ;; =>
    ;; ("customize-save-variable"
    ;;  "customize-variable"
    ;;  "customize-variable-other-window"
    ;;  "customize-set-variable")

So the sort order is exactly the same as the entries in the obarray are.

Why I'm getting a different sort order with my config? Because I have `smex` installed and used `customize-variable` at least once: now it has priority over the other candidates.

**Comment by d125q** [comment] 2016-10-30 14:52
> I'm able to reproduce this issue. Typing M-x customize variable gives customize-save-variable as first in the list and customize-variable as second in the list.

This is *especially* annoying.

**Comment by abo-abo** [comment] 2016-10-31 10:07
> This is especially annoying.

This is /easily/ fixed by using `smex`, since you automatically get your own sorting order.
It's also possible to roll your own sorting function if you know what you want.

**Comment by rdotdk** [comment] 2016-10-31 14:16
I just installed ``` smex ``` and I'm getting  last used commands in the first of ``` counsel-M-x ```. Thanks @abo-abo . It would be helpful and avoid confusions if we mention this in readme or in the docs saying that if smex it installed, counsel-M-x will show commands list based on last used. Maybe under a topic like integration with other packages?

**Comment by abo-abo** [comment] 2016-11-01 14:08
@rdotdk PRs for documentation are always welcome. You need an Emacs CA to change the stuff in the repo, e.g. https://github.com/abo-abo/swiper/blob/master/doc/ivy.org.

No access rights are needed to update/extend https://github.com/abo-abo/swiper/wiki.

**Comment by abo-abo** [comment] 2016-11-01 14:10
I'll close this issue, since `smex` is the only approach to user-preferred sorting that's currently good enough; and it's already implemented.

Using rule-based approaches that don't log and adapt to the stuff that you select (e.g. `sting<`) for sorting can't possibly satisfy everyone.

**Closed by abo-abo** 2016-11-01 14:10 UTC
