### ISSUE TITLE
ivy-resume performs the search again

### ISSUE THREAD

**Issue by hisnawi** [abo-abo/swiper#2477] opened 2020-03-08 23:09 UTC
Not sure if I am using ivy-resume correctly or is it a bug, but when doing counsel-projectile-rg search, checking one of the results, the executing ivy-resume, I see the search being done again.
However helm-resume doesn't do the search again and would have the buffer cached somewhere with the position the search was left at.

Is this a bug?

**Comment by abo-abo** [comment] 2020-03-09 19:57
I don't consider this a bug. Having `ivy-resume` call `ivy-read` simplifies the code a great deal. Some caching may be added in the future. But for now I'm closing this as not a bug.

Is there a big performance impact of calling the search again?

**Comment by hisnawi** [comment] 2020-03-09 20:12
It is actually. On big projects it is.

**Comment by abo-abo** [comment] 2020-03-09 20:30
Is `counsel-projectile-rg` a static collection or `:dynamic-collection`? The fix for a static one is fairly easy, just a line of change. Dynamic one is harder.

**Comment by hisnawi** [comment] 2020-03-09 22:27
I am not sure, that is a question for @ericdanan.
But I think it could be as simple as keeping the search buffer when selecting one for the matches, not kill it afterwards.

**Comment by ericdanan** [comment] 2020-03-10 16:59
Hi,
`counsel-projectile-rg` doesn't call `ivy-read` directly but instead calls `counsel-rg`, so it's a dynamic collection.

**Comment by abo-abo** [comment] 2020-03-11 11:46
Thanks, please test. I tested with `counsel-rg`.

**Closed** 2020-03-11 11:45 UTC

**Comment by hisnawi** [comment] 2020-03-11 17:02
Tested and works great.
Thanks for the support on this.
Looking forward for the official release.

**Comment by hisnawi** [comment] 2020-03-13 01:11
@abo-abo One small note that I hope if not much change in the code to be implemented. When the searches started showing up, I start moving to different candidates, but when the search concludes the line goes back to the first candidate (counsel-rg).

Not sure if this should be addressed here or as a separate issue for ivy, but would be great if the line stays where I was had it after the search ends.

Small annoyance, if too much code, then never mind.

**Comment by hisnawi** [comment] 2020-04-15 03:51
@abo-abo is it complicated to accommodate the enhancement I mentioned above? I am seeing this on big projects with many matching lines and it gets hectic starting from the beginning of the minibuffer every time.

**Comment by abo-abo** [comment] 2020-05-01 13:37
@hisnawi Thanks, please test.

**Comment by hisnawi** [comment] 2020-05-01 18:23
Works perfectly, Thank you!

**Comment by mfiano** [comment] 2020-05-16 09:40
This "fix" was very unfortunate. Bisecting why my `ivy-resume` would not re-search after jumping to a candidate, changing it, and re-issuing `ivy-resume` only to now see an old view. I relied on the previous behavior every day for a long time.

**Comment by abo-abo** [comment] 2020-05-17 11:53
@mfiano Please open a new issue with more details, and reference the commit that broke your workflow.

**Comment by hisnawi** [comment] 2020-05-18 15:39
@abo-abo Was this change reversed? With latest, I see the match still go back to the first candidate.

**Comment by abo-abo** [comment] 2020-05-18 15:56
@hisnawi Still works fine for me. Please try to reproduce with `emacs -Q`

**Comment by hisnawi** [comment] 2020-05-18 16:28
I now only have this in my setup (ivy/counsel related)
```
  (use-package ivy
    :ensure t
    )

  (use-package counsel
    :ensure t
    )

  (use-package counsel-projectile
    :ensure t
    )

```
I removed elpa directory and started from scratch.
I still see the behavior of the highlight going back to the first matching candidate.

**Comment by abo-abo** [comment] 2020-05-18 17:24
Do you get this behavior for `counsel-rg`?

**Comment by hisnawi** [comment] 2020-05-18 17:43
Yes, and I also tried with an unchanged doom build and I see the same behavior.

**Comment by abo-abo** [comment] 2020-05-19 07:23
Thanks, please test again.

**Comment by hisnawi** [comment] 2020-05-19 15:09
Tested and works. Thanks!
