### ISSUE TITLE
`counsel-grep-function' chokes on a simple file

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1144] opened 2017-08-08 10:54 UTC
Hi,

Try `counsel-grep` on a simple file:

```
// wa
```

by searching for `war`.  Notice how after one types the last `r`, the `error code 2` is immediately shown.  As far as I could get with the debugging, the value of `string` and `regex` in `counsel-grep-function` look like

```
war
1:// wa
```

```
(war
1://).*?(wa)
```

respectively, which is of course odd.  Please, investigate further.

**Comment by Alexander-Shukaev** [comment] 2017-08-08 11:09
**NOTE:** I've updated the issue.

**Comment by basil-conto** [comment] 2018-04-24 08:31
Can you reproduce this issue from `make plain` or `emacs -Q`? Because I can't.

**Comment by mookid** [comment] 2018-04-24 08:43
I can't either on 25.3.

**Comment by Alexander-Shukaev** [comment] 2018-11-21 13:43
Surprise `(setq-default minibuffer-completing-file-name t)`!

**Comment by Alexander-Shukaev** [comment] 2018-11-21 13:54
I found this comment in the `minibuffer.c` now though:

```
;; minibuffer-completing-file-name is a variable used internally in minibuf.c
;; to determine whether to use minibuffer-local-filename-completion-map or
;; minibuffer-local-completion-map.  It shouldn't be exported to Elisp.
;; FIXME: Actually, it is also used in rfn-eshadow.el we'd otherwise have to
;; use (eq minibuffer-completion-table #'read-file-name-internal), which is
;; probably even worse.  Maybe We should add some read-file-name-setup-hook
;; instead, but for now, let's keep this non-obsolete.
;;(make-obsolete-variable 'minibuffer-completing-file-name nil "future" 'get)
```

Meaning I should simply get rid of this setting as this is not what I thought it is but it really should not be exposed to Emacs Lisp as mentioned there or documented properly.

**Comment by abo-abo** [comment] 2018-11-21 14:36
Indeed, the way to make the problem appear is to configure:

```elisp
(setq minibuffer-completing-file-name t)
```

The default value will not cause the problem:

```elisp
(setq minibuffer-completing-file-name t)
```

Closing the issue. I don't think it makes sense to document this. It's already documented in `minibuffer-completing-file-name`.

**Closed by abo-abo** 2018-11-21 14:36 UTC
