### ISSUE TITLE
Highlights unavailable (as in not matching) results when searching for uppercase text

### ISSUE THREAD

**Issue by etu** [abo-abo/swiper#509] opened 2016-05-12 14:15 UTC
I took this text for my test (Happens to be the description of swiper):

```
This package gives an overview of the current regex search
candidates.  The search regex can be split into groups with a
space.  Each group is highlighted with a different face.

It can double as a quick `regex-builder', although only single
lines will be matched.

It also provides `ivy-mode': a global minor mode that uses the
matching back end of `swiper' for all matching on your system,
including file matching. You can use it in place of `ido-mode'
(can't have both on at once).
```

If I do `M-x swiper` `the`: It will highlight all 3 instances of the word and I can navigate to any of them with up or down arrow.

If I do `M-x swiper` `The`: It will highlight all 3 instances of the word but I can only navigate to the one with big T.

Is this intended or a bug? May be a duplicate of #473.

**Comment by manuel-uberti** [comment] 2016-05-12 17:07
I can't replicate it. I can navigate all the highlighted `the` (`The` included) if I input `the`. I see only `The` if I input `The`. This is with both my Emacs setup and `emacs -Q`.

Which version of Swiper are you using? Could you try with `emacs -Q`?

**Comment by etu** [comment] 2016-05-12 17:47
With uppercase T, all the words is highlighted but only one is selectable:
![2016-05-12-194302_758x580_scrot](https://cloud.githubusercontent.com/assets/461970/15224483/e2c018e8-1879-11e6-8a45-e98a50790fa9.png)

With lowercase T, all the words is highlighted and all is selectable:
![2016-05-12-194317_758x580_scrot](https://cloud.githubusercontent.com/assets/461970/15224484/e2e610f2-1879-11e6-834f-363cf74dd160.png)

```
$ emacs --version
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

My Emacs is started with `emacs -Q` then I've switched to the scratchbuffer and evaluated the lisp in the screenshot before I've pasted the text and ran `M-x swiper`.

Don't mind the broken (as in missing) icons in the toolbar, that's a gtk bug recently in Archlinux.

**Comment by manuel-uberti** [comment] 2016-05-12 17:52
Thanks, much clearer now. I can reproduce the issue on my system too.

**Comment by ardpp** [comment] 2016-05-12 20:46
I think that the behaviour that you expect is not implemented yet. Highlighted and selectable items do not always match. Read @abo-abo 's last answer here https://github.com/abo-abo/swiper/issues/166

**Comment by basil-conto** [comment] 2018-02-09 20:06
I cannot reproduce this issue anymore in Emacs versions 24, 25 and 27; it must have been fixed somewhere along the line.

**Comment by manuel-uberti** [comment] 2018-02-09 20:31
Me neither, actually.

**Comment by abo-abo** [comment] 2018-02-09 21:15
Thanks for the checks, I'll close the issue then. If it comes up again, we can have a new issue.

**Closed by abo-abo** 2018-02-09 21:15 UTC
