### ISSUE TITLE
Closing swiper/counsel-M-x with ESC

### ISSUE THREAD

**Issue by sho-87** [abo-abo/swiper#991] opened 2017-05-09 18:20 UTC
I use evil mode and have tried to setup ESC to close things like minibuffers with a single push (usually you need like 3 of them, which gets annoying):

```
(defun minibuffer-keyboard-quit ()
  "Abort recursive edit.
In Delete Selection mode, if the mark is active, just deactivate it;
then it takes a second \\[keyboard-quit] to abort the minibuffer."
  (interactive)
  (if (and delete-selection-mode transient-mark-mode mark-active)
      (setq deactivate-mark  t)
    (when (get-buffer "*Completions*") (delete-windows-on "*Completions*"))
    (abort-recursive-edit)))

(define-key evil-normal-state-map [escape] 'keyboard-quit)
(define-key evil-visual-state-map [escape] 'keyboard-quit)
(define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)
```

However, this doesn't seem to work when using `swiper` or `counsel-M-x`

Is there something I need to add/change so that ESC correctly closes them with a single press?

My current init file is [here](https://github.com/sho-87/dotfiles/blob/master/emacs/init.el) if that helps

**Comment by abo-abo** [comment] 2017-05-09 19:35
Try:

```elisp
(define-key ivy-minibuffer-map (kbd "<ESC>") 'minibuffer-keyboard-quit)
(define-key swiper-map (kbd "<ESC>") 'minibuffer-keyboard-quit)
```

**Comment by sho-87** [comment] 2017-05-09 19:40
Both seem to work, but only on the first press of ESC

For example:
Open emacs, open swiper, ESC works. Open swiper again, ESC no longer works

I'm not sure why this only works on the first ESC, and stops working for every time after?

**Comment by abo-abo** [comment] 2017-05-09 20:50
> I'm not sure why this only works on the first ESC, and stops working for every time after?

Works every time for me.

**Comment by SP00KYB00G13** [comment] 2017-07-05 15:29
After putting:
`(define-key ivy-minibuffer-map (kbd "<ESC>") 'minibuffer-keyboard-quit)`
`(define-key swiper-map (kbd "<ESC>") 'minibuffer-keyboard-quit)`

Into my init.el, I experience the same behaviour as sho-87, here is the output of view-lossage:

` ESC t t [counsel-gtags-dwim]       `                                                                                                                    
` ESC [minibuffer-keyboard-quit] `                                                                                                                       `ESC t t [counsel-gtags-dwim] `                                                                                       
 `ESC ESC ESC ESC ESC ESC ESC ESC ESC ESC RET [nil]`              
` RET [ivy-done]`

**Comment by abo-abo** [comment] 2017-07-05 18:48
@SP00KYB00G13 Maybe your config is different from mine, I still can't reproduce. I try it with `counsel-M-x` and `swiper`.

**Comment by SP00KYB00G13** [comment] 2017-07-06 14:55
@abo-abo 
It exhibits the same behavior Here is the output of view-lossage:
Counsel-M-x:
` ESC [ > ESC [ > 1 ; 3 2 0 1 ; 0 c ESC x x [counsel-M-x]`
`ESC [minibuffer-keyboard-quit]   `                                                                                                                      
`ESC x x [counsel-M-x]`                                                                                                                                  
` ESC ESC ESC ESC ESC ESC C-g [nil]        `                                                                                                              
` C-g [minibuffer-keyboard-quit]    `
Swiper:
` ESC [ > ESC [ > 1 ; 3 2 0 1 ; 0 c C-s [swiper]   `                                                                                                      
` ESC [minibuffer-keyboard-quit]          `                                                                                                               
` C-s [swiper]          `                                                                                                                                 
` ESC ESC ESC ESC C-g [nil]     `                                                                                                                         
` C-g [minibuffer-keyboard-quit] `

If I remove:
`(define-key ivy-minibuffer-map (kbd "<ESC>") 'minibuffer-keyboard-quit)`
`(define-key swiper-map (kbd "<ESC>") 'minibuffer-keyboard-quit)`
From my config I can exit both `swiper` and `counsel-M-x` with `<ESC> <ESC> <ESC>`

**Comment by abo-abo** [comment] 2017-07-06 16:07
@SP00KYB00G13 Can you give me a minimal reproducible init.el file? So I can reproduce the issue with `emacs -Q -l init.el`?

**Comment by SP00KYB00G13** [comment] 2017-07-06 19:21
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

;EVIL mode
(require 'evil)
(setq evil-emacs-state-modes (delq 'ibuffer-mode evil-emacs-state-modes))
(evil-mode 1)
; adding vim keybindings
(evil-ex-define-cmd "Q" 'evil-quit)
(evil-ex-define-cmd "Wq" 'evil-save-and-close)
(evil-ex-define-cmd "Qa" "quitall")
(evil-ex-define-cmd "Wqa" 'evil-save-and-quit)
(define-key evil-window-map "\C-h" 'evil-window-left)

(require 'counsel)
; counsel default cnfg from github
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
(global-set-key "\C-s" 'swiper)
(global-set-key (kbd "C-c C-r") 'ivy-resume)
(global-set-key (kbd "<f6>") 'ivy-resume)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "<f1> f") 'counsel-describe-function)
(global-set-key (kbd "<f1> v") 'counsel-describe-variable)
(global-set-key (kbd "<f1> l") 'counsel-find-library)
(global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
(global-set-key (kbd "<f2> u") 'counsel-unicode-char)
(global-set-key (kbd "C-c g") 'counsel-git)
(global-set-key (kbd "C-c j") 'counsel-git-grep)
(global-set-key (kbd "C-c k") 'counsel-ag)
(global-set-key (kbd "C-x l") 'counsel-locate)
(global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
(define-key ivy-minibuffer-map (kbd "C-j") 'ivy-next-line)
(define-key ivy-minibuffer-map (kbd "C-k") 'ivy-previous-line)
(define-key ivy-minibuffer-map (kbd "<ESC>") 'minibuffer-keyboard-quit)
(define-key swiper-map (kbd "<ESC>") 'minibuffer-keyboard-quit)
(define-key read-expression-map (kbd "C-r") 'counsel-expression-history)

;counsel g-tags
(require 'counsel-gtags)
(add-hook 'c-mode-hook 'counsel-gtags-mode)
(add-hook 'c++-mode-hook 'counsel-gtags-mode)

(with-eval-after-load 'counsel-gtags
  (define-key counsel-gtags-mode-map (kbd "M-t") 'counsel-gtags-dwim)
  (define-key counsel-gtags-mode-map (kbd "M-T") 'counsel-gtags-dwim)
  (define-key counsel-gtags-mode-map (kbd "M-r") 'counsel-gtags-find-reference)
  (define-key counsel-gtags-mode-map (kbd "M-s") 'counsel-gtags-find-symbol)
  (define-key counsel-gtags-mode-map (kbd "M-f") 'counsel-gtags-find-file)
  (define-key counsel-gtags-mode-map (kbd "M-,") 'counsel-gtags-go-backward))
```

I'm not sure if evil is needed to reproduce this but i dont know how to use emacs without it. 

Current emacs:
`GNU Emacs 25.1.1`
on:
`Ubuntu 12.04.5 LTS`

I can investigate if I get the same behaviour on a different pc later today.

**Comment by leiwang-ninjia** [comment] 2017-12-07 10:07
Seems to me the is related to key-bindings issue,  This has nothing related to swiper package.
for example, if i use spacemacs hybrid-mode keybindings, then can reproduce this issue,

**Comment by jgkamat** [comment] 2017-12-08 00:25
For me, 
`(define-key ivy-minibuffer-map [escape] 'minibuffer-keyboard-quit)`

seems to work fine. The `kbd` version seems to not work for me.

**Comment by leiwang-ninjia** [comment] 2017-12-08 02:25
For me, Jut check spacemacs hybrid-mode, when set hybrid-mode-enable-hjkl-bindings to t,
 Esc works well by below settings.  
` (define-key ivy-minibuffer-map (kbd "<escape>")  'minibuffer-keyboard-quit))`

**Comment by abo-abo** [comment] 2017-12-08 10:54
Hi all,

> (define-key ivy-minibuffer-map [escape] 'minibuffer-keyboard-quit)
> (define-key ivy-minibuffer-map (kbd "<escape>") 'minibuffer-keyboard-quit)

Both of these approaches yield the same code. If they work for you, I'm eager to close this issue.

Can everyone please check again?

**Comment by eipplusone** [comment] 2018-01-04 19:28
Had the same issue, `(kbd "<ESC>")` didn't seem to work but `[escape]` works like a charm.

**Comment by abo-abo** [comment] 2018-01-04 20:08
@eipplusone Thanks.
@sho-87 Does that work for you?

**Comment by basil-conto** [comment] 2018-05-30 23:53
Trying to reliably bind `ESC` to something (think terminal escape codes, `meta-prefix-char`, `ESC-prefix`, hard-coded keys, etc.) is not straight-forward and is almost definitely outside the scope of Swiper. I think this issue can be closed, and any remaining reproducible problems reported via `report-emacs-bug`.

**Comment by abo-abo** [comment] 2018-06-11 07:57
@basil-conto You're right, closing.

**Closed by abo-abo** 2018-06-11 07:57 UTC
