### ISSUE TITLE
Doesn't work in polymode (Allow customizable list of modes to bypass font-lock-ensure?)

### ISSUE THREAD

**Issue by arbelt** [abo-abo/swiper#44] opened 2015-04-20 23:19 UTC
I've noticed that swiper doesn't work in polymode (markdown+r) buffers — I think it may have to do with font-locking, though I'll have to dig a little to be sure.  What happens is that as soon as the match navigates to something in a code block, all candidates get lost.

On a related note: would it be possible to make the list of modes ignored by font-lock-ensure customizable?  I could try to make a PR if that helps.  May also want to add paradox to the default list (which loses fontification after running swiper).  This might just make it easier for users to deal with modes where fontification messes up without modifying the package itself.

**Comment by tsdh** [comment] 2015-04-21 05:39
@arbelt paradox looses fontification because it propertizes with the `'face` attribute whereas it should use the `'font-lock-face` attribute.  I added a [paradox issue](https://github.com/abo-abo/swiper/issues/44) for that.

**Comment by abo-abo** [comment] 2015-04-21 06:58
@arbelt, I'm unfamiliar with `polymode`. Can you please provide a minimal polymode file and the command sequence recipe for which `swiper` fails?

**Comment by abo-abo** [comment] 2015-04-21 07:05
@arbelt, I'd like to keep track of the modes for which the font lock fails for science purposes.
So I prefer that people raise issues and I amend my list. I respond pretty quickly, but if you're
impatient, you can use this, which is almost equivalent to a custom var:

```elisp
(defadvice swiper-font-lock-ensure (around swiper-ignore activate)
  (unless (memq major-mode '(paradox-menu-mode))
    ad-do-it))
```

**Comment by arbelt** [comment] 2015-04-22 14:16
Thanks for the quick feedback!

Polymode allows for multiple major modes in a buffer through the use of indirect buffers, so there's some funky stuff happening behind the scenes.  I usually use it to edit `.Rmd` markdown files with R code chunks.  Here's an example that causes the error (without the backslashes... not sure how to insert three backticks in a markdown code chunk):

```
# Some stuff here

\```{r}
# Some more stuff here
\```

And more stuff.
```

Start swiper at the beginning of the file and search for "stuff": it shows all three candidates, but moving to the second one triggers an error.  I'm guessing something to do with the major mode change.

```
Error in post-command-hook (ivy--exhibit): (wrong-type-argument listp font-lock-comment-delimiter-face)
Quit
```

**Comment by abo-abo** [comment] 2015-04-22 14:37
This is looks to be a strictly polymode issue, which you should file with its maintainer.
Here's a simple code that doesn't work because of the `str` produced by `polymode`:

```elisp
(setq str #("4 # Some more stuff here"
            0 2 (face (ivy-current-match))
            2 3 (fontified
                 nil
                 chunkmode
                 t
                 face
                 ((background-color . "#f9f9f9") . font-lock-comment-delimiter-face))
            3 4 (fontified
                 nil
                 chunkmode
                 t
                 face
                 ((background-color . "#f9f9f9") . font-lock-comment-delimiter-face))
            4 24 (fontified
                  nil
                  chunkmode
                  t
                  face
                  ((background-color . "#f9f9f9") . font-lock-comment-face))))

(font-lock-append-text-property 0 (length str) 'face 'ivy-current-match)
```

Meanwhile, I can add a stub to avoid the error message. Swiper will work, just the minibuffer contents won't be highlighted properly until the issue is fixed in `polymode`.

**Closed** 2015-04-22 14:38 UTC
