### ISSUE TITLE
counsel-org-goto-all signals an error

### ISSUE THREAD

**Issue by yogeshwersharma** [abo-abo/swiper#2617] opened 2020-06-17 04:34 UTC
I think it stopped working after some sort of autoupgrade/update. Here is the `--debug-init` log. 
```
Debugger entered--Lisp error: (error "Keyword argument :parent not one of (:initial-input :height :occur :update-fn :init-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)")
  signal(error ("Keyword argument :parent not one of (:initial-input :height :occur :update-fn :init-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)"))
  error("Keyword argument %s not one of (:initial-input :height :occur :update-fn :init-fn :unwind-fn :index-fn :sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)" :parent)
  ivy-configure(counsel-describe-variable :parent counsel-describe-symbol :display-transformer-fn counsel-describe-variable-transformer)
  byte-code("\300\301\302\303\304\305%\210\306\307\310\"\210\311\312\313\314\315DD\316\317\314%\207" [ivy-configure counsel-describe-variable :parent counsel-describe-symbol :display-transformer-fn counsel-describe-variable-transformer ivy-set-actions counsel-describe-function (("I" counsel-info-lookup-symbol "info") ("d" counsel--find-symbol "definition")) custom-declare-variable counsel-describe-function-function funcall function #[0 "\300\207" [describe-function] 1] "Function to call to describe a function passed as parameter." :type] 6)
  require(counsel nil t)
  (not (require (quote counsel) nil t))
  (if (not (require (quote counsel) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote counsel)) :error))
  (condition-case err (if (not (require (quote counsel) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote counsel)) :error)) ((debug error) (funcall use-package--warning2 :catch err)))
  eval-buffer(#<buffer  *load*> nil "/home/yogi/.emacs.d/init.el" nil t)  ; Reading at buffer position 5609
  load-with-code-conversion("/home/yogi/.emacs.d/init.el" "/home/yogi/.emacs.d/init.el" t t)
  load("/home/yogi/.emacs.d/init" t t)
```
The funny thing is that the error keeps changing. It is possible that if I ignore this error, the error will appear later. I started a discussion in emacs.stackexchange here, but I don't know enough emacs debugging to proceed. 
https://emacs.stackexchange.com/questions/59094/some-keybinding-stopped-working-this-morning-with-error-wrong-type-argument-ar

Is there a simple fix for this? 

I have tried going back to a working version (going back in git history for emacs.d), but that strangely does not fix the issue. I am at loss.

**Comment by basil-conto** [comment] 2020-06-17 08:52
Is this a duplicate of #2591? TL;DR: Counsel depends on latest Ivy, and your installed version of Ivy might be too old.

**Comment by yogeshwersharma** [comment] 2020-06-18 14:35
Thanks @basil-conto for pointer to the other issue. 

I did have older version of ivy.el. I now have newer, but now the error has moved to a different place. See below. I was seeing earlier too if I had ignored the counsel loading warning. 

My ivy and counsel versions are as follows: 

```
$ head elpa/ivy-20200615.1103/ivy.el                                                                                  
;;; ivy.el --- Incremental Vertical completYon -*- lexical-binding: t -*-                                              
                                                                                                                                        
;; Copyright (C) 2015-2020  Free Software Foundation, Inc.                                                                               
                                                                                                                                          
;; Author: Oleh Krehel <ohwoeowho@gmail.com>                                                                                         
;; URL: https://github.com/abo-abo/swiper                                                                                        
;; Version: 0.13.0                                                                                                                
;; Package-Requires: ((emacs "24.5"))                                                                                              
;; Keywords: matching                     
```
and 
```
$ head elpa/counsel-20200615.1226/counsel.el                    
;;; counsel.el --- Various completion functions using Ivy -*- lexical-binding: t -*-
                                                                
;; Copyright (C) 2015-2019  Free Software Foundation, Inc.      
                                             
;; Author: Oleh Krehel <ohwoeowho@gmail.com>                    
;; URL: https://github.com/abo-abo/swiper   
;; Package-Version: 20200615.1226
;; Package-Commit: a007ba637d6c6e232fb894e10a40cfc1142a24ae     
;; Version: 0.13.0                           
;; Package-Requires: ((emacs "24.5") (swiper "0.13.0"))
``` 
The stack trace on error: 
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("\\[[0-9]*\\(?:%\\|/[0-9]*\\)\\]" " " nil)
  counsel-outline-title-org()
  #[512 "\306\307\310\"\206	 \311Q\307\312\"\206 \313\307\314\"\206 	\307\315\"\206# \n\307\316\"\206, \307\317\"\2066 
\307\320\"\206@ '\321`\205Q \322	\321$C\323\211\211\211\212\321(eb\210\324
\323\325#\203
\212\326 \327\321\330\331\332!\333\"\334$\216\f )\262\206~ \335\262\321\224b\210\336 \262\n \262	\337=\203\327 X\203\251 \211A\262\210S\262\202\224 V\203\275 \335B\262T\262\202\251 \211\322

$\240\266\340\341\342!\f#\262\202\361 	\343=\203\347 \344\345\"\346Q\262\322$\262BB\262)\335\230\204\\ W\204\\ (T(\202\\ )\237)\207" [outline-regexp outline-level counsel-outline-display-style counsel-outline-path-separator path-separator counsel-outline-face-style "^\\(?:" plist-get :outline-regexp "\\)" :outline-title counsel-outline-title :outline-level :display-style :path-separator :face-style :custom-faces 0 counsel-outline--add-face nil re-search-forward t match-data make-byte-code "\301\300\302\"\207" vconcat vector [set-match-data evaporate] 3 "" point-marker path mapconcat identity reverse headline make-string 42 " " counsel-outline-custom-faces counsel-outline--preselect] 22 ("/home/yogi/.emacs.d/elpa/counsel-20200615.1226/counsel.elc" . 167065)]((:outline-title counsel-outline-title-org :action counsel-org-goto-action :history counsel-org-goto-history :caller counsel-org-goto) nil)
  apply(#[512 "\306\307\310\"\206	 \311Q\307\312\"\206 \313\307\314\"\206 	\307\315\"\206# \n\307\316\"\206, \307\317\"\2066 
\307\320\"\206@ '\321`\205Q \322	\321$C\323\211\211\211\212\321(eb\210\324
\323\325#\203
\212\326 \327\321\330\331\332!\333\"\334$\216\f )\262\206~ \335\262\321\224b\210\336 \262\n \262	\337=\203\327 X\203\251 \211A\262\210S\262\202\224 V\203\275 \335B\262T\262\202\251 \211\322

$\240\266\340\341\342!\f#\262\202\361 	\343=\203\347 \344\345\"\346Q\262\322$\262BB\262)\335\230\204\\ W\204\\ (T(\202\\ )\237)\207" [outline-regexp outline-level counsel-outline-display-style counsel-outline-path-separator path-separator counsel-outline-face-style "^\\(?:" plist-get :outline-regexp "\\)" :outline-title counsel-outline-title :outline-level :display-style :path-separator :face-style :custom-faces 0 counsel-outline--add-face nil re-search-forward t match-data make-byte-code "\301\300\302\"\207" vconcat vector [set-match-data evaporate] 3 "" point-marker path mapconcat identity reverse headline make-string 42 " " counsel-outline-custom-faces counsel-outline--preselect] 22 ("/home/yogi/.emacs.d/elpa/counsel-20200615.1226/counsel.elc" . 167065)] ((:outline-title counsel-outline-title-org :action counsel-org-goto-action :history counsel-org-goto-history :caller counsel-org-goto) nil))
  counsel-outline-candidates((:outline-title counsel-outline-title-org :action counsel-org-goto-action :history counsel-org-goto-history :caller counsel-org-goto) nil)
  counsel-org-goto-all()
  funcall-interactively(counsel-org-goto-all)
  call-interactively(counsel-org-goto-all nil nil)
  command-execute(counsel-org-goto-all)

```

**Comment by yogeshwersharma** [comment] 2020-06-18 14:36
And here is my version of swiper, just in case that is helpful. 
```
$ head -n 15 elpa/swiper-20200319.1334/swiper.el
;;; swiper.el --- Isearch with an overview. Oh, man! -*- lexical-binding: t -*-

;; Copyright (C) 2015-2019  Free Software Foundation, Inc.

;; Author: Oleh Krehel <ohwoeowho@gmail.com>
;; URL: https://github.com/abo-abo/swiper
;; Package-Version: 20200319.1334
;; Version: 0.13.0
;; Package-Requires: ((emacs "24.5") (ivy "0.13.0"))
;; Keywords: matching

```

**Comment by basil-conto** [comment] 2020-06-18 15:00
> The stack trace on error:

Can you please provide a detailed set of steps to reproduce the error, ideally starting with `emacs -Q`? I.e. which keys you type, what happens, etc. If you can't reproduce it from `emacs -Q` then try narrowing down which part of your config gives rise to the error.

Thanks.

**Comment by yogeshwersharma** [comment] 2020-06-18 15:11
So, the error is fixed now. I will give my assessment of what happened, but that might not be accurate, given that I don't understand emacs well. 

After I upgraded all packages (counsel, ivy, swiper) to latest version, the error was still there. But I noticed a warning in emacs' Messages buffer. 
```
Source file ‘/home/yogi/.emacs.d/elpa/counsel-20200615.1226/counsel.el’ newer than byte-compiled file
```
That lead me to [this stackexchange post](https://emacs.stackexchange.com/questions/185/can-i-avoid-outdated-byte-compiled-elisp-files). After recompiling elps directory and restarting emacs, the error is gone. 

On the compilation though, I got this warning. 
```
In counsel-outline-candidates:
counsel.el:5036:8:Warning: function counsel-outline-candidates used to take 0+
    arguments, now takes 0-2
```
Anything I need to do here? 

Thanks so much for your help @basil-conto.

**Comment by yogeshwersharma** [comment] 2020-06-18 16:10
Sorry for another message, but I was mistaken in saying everything is fixed now. I had made a change in counsel.el, which I had forgotten to revert back. Here is the change I need to make for `counsel-org-goto-all` to work. 
```
(defun counsel-outline-title-org ()
  "Return title of current outline heading.
Like `counsel-outline-title' (which see), but for `org-mode'
buffers."
  (let ((statistics-re "\\[[0-9]*\\(?:%\\|/[0-9]*\\)\\]")
        (heading (apply #'org-get-heading (counsel--org-get-heading-args))))
    (if counsel-org-headline-display-statistics
        heading
        heading)))
;;      (org-trim (replace-regexp-in-string statistics-re " " heading)))))
```
If I don't call `replace-regexp-in-string`, then there is no error. Otherwise, I see the error mentioned in [above comment](https://github.com/abo-abo/swiper/issues/2617#issuecomment-646059146). 

I can help you debug, but I don't even know how to do `printf` or log function arguments in emacs-lisp. Let me know how I can help. 

In the mean time, I am not filtering the statistics when listing headings. :-)

**Closed** 2020-06-19 10:33 UTC
Labels: triage

**Comment by basil-conto** [comment] 2020-06-19 10:36
I added a guard against `heading` being `nil` in commit 77748673d3481f9fd1de91283c57ce535404c28f. CCing @bricewge from #2490 to comment.

**Comment by basil-conto** [comment] 2020-06-19 10:37
Thanks for all the info, @yogeshwersharma!
