### ISSUE TITLE
failed to provide feature ‘swiper’

### ISSUE THREAD

**Issue by abrahamparayil** [abo-abo/swiper#1796] opened 2018-11-03 18:21 UTC
My config code:

```
(use-package counsel`
:ensure t
  :bind
  (("M-y" . counsel-yank-pop)
   :map ivy-minibuffer-map
   ("M-y" . ivy-next-line)))

  (use-package ivy
  :ensure t
  :diminish (ivy-mode)
  :bind (("C-x b" . ivy-switch-buffer))
  :config
  (ivy-mode 1)
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "%d/%d ")
  (setq ivy-display-style 'fancy))

  (use-package swiper
  :ensure t
  :bind (("C-s" . swiper)
	 ("C-r" . swiper)
	 ("C-c C-r" . ivy-resume)
	 ("M-x" . counsel-M-x)
	 ("C-x C-f" . counsel-find-file))
  :config
  (progn
    (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)
    (setq ivy-display-style 'fancy)
    (define-key read-expression-map (kbd "C-r") 'counsel-expression-history)
    ))`

```
and I get the following error message:

> ad-Advice-require: Loading file /home/guyfawkes/.emacs.d/elpa/swiper-20181008.1731/swiper.elc failed to provide feature ‘swiper’

**Comment by mookid** [comment] 2018-11-04 00:29
Can't reproduce from make plain.

Knowing your emacs version might help.... 

Can you try to forge a reproduction recipe from make plain?

**Comment by 4br** [comment] 2018-11-04 11:42
@mookid I'm using 26.1.
And regarding forging a reproduction recipe, I really don't know how to do that.
So yeah. Help.

**Comment by abo-abo** [comment] 2018-11-27 21:48
@4br you can check that ivy works correctly by:

```sh
git clone https://github.com/abo-abo/swiper
cd swiper
make plain
```

This will launch an Emacs instance that has only ivy/swiper/counsel loaded, and nothing else. This is an advantage when reporting bugs, because other people can easily reproduce the bug.

If the bug is not reproducible this way, the problem is likely with your config. Here's a good approach to fixing it: https://stackoverflow.com/a/23772957/1350992.

**Comment by brandon-arnold** [comment] 2018-12-13 12:54
I had this issue this morning because, for whatever reason, the package update didn't download `swiper.el` correctly. I downloaded the file manually and put it in my `elpa/swiper-2018-...` folder.

**Comment by basil-conto** [comment] 2018-12-13 13:43
@brandon-arnold You had the exact same error message mentioning `ad-Advice-require`? That artefacts of some [`defadvice`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Porting-old-advice.html) appear in the error message suggests that the problem is either directly or indirectly a result of the OP's configuration or installed packages. Swiper doesn't do anything special w.r.t. package installation, so any problem that doesn't arise as a result of one's configuration should only be transient. For example, there may be some edge cases where `package.el` (or whatever third-party package manager you use) mishandles some error or timeout from ELPA or MELPA, but uninstalling the package and trying to reinstall it later should work in most cases. I try to nuke my `package-user-dir` once or twice a year and reinstall all my packages to reduce the chance of stale byte-code and/or archive information lying around. The less nuclear version of this is to simply `package-reinstall` whichever package is currently being problematic.

In any case, this looks like a support issue that is not directly related to Ivy/Swiper/Counsel, and is probably specific to user configuration, package manager, stale packages, or some combination thereof. I'd be happy to try to assist in debugging the problem, but I think this issue can be closed in the meantime.

Can you try reinstalling Ivy, Swiper, Counsel, and any other related/dependent packages, and report back with as much information (backtraces, error messages, etc.) as possible? Thanks.

**Comment by basil-conto** [comment] 2018-12-13 13:45
@4br Have you run into this error again since your original report?

**Comment by basil-conto** [comment] 2024-04-07 14:48
Closing; feel free to reopen if more information comes to light.

**Closed as not planned by basil-conto** 2024-04-07 14:48 UTC
Labels: moreinfo, support
