### ISSUE TITLE
[ivy] Selecting nothing at a completing-read prompt

### ISSUE THREAD

**Issue by purcell** [abo-abo/swiper#636] opened 2016-08-27 02:24 UTC
With `ivy-mode` enabled, create a new .el file, and execute `auto-insert`. The Keywords prompt of this process uses `completing-read`, and entering nothing (just hitting RET) is the way to indicate that you are done entering keywords. This works with the default `completing-read`, but not with Ivy, since it doesn't allow an empty selection, and there's no obvious workaround other than disabling `ivy-mode`.

FWIW, the `ido-ubiquitous` author had to do some magic for certain commands: https://github.com/DarwinAwardWinner/ido-ubiquitous/issues/74

**Comment by purcell** [comment] 2016-08-27 06:24
Hmm, looks like `C-M-j` does the trick in this situation. I found it hard to discover that, but feel free to close this issue as invalid.

**Comment by abo-abo** [comment] 2016-08-27 06:48
OK, closing. This issue comes up in some shape or form every month or so. I added it to [FAQ](https://github.com/abo-abo/swiper#frequently-asked-questions), and it's in the manual.

I don't want users to be confused, but I've taken all steps I know to avoid this confusion. Suggestions?

**Closed by abo-abo** 2016-08-27 06:48 UTC

**Comment by purcell** [comment] 2016-08-27 07:16
I guess when the `require-match` argument to `completing-read` is false, you could include the currently-typed text as an additional item in the completion list, after all the other matches, and perhaps colour it differently. Not sure how you'd represent the empty string, but the principle would still apply.

**Comment by purcell** [comment] 2016-08-27 07:22
(Background to all this: I'm having a serious go at switching from `ido` to `ivy`. :-) )

**Comment by abo-abo** [comment] 2016-08-27 07:30
> I guess when the require-match argument to completing-read is false, you could include the currently-typed text as an additional item in the completion list, after all the other matches, and perhaps colour it differently.

Thanks for the idea, I'll think about it.

There's a slightly related mechanism in `counsel-find-file`: it hides all dot files, unless your input starts with a dot; but once your input matches nothing else, it tries to offer the dot files that match your input.

**Comment by purcell** [comment] 2016-08-27 23:39
Yeah, exactly! I've always found `ido`'s behaviour confusing when it comes to entering "none of these completions", so this is a great opportunity for `ivy` to make that a smooth and intuitive experience.

(I'm really liking Ivy, by the way. The `ido` muscle memory will take a while to re-train, and it's hard for me to get used to typing a space between match portions, but those are very minor issues!)

**Comment by abo-abo** [comment] 2016-08-28 08:36
> to get used to typing a space between match portions

You can use:

```elisp
(setq ivy-re-builders-alist
      '((t . ivy--regex-fuzzy)))
```

Then you don't need a space, but you get potentially more matches. To sort the matches better, install `flx`; it integrates automatically.

I use the default setting myself, I find it slightly longer to type but more consistent.

**Comment by DarwinAwardWinner** [comment] 2017-05-31 03:09
Hi, I'm the author of ido-ubiquitous, and I can comment on this issue. The problem is that when `completing-read` returns the empty string, it could mean one of two things: it could either be literally the empty string, or it could be an indication that the calling function should use the default. To illustrate the latter usage: 

```lisp
(defun pick-a-fruit-old ()
  (interactive)
  (let* ((default "banana")
         (prompt (format "Pick a fruit (default %s): " default))
         (collection '("apple" "banana" "cherry"))
         (selection (completing-read prompt collection nil t)))
    (when (string= selection "")
      (setq selection default))
    (message "You selected %s" selection)))
```

Try executing that and entering the empty string (i.e. `C-M-j` if you're using ivy). You'll see that even though `require-match` is `t`, `completing-read` will still return the empty string, which the calling code interprets as an instruction to use the default. This usage was once the only way to implement a default, because `completing-read` didn't implement the default argument until later. So there's still some extant code that uses this pattern.

The problem comes because the prompt says "default banana", but if you're using Ivy and you just press RET expecting the default, you get an apple instead, whereas if you're using stock completion and you press RET, you get the banana you were promised. So ivy has turned this normally honest function into a liar. (For a real function that uses this pattern, see `Info-follow-reference`.) You might suggest fixing this problem by having ivy return the empty string if the entry is empty and the user presses RET. But suppose you do that, and then you see this function:

```lisp
(defun pick-a-tool ()
  (interactive)
  (let* ((prompt "Pick a tool: ")
         (collection '("hammer" "screwdriver" "drill"))
         (selection (completing-read prompt collection nil t)))
    (message "You selected %S" selection)))
```

This function clearly expects that you will select one of the tools in the list and not enter an empty string, although it does not prevent you from doing so. With standard completion, pressing RET at this prompt will give you the empty string as your selected tool. But that is clearly a bug, and ivy as it is right now fixes it, since pressing RET will get you a hammer. (For a real-world example of this usage, see `read-char-by-name`.)

A third example is the usage of `completing-read` in the autoinsert package to read a series of keywords, with the empty string indicating the end of the list. In this case, the code is expecting the former behavior: returning the empty string on RET with an empty input. Arguably, this code should be using `completing-read-multiple` instead, but currently, it doesn't. (It was probably written before `completing-read-multiple`.)

So, what should ivy (or ido) do when the user presses RET on an empty input with no default? Should it return the empty string, or should it return the first item of the collection? There's no way to determine automatically which is correct for the given function. Only the function itself knows how it is using `completing-read`. The solution I settled on years ago for ido-ubiquitous was to manually assemble a list of functions/commands/packages that are known to expect an empty string on empty input, and treat those specially. This list used to be quite a bit larger, but as I check now, it's down to just 4 files/packages: info.el (built in), webjump.el (built in), autoinsert.el (built in), and bbdb. Given that 3 out of 4 of these are built in, at this point it has probably become feasible to purge the use of the old way entirely from all current elisp code. So maybe this ultimately isn't a problem that ivy will need to deal with.

**Comment by DarwinAwardWinner** [comment] 2017-05-31 04:50
Now that I realized how few instances remain, I submitted a patch to fix the 3 instances in files that come with Emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27158

**Comment by abo-abo** [comment] 2017-05-31 06:25
@DarwinAwardWinner Thanks.

**Comment by DarwinAwardWinner** [comment] 2017-05-31 11:47
Ok, on that thread, Drew Adams said something that made the behavior of `completing-read-default` make sense for me: 

> "" is just the default default

Given that, I think you might get full backward compatibility by taking this literally and prepending "" to the set of choices when DEF is nil.

**Comment by abo-abo** [comment] 2017-05-31 12:56
@DarwinAwardWinner PRs welcome.

**Comment by DarwinAwardWinner** [comment] 2017-05-31 15:45
I'll test it out and submit a pull request if it seems to work well.

**Comment by abo-abo** [comment] 2017-05-31 18:57
Thanks.

**Comment by DarwinAwardWinner** [comment] 2017-06-04 22:18
So, I ran into another issue while trying to make this proposal work: https://github.com/abo-abo/swiper/issues/1041. I don't have the time right now to dive into the code deeply enough to fix that, so I'm giving up on this for now.

**Comment by exaos** [comment] 2018-01-28 04:32
At last, I know how to quit keywords auto-inserting without using 'C-g' and then switch to the buffer. :-(
