### ISSUE TITLE
counsel-org-tag Not Offering All Completions.

### ISSUE THREAD

**Issue by hannahlbarton** [abo-abo/swiper#1654] opened 2018-07-06 17:14 UTC
Consider the following org file:
#+TAGS: time chemo chromebook  dell computer cycling mobile
* Test Header.                                                        :chemo:

** Test 2.                                                   :chromebook:

* Test 3.

If I remove all the tags from the headings counsel-org-tag offers me a list of all the tags defined in #+TAGS.

However, if I type counsel-org-tag on any of the above headings which already have tags, I am only offered chromebook and chemo as possible completions. I can manually type in any of the other tags and pressing Tab doesn't offer any completions from #+TAGS.

**Comment by basil-conto** [comment] 2018-07-07 12:30
Thanks, I can reproduce this starting from `make plain` with
* `Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /home/blc/.local/share/emacs/26.1.50/lisp/org/)`

and also with
* `Org mode version 9.1.13 (9.1.13-elpaplus @ /home/blc/.emacs.d/elpa/org-plus-contrib-20180702/)`

It looks like Org 9, which shipped with Emacs 26, introduced a new buffer-local variable `org-current-tag-alist` which supersedes the role of `org-tag-alist` and `org-tag-persistent-alist` during tag completion.

Tracking down this issue was relatively straightforward, and I will shortly open a PR fixing it, but in the future please provide as many details as possible from the outset, particularly your Emacs and Ivy/Swiper/Counsel versions, as well as the version of any relevant packages, such as Org. This will greatly help the project maintainers in debugging and fixing the issue. Thanks.

**Comment by abo-abo** [comment] 2018-07-09 15:39
The fix is merged, thanks all.

**Closed** 2018-07-09 15:38 UTC
