### ISSUE TITLE
TAB (complete-symbol) with ivy-mode and org-indent-mode fails with "Error in post-command-hook..."

### ISSUE THREAD

**Issue by tom10x** [abo-abo/swiper#2622] opened 2020-06-20 12:47 UTC
The complete error message is: Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument number-or-marker-p nil)

I've installed ivy + swiper + counsel 0.13.0 and org-mode 9.3.6 with the package manager.

To reproduce from emacs -Q:

(setq tab-always-indent 'complete)
(require 'package)
(package-initialize)
(use-package ivy)
(ivy-mode 1)

Now make a new .org file with the contents:

#+titl

With the cursor after "l", TAB and M-x complete-symbol both suggest "TITLE: " and "title: ". All good. But if I try the same thing after activating org-indent-mode (with M-x org-indent-mode) I get the error message above.

toggle-debug-on-error didn't do anything.

I'm using Emacs 27.0.90

I'm not savvy enough to figure out if this is an ivy-issue or org-indent-mode issue. They both work fine on their own, but they seem to trip each other up in this case.

**Comment by basil-conto** [comment] 2020-06-20 13:03
I can't reproduce this with latest Ivy 20200615 in either Emacs 26, 27, or 28, with Org 9.3 or 9.3.7.

Where are you installing Ivy from? GNU ELPA, MELPA Stable, or MELPA?

Any chance this is related to #2539?

**Comment by tom10x** [comment] 2020-06-20 17:59
@basil-conto That was fast. :-) Yeah I can't reproduce it either with 20200615! Cool, thanks.

I was grabbing ivy from stable.melpa.org but I'll change it up so I get the 20200615 version.

Related to #2539 - possibly, the error messages look the same, but I don't understand the instructions on how to reproduce. Not sure it matters now, issue is resolved afaicm, please go ahead and close this issue if you want. And let me know if you want me to do some testing.

**Comment by basil-conto** [comment] 2020-06-20 18:12
Thanks for confirming! Unfortunately bugfixes aren't backported to "stable"/point releases AFAIK, so unless any other related issues crop up I'm just going to boldly close this as "fixed in the next release".

BTW I'm not sure this is 100% accurate but I'd say the version on MELPA Stable is the same as on GNU ELPA, which should be preferred wherever possible.

**Closed by basil-conto** 2020-06-20 18:12 UTC
Labels: triage

**Comment by tom10x** [comment] 2020-06-20 18:54
@basil-conto Thanks! Yeah that makes sense.

I just wanted to add a note about why I wasn't getting ivy from gnu elpa since it was intentional.

Normally I do try to get packages from gnu but I chose melpa-stable in this case because I couldn't find counsel on gnu. I dunno, it just seemed like a bad idea to get ivy+swiper from gnu and counsel from somewhere else. melpa-stable seemed like the next best thing, and it does have all three, so higher chance that they are in sync, I thought.

Anyway, that was my thought process. I'm not claiming it's correct or anything. :-)

**Comment by basil-conto** [comment] 2020-06-20 19:16
No, it makes sense! Most people want Counsel, but by its design I think it's intentionally left out of GNU ELPA, which together with the co-maintenance of all the packages complicates compatibility.

**Comment by abo-abo** [comment] 2020-06-22 11:34
@tom10x The Ivy version on [GNU ELPA](https://elpa.gnu.org/packages/ivy-0.13.0.tar) bundles ivy, swiper and counsel together.

Here's what might be happening:

1. You install `ivy+swiper+counsel-0.13.0` from GNU ELPA
2. You install something that depends on `counsel`, like `counsel-projectile` from MELPA
3. It pulls in `counsel-20200619.1030`, but not `ivy-20200619.1030`!

And then we have the incompatibility, since `counsel-20200619.1030` can't work properly with `ivy-0.13.0`.

I think the solution should be to publish `ivy-0.13.1`, `swiper-0.13.1`, and `counsel-0.13.1` to GNU ELPA. Then e.g. `counsel-projectile` that's installed from MELPA can use the existing `counsel-0.13.1`. I've just pushed this change to GNU ELPA, it should be visible in the archives within a day.

**Comment by tom10x** [comment] 2020-06-24 08:18
@abo-abo Ah I see, that does sound problematic. Package management i general seems tricky in Emacs. The advice I find online all seem to range from you-should-get-everything-from-gnu to you-should-get-everything-from-melpa. :-)  

Just checked gnu and *-0.13.1 versions are already there, you guys work fast!
