### ISSUE TITLE
Counsel commands issues with tramp 

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#1978] opened 2019-03-22 22:32 UTC
Hi
I am trying to use counsel-rg with a tram buffer but it doesn't work because the command is executed locally maybe a replace of call-process with a process-file call will fix this issue; because I don't know if it is possible to use rg to search in a remote directory.

Similar when I try counsel-grep in a tramp buffer I only get a message: error code 2

**Comment by Alexander-Shukaev** [comment] 2019-03-23 10:41
When one is in remote buffer, the remote binaries are/should be picked up.

**Comment by abo-abo** [comment] 2019-03-25 11:15
> if it is possible to use rg to search in a remote directory

This is not possible, to my knowledge. In any case, it would be very inefficient. Imagine you have a 1 gigabyte repo on the remote. The only way to grep it with a local `rg` is to send all that data to the local machine.

Closing as resolved. The solution is mentioned by @Alexander-Shukaev, just install `ripgrep` on remote.

**Comment by Ergus** [comment] 2019-03-25 14:00
Hi Abo-abo:
Sorry to insist, but it looks like I explained wrong the issue. The local execution was only a comment. The problem is that counsel-grep command return error code 2. even when grep exists in the remote machine.
The normal grep command from emacs works fine, but counsel-grep don't.

**Comment by abo-abo** [comment] 2019-03-25 14:44
Hmm, `counsel-rg` uses `start-file-process-shell-command` which handles remotes. And I recall it working before. Will have to test this later.

**Comment by Alexander-Shukaev** [comment] 2019-03-25 20:47
@abo-abo, He's right and the scenario is not that far-fetched.  Just tested `sudo` (i.e. physically same machine) via `tramp` and indeed `counsel-grep` returns `error code 2`.   At the same time `counsel-rg` has no problems.  This definitely needs to be investigated.  Let me check this.

**Comment by Alexander-Shukaev** [comment] 2019-03-25 21:13
Right, of course, `counsel-rg` produces the following command for example:

```
rg -S --no-heading --line-number --color never --follow --hidden --smart-case   <pattern> .
```

While, `counsel-grep` produces the following command for example:

```
grep -E -n -e <pattern> -i /sudo\:root\@hostname\:/home/user/.bashrc
```

**Comment by Alexander-Shukaev** [comment] 2019-03-25 21:36
So, to fix the problem with `counsel-grep`, the function should be changed as follows:

```emacs-lisp
  (setq counsel-grep-command
        (format counsel-grep-base-command
                "%s" (shell-quote-argument (file-name-nondirectory buffer-file-name))))
  (let ((default-directory (file-name-directory buffer-file-name))
        (init-point (point))
        res)
```

**Comment by Alexander-Shukaev** [comment] 2019-03-26 01:21
From the code perspective I can confirm that `counsel-*g` should already work fine with remote directories and no further changes in this regard are required.  However, even though `counsel-rg` does work fine (again e.g. via `sudo` protocol of `tramp`), at the same time, `counsel-ag` does not as it returns nothing and I suspect that it might be related to #1822 (though adding `--vimgrep` and `.` to `counsel-ag-base-command` did not help in my case).

**Comment by Alexander-Shukaev** [comment] 2019-03-26 01:36
OK, so it looks like the problem with remote `counsel-ag` is `--follow`.  God knows why but we probably should remove it from arguments when `(file-remote-p default-directory)`.

**Comment by abo-abo** [comment] 2019-03-26 09:39
> OK, so it looks like the problem with remote `counsel-ag` is `--follow`. God knows why but we probably should remove it from arguments when `(file-remote-p default-directory)`

`--follow` isn't anywhere in the defaults though. If `--follow` causes problems, the user should not add it in with a customization.

**Comment by abo-abo** [comment] 2019-03-26 09:41
@Alexander-Shukaev Thanks, I integrated your `counsel-grep` change.

@Ergus Please test. Can this issue be closed now?

**Comment by Alexander-Shukaev** [comment] 2019-03-26 14:38
@abo-abo, my point about `--follow` is that it works fine for non-`tramp` cases for `ag`.  Furthermore, it works fine for both `tramp` and non-`tramp` cases for `rg`.  So it's rather questionable whether or not to filter it out for `tramp` cases for `ag`.

**Comment by Ergus** [comment] 2019-03-26 14:42
Hi:
II tested and counsel-grep works as expected. Very thanks!! So I think you can close the issue. 
BTW:
I use counsel-ag a lot, but in some servers I access there is not ag, rg ot pt; only grep. So I search for patterns with patterns like: grep regex -R *
Is it there a way I can do that in counsel-grep?
Once again, thanks,
Ergus

**Closed** 2019-03-26 14:43 UTC

**Comment by Alexander-Shukaev** [comment] 2019-03-26 14:45
I just use plain `rgrep` for that.
