### ISSUE TITLE
Active process in term steals focus from ivy

### ISSUE THREAD

**Issue by Sbozzolo** [abo-abo/swiper#1429] opened 2018-02-04 18:27 UTC
If I have a term buffer with an ongoing process and I invoke ivy-based commands like `counsel-M-x` or `counsel-yank-pop`, as soon as the process writes anything on the stdout term mode steals the focus from the minibuffer. 
![term](https://user-images.githubusercontent.com/9167485/35780800-4d6c4920-099e-11e8-8084-02662f25e6fc.gif)

When the focus is stolen, there's no way to get back to the minibuffer.

A few information about my system:
I am using Gentoo Linux with GNU Emacs 25.3.1. I am also using EXWM as windows manager, and muti-term to handle terminals. The relevant part of my configurations are:
```emacs-lisp
   (use-package ivy
      :diminish ivy-mode
      :ensure t
      :bind
      (("C-x b" . ivy-switch-buffer)
       ("C-s" . swiper)
       ("C-r" . swiper)
       :map ivy-minibuffer-map
       ("C-j" . ivy-immediate-done)
       ("RET" . ivy-alt-done)
       )
      :init
      :config
      (ivy-mode 1)
      (setq-default ivy-use-virtual-buffers t
                    ivy-count-format ""
                    ivy-display-style 'fancy
                    projectile-completion-system 'ivy
                    ivy-initial-inputs-alist
                    '((counsel-M-x . "^")
                      (man . "^")
                      (woman . "^")))
      ;; Press C-p to select an item, then press RET to return it
      ;; (For example when renaming files with the same name)
      (setq ivy-use-selectable-prompt t)
      )

    (use-package counsel
      :diminish counsel-mode
      :ensure ivy
      :init
      (setq-default counsel-mode-override-describe-bindings t)
      (add-hook 'after-init-hook 'counsel-mode)
      :bind
      (("M-x" . counsel-M-x)
       ("C-x C-f" . counsel-find-file)
       ("M-y" . counsel-yank-pop)
       :map ivy-minibuffer-map   ("M-y" . ivy-next-line)
       )
      )

     (use-package eterm-256color
       :ensure t
       :config  (add-hook 'term-mode-hook #'eterm-256color-mode)
       )

     ;; Some terminal functions
     (defun last-term-buffer (l)
       "Return most recently used term buffer."
       (when l
         (if (eq 'term-mode (with-current-buffer (car l) major-mode))
             (car l) (last-term-buffer (cdr l)))))

     (defun get-term ()
       "Switch to the term buffer last used, or create a new one if
         none exists, or if the current buffer is already a term."
       (interactive)
       (let ((b (last-term-buffer (buffer-list))))
         (if (or (not b) (eq 'term-mode major-mode))
             (multi-term)
           (switch-to-buffer b))))

     ;; Better paste
     (defun my/term-paste (&optional string)
       "Paste on terminals"
       (interactive)
       (process-send-string
        (get-buffer-process (current-buffer))
        (if string string (current-kill 0))))


     (use-package multi-term
       :ensure t
       :init
       ;; Fix encoding
       (defadvice multi-term (after advise-multi-term-coding-system)
         (set-buffer-process-coding-system 'utf-8-unix 'utf-8-unix))
       (ad-activate 'multi-term)
       :bind (:map term-raw-map
                   ("C-y" . my/term-paste)
                   ("C-r" . isearch-backward)
                   )
       :config
       (setq multi-term-program "/bin/zsh")

       ;; It would be nice to find a more compact way using remove and add-to-list

       (setq term-bind-key-alist
             '(("C-c C-c" . term-interrupt-subjob)
               ("C-c C-e" . term-send-esc)
               ("C-p" . previous-line)
               ("C-n" . next-line)
               ("C-s" . isearch-forward)
               ("M-r" . isearch-backward)
               ("C-m" . term-send-return)
               ("C-y" . term-paste)
               ("M-f" . term-send-forward-word)
               ("M-b" . term-send-backward-word)
               ("M-o" . term-send-backspace)
               ("M-p" . term-send-up)
               ("M-n" . term-send-down)
               ("M-M" . term-send-forward-kill-word)
               ("M-N" . term-send-backward-kill-word)
               ("<C-backspace>" . term-send-backward-kill-word)
               ("C-r" . term-send-reverse-search-history)
               ("M-d" . term-send-delete-word)
               ("M-," . term-send-raw)
               ("M-." . comint-dynamic-complete)))

       ;; On shells, please handle properly the ansi escape codes
       (add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on)

       ;; (setq term-scroll-to-bottom-on-input t
       ;;   term-scroll-to-bottom-on-output nil
       ;;   term-scroll-show-maximum-output nil)
       )
```
I tried commenting out everything related to term, but nothing changes.

Regards,
sbozzolo

**Comment by abo-abo** [comment] 2018-02-04 19:03
> as soon as the process writes anything on the stdout term mode steals the focus from the minibuffer.

Can't reproduce.

> When the focus is stolen, there's no way to get back to the minibuffer.

`other-window` or `ace-window` are able to select the minibuffer.

**Comment by Sbozzolo** [comment] 2018-02-04 19:08
I tried to move to cursor to the minibuffer with `other-window` but it
doesn't work. Interestingly, if I press M-x, it says that "Command
attempted to use minibuffer while in minibuffer"

**Comment by basil-conto** [comment] 2018-02-04 19:14
> I tried commenting out everything related to term, but nothing changes.

Can you reproduce with `emacs -Q` or by running `make plain` from a checkout of this project? If not, try recursively bisecting your `user-init-file` to pinpoint the package or setting which causes this behaviour.

**Comment by basil-conto** [comment] 2018-02-04 19:15
My crystal ball is telling me that it might be related to multiterm.

**Comment by Sbozzolo** [comment] 2018-02-04 20:49
Your crystal ball was off-track: the problem is with EXWM. The behavior is triggered with:
```emacs-lisp
 (setq exwm-workspace-minibuffer-position 'bottom)
```

**Comment by basil-conto** [comment] 2018-02-04 20:57
> the problem is with EXWM

Ah sorry, I misread that as EWMH, which explains why:

> Your crystal ball was off-track

But such is the problem with crystal balls anyway. :)

**Comment by abo-abo** [comment] 2018-02-05 10:40
> "Command
> attempted to use minibuffer while in minibuffer"

Might be fixed with:

    (setq enable-recursive-minibuffers t)

**Comment by Sbozzolo** [comment] 2018-02-14 05:31
Nothing changes allowing recursive minibuffers

**Comment by basil-conto** [comment] 2018-08-07 13:27
Can this issue be closed?

**Comment by basil-conto** [comment] 2018-11-21 00:56
Ping.

**Comment by Sbozzolo** [comment] 2018-11-21 01:07
The problem has been solved in a recent EXWM update. The issue can be
closed.

**Comment by abo-abo** [comment] 2018-11-21 15:13
OK, thanks.

**Closed by abo-abo** 2018-11-21 15:13 UTC
