### ISSUE TITLE
counsel-describe-variable, counsel-describe-function, others erroring

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#1647] opened 2018-07-04 05:06 UTC
I'm getting a lot of `wrongtype argument stringp, nil` with these functions, as well as errors in `completion-at-point` going from the latest commit.

**Comment by manuel-uberti** [comment] 2018-07-04 06:03
Happens to me, with latest `ivy` and `counsel` from MELPA.

**Comment by bymoz089** [comment] 2018-07-04 07:55
same here, backup from older version is working

**Comment by DamienCassou** [comment] 2018-07-04 08:03
I can reproduce. This is due to 0cf0e6da85a72991afe8e08a0514dad6485cbf76.

**Comment by seagle0128** [comment] 2018-07-04 08:44
Same here. Root cause is https://github.com/abo-abo/swiper/commit/0cf0e6da85a72991afe8e08a0514dad6485cbf76

**Comment by basil-conto** [comment] 2018-07-04 09:59
Cc: @raxod502 

@seagle0128 Would you care to open a PR with that change?

Here's a recipe for the issue:

1. `make plain`
2. <kbd>M-x</kbd>`toggle-debug-on-error`<kbd>RET</kbd>
3. <kbd>C-h</kbd><kbd>f</kbd>
   * Expected result: Minibuffer Elisp function completion
   * Actual result:

         Debugger entered--Lisp error: (wrong-type-argument stringp nil)
           string-match("" nil nil)
           string-match-p("" nil)
           (and (stringp preselect) (string-match-p preselect current))
           (or (and (integerp preselect) (= ivy--index preselect)) (equal current preselect) (and (stringp preselect) (string-match-p preselect current)))
           (not (or (and (integerp preselect) (= ivy--index preselect)) (equal current preselect) (and (stringp preselect) (string-match-p preselect current))))
           (and (not (string= name "")) (not (and ivy--flx-featurep (eq ivy--regex-function 'ivy--regex-fuzzy) (< (length cands) 200))) (not (or (and (integerp preselect) (= ivy--index preselect)) (equal current preselect) (and (stringp preselect) (string-match-p preselect current)))) ivy--old-cands (cl-position current cands :test #'equal))
           (or (cl-position (if (and (> (length name) 0) (eq 94 (aref name 0))) (substring name 1) name) cands :test #'ivy--case-fold-string=) (and ivy--directory (cl-position (concat re-str "/") cands :test #'ivy--case-fold-string=)) (and (eq caller 'ivy-switch-buffer) (> (length name) 0) 0) (and (not (string= name "")) (not (and ivy--flx-featurep (eq ivy--regex-function 'ivy--regex-fuzzy) (< (length cands) 200))) (not (or (and (integerp preselect) (= ivy--index preselect)) (equal current preselect) (and (stringp preselect) (string-match-p preselect current)))) ivy--old-cands (cl-position current cands :test #'equal)) (funcall func re-str cands))
           (ivy-set-index (or (cl-position (if (and (> (length name) 0) (eq 94 (aref name 0))) (substring name 1) name) cands :test #'ivy--case-fold-string=) (and ivy--directory (cl-position (concat re-str "/") cands :test #'ivy--case-fold-string=)) (and (eq caller 'ivy-switch-buffer) (> (length name) 0) 0) (and (not (string= name "")) (not (and ivy--flx-featurep (eq ivy--regex-function 'ivy--regex-fuzzy) (< (length cands) 200))) (not (or (and (integerp preselect) (= ivy--index preselect)) (equal current preselect) (and (stringp preselect) (string-match-p preselect current)))) ivy--old-cands (cl-position current cands :test #'equal)) (funcall func re-str cands)))
           (if (eq this-command 'ivy-resume) nil (ivy-set-index (or (cl-position (if (and (> (length name) 0) (eq 94 (aref name 0))) (substring name 1) name) cands :test #'ivy--case-fold-string=) (and ivy--directory (cl-position (concat re-str "/") cands :test #'ivy--case-fold-string=)) (and (eq caller 'ivy-switch-buffer) (> (length name) 0) 0) (and (not (string= name "")) (not (and ivy--flx-featurep (eq ivy--regex-function 'ivy--regex-fuzzy) (< (length cands) 200))) (not (or (and (integerp preselect) (= ivy--index preselect)) (equal current preselect) (and (stringp preselect) (string-match-p preselect current)))) ivy--old-cands (cl-position current cands :test #'equal)) (funcall func re-str cands))))
           (let* ((caller (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 22))) (func (or (and caller (cdr (assoc caller ivy-index-functions-alist))) (cdr (assoc t ivy-index-functions-alist)) #'ivy-recompute-index-zero)) (case-fold-search (ivy--case-fold-p name)) (preselect (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 7))) (current (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 23)))) (if (eq this-command 'ivy-resume) nil (ivy-set-index (or (cl-position (if (and (> ... 0) (eq 94 ...)) (substring name 1) name) cands :test #'ivy--case-fold-string=) (and ivy--directory (cl-position (concat re-str "/") cands :test #'ivy--case-fold-string=)) (and (eq caller 'ivy-switch-buffer) (> (length name) 0) 0) (and (not (string= name "")) (not (and ivy--flx-featurep (eq ivy--regex-function ...) (< ... 200))) (not (or (and ... ...) (equal current preselect) (and ... ...))) ivy--old-cands (cl-position current cands :test #'equal)) (funcall func re-str cands)))) (if (or (string= name "") (string= name "^")) (progn (ivy-set-index (or (ivy--preselect-index preselect cands) ivy--index)))))
           ivy--recompute-index("^" "^" ("%" "(setf seq-elt)" "*" "+" "-" "/" "/=" "1+" "1-" "1value" "2048-game" "2C-associate-buffer" "2C-command" "2C-split" "2C-two-columns" "5x5" "5x5-crack" "5x5-crack-mutating-best" "5x5-crack-mutating-current" "5x5-crack-randomly" "5x5-crack-xor-mutate" "<" "<=" "=" ">" ">=" "BibTeX-auto-store" "Buffer-menu--pretty-file-name" "Buffer-menu--pretty-name" "Buffer-menu--unmark" "Buffer-menu-1-window" "Buffer-menu-2-window" "Buffer-menu-backup-unmark" "Buffer-menu-beginning" "Buffer-menu-buffer" "Buffer-menu-bury" "Buffer-menu-delete" "Buffer-menu-delete-backwards" "Buffer-menu-execute" "Buffer-menu-isearch-buffers" "Buffer-menu-isearch-buffers-regexp" "Buffer-menu-mark" "Buffer-menu-marked-buffers" "Buffer-menu-mode" "Buffer-menu-mouse-select" "Buffer-menu-multi-occur" "Buffer-menu-no-header" "Buffer-menu-not-modified" "Buffer-menu-other-window" "Buffer-menu-save" ...))
           (if (memq (cdr (assoc (progn (or (and (memq ... cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list ... ivy-last))) (aref ivy-last 22)) ivy-index-functions-alist)) '(ivy-recompute-index-swiper ivy-recompute-index-swiper-async)) (progn (ivy--recompute-index name re-str cands) (setq ivy--old-cands (ivy--sort name cands))) (setq ivy--old-cands (ivy--sort name cands)) (ivy--recompute-index name re-str ivy--old-cands))
           (let* ((re-str (if (listp re) (car (car re)) re)) (matcher (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 18))) (case-fold-search (ivy--case-fold-p name)) (cands (cond (matcher (funcall matcher re candidates)) ((and ivy--old-re (stringp re) (stringp ivy--old-re) (not (string-match "\\\\" ivy--old-re)) (not (equal ivy--old-re "")) (memq (cl-search ... re) '...)) (condition-case nil (progn (cl-remove-if-not ... ivy--old-cands)) (error nil))) (t (ivy--re-filter re candidates))))) (if (memq (cdr (assoc (progn (or (and ... t) (signal ... ...)) (aref ivy-last 22)) ivy-index-functions-alist)) '(ivy-recompute-index-swiper ivy-recompute-index-swiper-async)) (progn (ivy--recompute-index name re-str cands) (setq ivy--old-cands (ivy--sort name cands))) (setq ivy--old-cands (ivy--sort name cands)) (ivy--recompute-index name re-str ivy--old-cands)) (setq ivy--old-re re) ivy--old-cands)
           (if (and ivy--old-re ivy--old-cands (equal re ivy--old-re)) ivy--old-cands (let* ((re-str (if (listp re) (car (car re)) re)) (matcher (progn (or (and (memq ... cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list ... ivy-last))) (aref ivy-last 18))) (case-fold-search (ivy--case-fold-p name)) (cands (cond (matcher (funcall matcher re candidates)) ((and ivy--old-re (stringp re) (stringp ivy--old-re) (not ...) (not ...) (memq ... ...)) (condition-case nil (progn ...) (error nil))) (t (ivy--re-filter re candidates))))) (if (memq (cdr (assoc (progn (or ... ...) (aref ivy-last 22)) ivy-index-functions-alist)) '(ivy-recompute-index-swiper ivy-recompute-index-swiper-async)) (progn (ivy--recompute-index name re-str cands) (setq ivy--old-cands (ivy--sort name cands))) (setq ivy--old-cands (ivy--sort name cands)) (ivy--recompute-index name re-str ivy--old-cands)) (setq ivy--old-re re) ivy--old-cands))
           (let ((re (funcall ivy--regex-function name))) (if (and ivy--old-re ivy--old-cands (equal re ivy--old-re)) ivy--old-cands (let* ((re-str (if (listp re) (car (car re)) re)) (matcher (progn (or (and ... t) (signal ... ...)) (aref ivy-last 18))) (case-fold-search (ivy--case-fold-p name)) (cands (cond (matcher (funcall matcher re candidates)) ((and ivy--old-re ... ... ... ... ...) (condition-case nil ... ...)) (t (ivy--re-filter re candidates))))) (if (memq (cdr (assoc (progn ... ...) ivy-index-functions-alist)) '(ivy-recompute-index-swiper ivy-recompute-index-swiper-async)) (progn (ivy--recompute-index name re-str cands) (setq ivy--old-cands (ivy--sort name cands))) (setq ivy--old-cands (ivy--sort name cands)) (ivy--recompute-index name re-str ivy--old-cands)) (setq ivy--old-re re) ivy--old-cands)))
           ivy--filter("^" ("%" "(setf seq-elt)" "*" "+" "-" "/" "/=" "1+" "1-" "1value" "2048-game" "2C-associate-buffer" "2C-command" "2C-split" "2C-two-columns" "5x5" "5x5-crack" "5x5-crack-mutating-best" "5x5-crack-mutating-current" "5x5-crack-randomly" "5x5-crack-xor-mutate" "<" "<=" "=" ">" ">=" "BibTeX-auto-store" "Buffer-menu--pretty-file-name" "Buffer-menu--pretty-name" "Buffer-menu--unmark" "Buffer-menu-1-window" "Buffer-menu-2-window" "Buffer-menu-backup-unmark" "Buffer-menu-beginning" "Buffer-menu-buffer" "Buffer-menu-bury" "Buffer-menu-delete" "Buffer-menu-delete-backwards" "Buffer-menu-execute" "Buffer-menu-isearch-buffers" "Buffer-menu-isearch-buffers-regexp" "Buffer-menu-mark" "Buffer-menu-marked-buffers" "Buffer-menu-mode" "Buffer-menu-mouse-select" "Buffer-menu-multi-occur" "Buffer-menu-no-header" "Buffer-menu-not-modified" "Buffer-menu-other-window" "Buffer-menu-save" ...))
           (setq ivy--old-cands (ivy--filter initial-input coll))
           (progn (setq ivy--old-cands coll) (setq ivy--old-cands (ivy--filter initial-input coll)))
           (if initial-input (progn (setq ivy--old-cands coll) (setq ivy--old-cands (ivy--filter initial-input coll))))
           (let (coll sort-fn) (cond ((eq collection 'Info-read-node-name-1) (if (equal Info-current-file "dir") (setq coll (mapcar #'(lambda ... ...) (cl-delete-duplicates (all-completions "(" collection predicate) :test #'equal))) (setq coll (all-completions "" collection predicate)))) ((eq collection 'read-file-name-internal) (setq ivy--directory default-directory) (if (and initial-input (not (equal initial-input ""))) (progn (cond ((file-directory-p initial-input) (if ... ...) (setq ivy--directory initial-input) (setq initial-input nil) (if preselect ...)) ((condition-case nil ... ...) (setq ivy--directory ...) (progn ... ...))))) (require 'dired) (if preselect (progn (let ((preselect-directory ...)) (if (or ... ...) nil (setq ivy--directory preselect-directory)) (progn (or ... ...) (let* ... ...))))) (setq coll (ivy--sorted-files ivy--directory)) (if initial-input (progn (if (or require-match (equal initial-input default-directory) (equal initial-input "")) nil (setq coll (cons initial-input coll))) (if (and (progn ... ...) (not ...)) nil (setq initial-input nil))))) ((eq collection 'internal-complete-buffer) (setq coll (ivy--buffer-list "" ivy-use-virtual-buffers predicate))) (dynamic-collection (setq coll (funcall collection ivy-text))) ((and (consp collection) (listp (car collection))) (if (and sort (setq sort-fn (ivy--sort-function caller))) (progn (setq sort nil) (setq coll (mapcar #'car (sort ... sort-fn)))) (setq collection (progn (or (and ... t) (signal ... ...)) (let* (...) (aset v 2 ...)))) (setq coll (all-completions "" collection))) (let ((i 0)) (condition-case nil (progn (let (...) (while --dolist-tail-- ...))) (error nil)))) ((or (functionp collection) (byte-code-function-p collection) (vectorp collection) (hash-table-p collection) (and (listp collection) (symbolp (car collection)))) (setq coll (all-completions "" collection predicate))) (t (setq coll (if predicate (cl-remove-if-not predicate collection) collection)))) (if (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 19)) nil (setq coll (delete "" coll))) (if def (progn (cond ((listp def) (setq coll (cl-union def coll :test 'equal))) ((member def coll)) (t (setq coll (cons def coll)))))) (if sort (progn (if (functionp collection) (if (and (not (eq collection ...)) (<= (length coll) ivy-sort-max-size) (setq sort-fn (ivy--sort-function collection))) (progn (setq coll (sort ... sort-fn)))) (if (and (not (eq history ...)) (<= (length coll) ivy-sort-max-size) (setq sort-fn (ivy--sort-function caller))) (progn (setq coll (sort ... sort-fn))))))) (setq coll (ivy--set-candidates coll)) (setq ivy--old-re nil) (setq ivy--old-cands nil) (if (integerp preselect) (progn (setq ivy--old-re "") (ivy-set-index preselect))) (if initial-input (progn (setq ivy--old-cands coll) (setq ivy--old-cands (ivy--filter initial-input coll)))) (setq ivy--all-candidates coll) (if (integerp preselect) nil (ivy-set-index (or (and dynamic-collection ivy--index) (and preselect (ivy--preselect-index preselect (if initial-input ivy--old-cands coll))) 0))))
           (let* ((prompt (or (progn (or (and (memq ... cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list ... state))) (aref state 1)) "")) (collection (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 2))) (predicate (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 3))) (history (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 6))) (preselect (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 7))) (sort (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 10))) (re-builder (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 17))) (dynamic-collection (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 19))) (require-match (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 4))) (caller (or (progn (or (and (memq ... cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list ... state))) (aref state 22)) this-command)) (initial-input (or (progn (or (and (memq ... cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list ... state))) (aref state 5)) (cdr (assq caller ivy-initial-inputs-alist)))) (def (progn (or (and (memq (type-of state) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state state))) (aref state 24)))) (setq ivy--directory nil) (setq ivy-case-fold-search ivy-case-fold-search-default) (setq ivy--regex-function (or re-builder (and (functionp collection) (cdr (assq collection ivy-re-builders-alist))) (and caller (cdr (assq caller ivy-re-builders-alist))) (cdr (assq t ivy-re-builders-alist)) #'ivy--regex)) (setq ivy--subexps 0) (setq ivy--regexp-quote #'regexp-quote) (setq ivy--old-text "") (setq ivy--full-length nil) (setq ivy-text "") (setq ivy--index 0) (setq ivy-calling nil) (setq ivy-use-ignore ivy-use-ignore-default) (setq ivy--highlight-function (or (cdr (assq ivy--regex-function ivy-highlight-functions-alist)) #'ivy--highlight-default)) (let (coll sort-fn) (cond ((eq collection 'Info-read-node-name-1) (if (equal Info-current-file "dir") (setq coll (mapcar #'... (cl-delete-duplicates ... :test ...))) (setq coll (all-completions "" collection predicate)))) ((eq collection 'read-file-name-internal) (setq ivy--directory default-directory) (if (and initial-input (not (equal initial-input ""))) (progn (cond (... ... ... ... ...) (... ... ...)))) (require 'dired) (if preselect (progn (let (...) (if ... nil ...) (progn ... ...)))) (setq coll (ivy--sorted-files ivy--directory)) (if initial-input (progn (if (or require-match ... ...) nil (setq coll ...)) (if (and ... ...) nil (setq initial-input nil))))) ((eq collection 'internal-complete-buffer) (setq coll (ivy--buffer-list "" ivy-use-virtual-buffers predicate))) (dynamic-collection (setq coll (funcall collection ivy-text))) ((and (consp collection) (listp (car collection))) (if (and sort (setq sort-fn (ivy--sort-function caller))) (progn (setq sort nil) (setq coll (mapcar ... ...))) (setq collection (progn (or ... ...) (let* ... ...))) (setq coll (all-completions "" collection))) (let ((i 0)) (condition-case nil (progn (let ... ...)) (error nil)))) ((or (functionp collection) (byte-code-function-p collection) (vectorp collection) (hash-table-p collection) (and (listp collection) (symbolp (car collection)))) (setq coll (all-completions "" collection predicate))) (t (setq coll (if predicate (cl-remove-if-not predicate collection) collection)))) (if (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 19)) nil (setq coll (delete "" coll))) (if def (progn (cond ((listp def) (setq coll (cl-union def coll :test ...))) ((member def coll)) (t (setq coll (cons def coll)))))) (if sort (progn (if (functionp collection) (if (and (not ...) (<= ... ivy-sort-max-size) (setq sort-fn ...)) (progn (setq coll ...))) (if (and (not ...) (<= ... ivy-sort-max-size) (setq sort-fn ...)) (progn (setq coll ...)))))) (setq coll (ivy--set-candidates coll)) (setq ivy--old-re nil) (setq ivy--old-cands nil) (if (integerp preselect) (progn (setq ivy--old-re "") (ivy-set-index preselect))) (if initial-input (progn (setq ivy--old-cands coll) (setq ivy--old-cands (ivy--filter initial-input coll)))) (setq ivy--all-candidates coll) (if (integerp preselect) nil (ivy-set-index (or (and dynamic-collection ivy--index) (and preselect (ivy--preselect-index preselect (if initial-input ivy--old-cands coll))) 0)))) (setq ivy-exit nil) (setq ivy--default (if (region-active-p) (buffer-substring (region-beginning) (region-end)) (ivy-thing-at-point))) (setq ivy--prompt (ivy-add-prompt-count prompt)) (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (let* ((v ivy-last)) (aset v 5 initial-input))))
           ivy--reset-state(#s(ivy-state :prompt "Describe function: " :collection ("enable-theme" "ansi-color-apply-overlay-face" "isearch--state-pop-fun--cmacro" "epg-context-signers" "kinsoku" "xselect--int-to-cons" "magit-submodule-update" "url-setup-privacy-info" "epg--status-VALIDSIG" "bbdb-toggle-records-layout" "dired-backup-diff" "dired-at-point" "figlet-preview-fonts" "pulse-momentary-highlight-region" "isearch-complete1" "charset-id-internal" "ivy-sort-file-function-default" "byte-compile-function-warn" "memory-use-counts" "string-make-unibyte" "digit-argument" "cl--struct-epg-signature-p" "auth-source-token-passphrase-callback-function" "%" "Info-apropos-find-file" "*" "+" "rx-trans-forms" "-" "/" "helm" "help" "url-fullness--cmacro" "w3m-replace-symbol" "set-window-new-pixel" "charset-long-name" "sexp-at-point" "minibuffer-contents-no-properties" "thread-first" "elp-instrument-function" "get-unused-category" "cl--struct-name-p" "dired-marker-regexp" "<" "=" "ivy--actionp" ">" "ido-display-file" "cl--generic-method-specializers" "cl-defmethod" ...) :predicate nil :require-match t :initial-input nil :history counsel-describe-symbol-history :preselect "" :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :update-fn nil :sort t :frame #<frame emacs@thunk 0x1422c30> :window #<window 3 on *scratch*> :buffer #<buffer *scratch*> :text nil :action (1 ("o" (closure (find-tag-marker-ring company-common company-point company-candidates t) (x) (funcall counsel-describe-function-function (intern x))) "default") ("i" (closure (bookmark-alist recentf-list avy-styles-alist avy-style avy-keys-alist avy-keys avy-action avy-all-windows Info-current-file cl-struct-ivy-state-tags t) (x) (insert (if (stringp x) x (car x)))) "insert") ("w" (closure (bookmark-alist recentf-list avy-styles-alist avy-style avy-keys-alist avy-keys avy-action avy-all-windows Info-current-file cl-struct-ivy-state-tags t) (x) (kill-new (if (stringp x) x (car x)))) "copy") ("I" counsel-info-lookup-symbol "info") ("d" counsel--find-symbol "definition")) :unwind nil :re-builder nil :matcher nil :dynamic-collection nil :display-transformer-fn counsel-describe-function-transformer :directory "~/.emacs.d/src/swiper/" :caller counsel-describe-function :current nil :def nil))
           (let ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (transformer-fn (plist-get ivy--display-transformers-list (cond (caller) ((functionp collection) collection)))) (ivy-display-function (if (window-minibuffer-p) nil (or ivy-display-function (cdr (or (assq caller ivy-display-functions-alist) (assq t ivy-display-functions-alist)))))) (height (or (cdr (assq caller ivy-height-alist)) ivy-height))) (setq ivy-last (record 'ivy-state prompt collection predicate require-match initial-input history preselect keymap update-fn sort (selected-frame) (selected-window) (current-buffer) nil action unwind re-builder matcher dynamic-collection transformer-fn default-directory caller nil def)) (ivy--reset-state ivy-last) (prog1 (unwind-protect (let ((fun #'ivy--minibuffer-setup) setup-hook) (setq setup-hook #'(lambda nil (remove-hook ... setup-hook) (funcall fun))) (unwind-protect (progn (add-hook 'minibuffer-setup-hook setup-hook) (let* (... ... ... ... ...) (if ... ... ...) (if ... ...) (progn ... ...))) (remove-hook 'minibuffer-setup-hook setup-hook))) (remove-hook 'post-command-hook #'ivy--queue-exhibit) (let ((cleanup (ivy--display-function-prop :cleanup))) (if (functionp cleanup) (progn (funcall cleanup)))) (if (setq unwind (progn (or (and ... t) (signal ... ...)) (aref ivy-last 16))) (progn (funcall unwind))) (if (eq ivy-exit 'done) nil (ivy-recursive-restore))) (ivy-call) (if (> (length (progn (or (and ... t) (signal ... ...)) (aref ivy-last 23))) 0) (progn (remove-list-of-text-properties 0 1 '(idx) (progn (or (and ... t) (signal ... ...)) (aref ivy-last 23)))))))
           (progn (let ((extra-actions (delete-dups (append (plist-get ivy--actions-list t) (plist-get ivy--actions-list this-command) (plist-get ivy--actions-list caller))))) (if extra-actions (progn (setq action (cond ((functionp action) (cons 1 ...)) ((null action) (cons 1 ...)) (t (delete-dups ...))))))) (if caller nil (setq caller this-command)) (let ((extra-sources (plist-get ivy--sources-list caller))) (if extra-sources (progn (setq ivy--extra-candidates nil) (let ((--dolist-tail-- extra-sources)) (while --dolist-tail-- (let (...) (cond ... ...) (setq --dolist-tail-- ...))))) (setq ivy--extra-candidates '((original-source))))) (let ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (transformer-fn (plist-get ivy--display-transformers-list (cond (caller) ((functionp collection) collection)))) (ivy-display-function (if (window-minibuffer-p) nil (or ivy-display-function (cdr (or ... ...))))) (height (or (cdr (assq caller ivy-height-alist)) ivy-height))) (setq ivy-last (record 'ivy-state prompt collection predicate require-match initial-input history preselect keymap update-fn sort (selected-frame) (selected-window) (current-buffer) nil action unwind re-builder matcher dynamic-collection transformer-fn default-directory caller nil def)) (ivy--reset-state ivy-last) (prog1 (unwind-protect (let ((fun #'ivy--minibuffer-setup) setup-hook) (setq setup-hook #'(lambda nil ... ...)) (unwind-protect (progn (add-hook ... setup-hook) (let* ... ... ... ...)) (remove-hook 'minibuffer-setup-hook setup-hook))) (remove-hook 'post-command-hook #'ivy--queue-exhibit) (let ((cleanup (ivy--display-function-prop :cleanup))) (if (functionp cleanup) (progn (funcall cleanup)))) (if (setq unwind (progn (or ... ...) (aref ivy-last 16))) (progn (funcall unwind))) (if (eq ivy-exit 'done) nil (ivy-recursive-restore))) (ivy-call) (if (> (length (progn (or ... ...) (aref ivy-last 23))) 0) (progn (remove-list-of-text-properties 0 1 '(idx) (progn (or ... ...) (aref ivy-last 23))))))))
           (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller)" (car --cl-keys--)))))) (progn (let ((extra-actions (delete-dups (append (plist-get ivy--actions-list t) (plist-get ivy--actions-list this-command) (plist-get ivy--actions-list caller))))) (if extra-actions (progn (setq action (cond (... ...) (... ...) (t ...)))))) (if caller nil (setq caller this-command)) (let ((extra-sources (plist-get ivy--sources-list caller))) (if extra-sources (progn (setq ivy--extra-candidates nil) (let ((--dolist-tail-- extra-sources)) (while --dolist-tail-- (let ... ... ...)))) (setq ivy--extra-candidates '((original-source))))) (let ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (transformer-fn (plist-get ivy--display-transformers-list (cond (caller) (... collection)))) (ivy-display-function (if (window-minibuffer-p) nil (or ivy-display-function (cdr ...)))) (height (or (cdr (assq caller ivy-height-alist)) ivy-height))) (setq ivy-last (record 'ivy-state prompt collection predicate require-match initial-input history preselect keymap update-fn sort (selected-frame) (selected-window) (current-buffer) nil action unwind re-builder matcher dynamic-collection transformer-fn default-directory caller nil def)) (ivy--reset-state ivy-last) (prog1 (unwind-protect (let ((fun ...) setup-hook) (setq setup-hook #'...) (unwind-protect (progn ... ...) (remove-hook ... setup-hook))) (remove-hook 'post-command-hook #'ivy--queue-exhibit) (let ((cleanup ...)) (if (functionp cleanup) (progn ...))) (if (setq unwind (progn ... ...)) (progn (funcall unwind))) (if (eq ivy-exit 'done) nil (ivy-recursive-restore))) (ivy-call) (if (> (length (progn ... ...)) 0) (progn (remove-list-of-text-properties 0 1 '... (progn ... ...))))))))
           (let* ((predicate (car (cdr (plist-member --cl-rest-- ':predicate)))) (require-match (car (cdr (plist-member --cl-rest-- ':require-match)))) (initial-input (car (cdr (plist-member --cl-rest-- ':initial-input)))) (history (car (cdr (plist-member --cl-rest-- ':history)))) (preselect (car (cdr (plist-member --cl-rest-- ':preselect)))) (def (car (cdr (plist-member --cl-rest-- ':def)))) (keymap (car (cdr (plist-member --cl-rest-- ':keymap)))) (update-fn (car (cdr (plist-member --cl-rest-- ':update-fn)))) (sort (car (cdr (plist-member --cl-rest-- ':sort)))) (action (car (cdr (plist-member --cl-rest-- ':action)))) (unwind (car (cdr (plist-member --cl-rest-- ':unwind)))) (re-builder (car (cdr (plist-member --cl-rest-- ':re-builder)))) (matcher (car (cdr (plist-member --cl-rest-- ':matcher)))) (dynamic-collection (car (cdr (plist-member --cl-rest-- ':dynamic-collection)))) (caller (car (cdr (plist-member --cl-rest-- ':caller))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :unwind :re-builder :matcher :dynamic-collection :caller)" (car --cl-keys--)))))) (progn (let ((extra-actions (delete-dups (append ... ... ...)))) (if extra-actions (progn (setq action (cond ... ... ...))))) (if caller nil (setq caller this-command)) (let ((extra-sources (plist-get ivy--sources-list caller))) (if extra-sources (progn (setq ivy--extra-candidates nil) (let (...) (while --dolist-tail-- ...))) (setq ivy--extra-candidates '(...)))) (let ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (transformer-fn (plist-get ivy--display-transformers-list (cond ... ...))) (ivy-display-function (if (window-minibuffer-p) nil (or ivy-display-function ...))) (height (or (cdr ...) ivy-height))) (setq ivy-last (record 'ivy-state prompt collection predicate require-match initial-input history preselect keymap update-fn sort (selected-frame) (selected-window) (current-buffer) nil action unwind re-builder matcher dynamic-collection transformer-fn default-directory caller nil def)) (ivy--reset-state ivy-last) (prog1 (unwind-protect (let (... setup-hook) (setq setup-hook ...) (unwind-protect ... ...)) (remove-hook 'post-command-hook #'ivy--queue-exhibit) (let (...) (if ... ...)) (if (setq unwind ...) (progn ...)) (if (eq ivy-exit ...) nil (ivy-recursive-restore))) (ivy-call) (if (> (length ...) 0) (progn (remove-list-of-text-properties 0 1 ... ...))))))))
           ivy-read("Describe function: " ("enable-theme" "ansi-color-apply-overlay-face" "isearch--state-pop-fun--cmacro" "epg-context-signers" "kinsoku" "xselect--int-to-cons" "magit-submodule-update" "url-setup-privacy-info" "epg--status-VALIDSIG" "bbdb-toggle-records-layout" "dired-backup-diff" "dired-at-point" "figlet-preview-fonts" "pulse-momentary-highlight-region" "isearch-complete1" "charset-id-internal" "ivy-sort-file-function-default" "byte-compile-function-warn" "memory-use-counts" "string-make-unibyte" "digit-argument" "cl--struct-epg-signature-p" "auth-source-token-passphrase-callback-function" "%" "Info-apropos-find-file" "*" "+" "rx-trans-forms" "-" "/" "helm" "help" "url-fullness--cmacro" "w3m-replace-symbol" "set-window-new-pixel" "charset-long-name" "sexp-at-point" "minibuffer-contents-no-properties" "thread-first" "elp-instrument-function" "get-unused-category" "cl--struct-name-p" "dired-marker-regexp" "<" "=" "ivy--actionp" ">" "ido-display-file" "cl--generic-method-specializers" "cl-defmethod" ...) :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :preselect "" :history counsel-describe-symbol-history :require-match t :sort t :action (closure (find-tag-marker-ring company-common company-point company-candidates t) (x) (funcall counsel-describe-function-function (intern x))) :caller counsel-describe-function)
           (let ((enable-recursive-minibuffers t)) (ivy-read "Describe function: " (let (cands) (mapatoms #'(lambda (x) (if (fboundp x) (progn ...)))) cands) :keymap counsel-describe-map :preselect (funcall counsel-describe-function-preselect) :history 'counsel-describe-symbol-history :require-match t :sort t :action #'(lambda (x) (funcall counsel-describe-function-function (intern x))) :caller 'counsel-describe-function))
           counsel-describe-function()
           funcall-interactively(counsel-describe-function)
           call-interactively(counsel-describe-function nil nil)
           command-execute(counsel-describe-function)

**Comment by seagle0128** [comment] 2018-07-04 10:15
Sure . The PR https://github.com/abo-abo/swiper/pull/1649 has been submitted.

**Comment by raxod502** [comment] 2018-07-04 15:58
Well this is a little embarrassing. Frankly I'm not sure how I didn't run into this myself, since I've been running a version of Swiper that includes https://github.com/abo-abo/swiper/pull/1573 for a month and a half.

**Comment by abo-abo** [comment] 2018-07-05 15:03
Merged, thanks all.

**Closed** 2018-07-05 15:03 UTC
