### ISSUE TITLE
[Feature requests]Add virtual initial input features

### ISSUE THREAD

**Issue by cireu** [abo-abo/swiper#1874] opened 2018-12-25 13:58 UTC
Sometimes we can find the input boxes of some website have a virtual initial input (most of time they're some ads :) ) If you think that "oh it's interesting" .You just need to press enter it will take you go. If you have no interest about it, you just simply type what you want, and these virtual initial input will be cleared.

I think it's useful for daily use. For example, we can ask counsel-ag based command get the symbol at point as a virtual initial-input. If users think "Ah that's really what I want" they can use C-n C-p to navigate between results, if they don't, they type theirs own, or they can use TAB key to make virtual initial-input become real inputs then modifiy them. Just like fish shell completion.

Is it possible to implement this features?

**Comment by Alexander-Shukaev** [comment] 2018-12-25 14:11
Looks like a duplicate of #1867 or at least could be consolidated there.

**Closed** 2018-12-26 00:16 UTC
