### ISSUE TITLE
Issues with symbolic links in find-file

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#1134] opened 2017-08-02 07:15 UTC
Symbolic links are being opened in `fundamental-mode` when they are opened using `counsel-fild-file`  or `find-file`. Also, I see that the font lock applied to symbolic links are that of directories. It used to work fine a week ago. 

I'm running emacs master build on MacOS Sierra.

**Comment by dom-verity** [comment] 2018-01-27 23:40
This issue is also happening for me.

Installation details:

OS: Mac OS X 10.12.6
Emacs: v 26.0.91 binary Emacs-pretest-26.0.91-1-universal.dmg from https://emacsformacosx.com/, but same behaviour observed on all locally compiled v26 emacs.
Configuration: Spacemacs v0.200.13 with ivy layer. (but have observed same behaviour with my own hand rolled .emacs.d/init.el).

Symptom:

The following screenshot 

<img width="659" alt="screen shot 2018-01-28 at 10 29 41 am" src="https://user-images.githubusercontent.com/369729/35477448-bbb3c5e4-0416-11e8-9f46-99fc6e99e392.png">

shows a section of listing of my home directory produced by counsel-find-file. The files .zshenv and .zshrc are links to files stored in my cofiguration files repository, but they are showing here as directories. Selecting one of these doesn't load the linked file, instead it creates a new file.

This behaviour is not observed when I use Emacs 25.3 with the same OS / configuration.

**Comment by abo-abo** [comment] 2018-01-28 15:31
Sorry, can't reproduce on GNU/Linux.
@CSRaghunandan Maybe you could try `git bisect`, if it was working before?

**Comment by ynilu** [comment] 2018-04-23 16:13
It seems to be a bug in emacs
https://lists.gnu.org/archive/html/emacs-bug-tracker/2017-11/msg00180.html

**Comment by basil-conto** [comment] 2018-04-23 16:32
@ynilu The full discussion is better viewed at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29231.

**Comment by abo-abo** [comment] 2018-04-23 16:33
@dom-verity Could you please verify if the bug is reproducible with the current Emacs-26 release candidate?

**Comment by basil-conto** [comment] 2018-05-30 22:19
This issue may be a duplicate of #1239.

**Comment by basil-conto** [comment] 2018-08-09 12:50
Emacs 26 has been out for over two months, can we close this presumed duplicate of #1239 until further notice?

**Comment by basil-conto** [comment] 2018-11-21 01:10
Can this issue be closed?

**Comment by abo-abo** [comment] 2018-11-21 15:12
Closing assuming this is fixed. Please report if there's still an issue.

**Closed by abo-abo** 2018-11-21 15:12 UTC
