### ISSUE TITLE
counsel-descbinds-function fo Helpful integration

### ISSUE THREAD

**Issue by ema2159** [abo-abo/swiper#2091] opened 2019-06-08 16:22 UTC
I noticed that there exist a `counsel-describe-function-function` and a `counsel-describe-variable-function` so I'm able to call Helpful using counsel like doing for example `(setq counsel-describe-function-function #'helpful-callable)` and that's awesome, however, there's no `counsel-descbinds-function`, so I'm unable to call Helpful from counsel when describing a key. 
Could this feature be implemented in a near future?

**Comment by Alexander-Shukaev** [comment] 2019-06-08 18:56
Duplicate of #1876 (it's not a big deal to implement by the way, PR is always welcome).

**Comment by abo-abo** [comment] 2019-06-24 14:45
Added, thanks.

**Closed** 2019-06-24 14:44 UTC

**Comment by ema2159** [comment] 2019-06-24 14:52
Awesome man, thanks!
