### ISSUE TITLE
virtual-buffers: can't read recentf-list without bookmark

### ISSUE THREAD

**Issue by ShuguangSun** [abo-abo/swiper#1033] opened 2017-05-26 16:01 UTC
If ivy-use-virtual-buffers is true and the bookmark is not loaded, the ivy-switch-buffer will not read recenf-list. It seems the ivy--virtual-buffers function read recentf-list and bookmark-alist at the same time which requires the bookmark is loaded first.

Could we make it in separate steps? Then it can read recentf-list no matter whether bookmark is loaded?

**Comment by abo-abo** [comment] 2017-05-26 17:32
> Could we make it in separate steps?

It is already separate steps, looking at the code. I can't reproduce your issue with `make plain`: `recentf-list` works even if `bookmark-alist` isn't defined.

**Comment by ShuguangSun** [comment] 2017-05-30 16:38
Sorry. It is my mistake. I auto-loaded the set of ivy-use-virtual-buffers  to t after the bookmark relevant comand. So you are right: recentf-list works even if bookmark-alist isn't defined.

**Comment by abo-abo** [comment] 2017-05-30 19:12
OK, closing.

**Closed by abo-abo** 2017-05-30 19:12 UTC
