### ISSUE TITLE
Question: ivy and auto-insert 

### ISSUE THREAD

**Issue by mambolevis** [abo-abo/swiper#1475] opened 2018-02-24 12:21 UTC
Hi,

When I use `auto-insert` and `ivy `is active, auto insert can no finish the insertion process. Let me explain that using to examples:

**1. Using auto-insert without ivy:**
- auto insert ask in the minibuffer for a `short description`: short description
- auto insert ask in the minibuffer for `Keyword, C-h`: Temp key
The auto insertion is finished as expected 

```
;;; settings.el --- short description                -*- lexical-binding: t; -*-

;; Copyright (C) 2018  Mambo Levis

;; Author: Mambo Levis 
;; Keywords: Tempo Key

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;;

;;; Code:



(provide 'settings)
;;; settings.el ends here
```

**2. Using auto-insert with ivy:**
- auto insert ask in the minibuffer for a `short description`: short description
- auto insert ask in the minibuffer for `Keyword, C-h`:     `(here is no possible to continue)`
Here the auto insertion can't finish due to the ivy interference.

```
;;; settings.el --- short description                -*- lexical-binding: t; -*-

;; Copyright (C) 2018  Mambo Levis

;; Author: Mambo Levis 
;; Keywords: Tempo Key
```

Question:
Is there a parameter that I can add to the configuration of auto-insert in order to stop temporarily ivy completion?

```
(use-package auto-insert
  :bind (("<f5> a" . auto-insert)))
```
Thanks

**Comment by basil-conto** [comment] 2018-02-24 13:08
> Here the auto insertion can't finish due to the ivy interference.

Can you please clarify what this means? Are no candidates shown? What keys do you press? Do you want to complete only a single keyword or multiple ones?

FWIW, the following:

https://github.com/emacs-mirror/emacs/blob/8a23dc15077c6bbe3d80ccfcef64397e71f5765d/lisp/autoinsert.el#L181-L189

seems to work for me with Ivy, but I don't use `auto-insert`, so I don't know what exactly to expect.

**Comment by mambolevis** [comment] 2018-02-24 13:31
@basil-conto 
Thanks. Basically what I need is that ivy doesn't present any candidates during the execution on auto-insert. 

The only thing auto-insert does is the creation of a template with the standar information that is used in a *.el file (see example 1). The point is that auto-insert interacts with the user in the minibuffer by asking for a `short description` and for a `Keywords`  (both options are just strings, nothing special) 

Auto insert belongs to emacs, so can easily use the following configuration to see the problem. **`Please do not forget to create an empty *.el buffer before running auto-insert.`**
```
(use-package auto-insert
  :bind (("<f5> a" . auto-insert)))
```

**Comment by mambolevis** [comment] 2018-02-24 15:44
Please follow this two print screens:
After running `"<f5> a" `, auto-insert stars asking for a `Short description`:

![image](https://user-images.githubusercontent.com/13024208/36632002-e51cdb6c-1980-11e8-8659-dc0afc4eaa17.png)

Then auto-insert asks for` Keyword, C-h:` 
![image](https://user-images.githubusercontent.com/13024208/36632048-564c01aa-1981-11e8-971b-62ab306428cc.png)

As you see, auto-insert can not continue generating the desired template for `test.el` file used in this example.

**Comment by basil-conto** [comment] 2018-02-24 16:17
I tried <kbd>M-x</kbd>`auto-insert`<kbd>RET</kbd> in an empty `emacs-lisp-mode` buffer (no need for the keybinding via `use-package`), and it works fine for me.

What I assume you mean with

> auto-insert can not continue generating the desired template

is that `auto-insert` enters a completion loop, i.e. after selecting one keyword it prompts the user again for a second, and third, etc. This loop exits when the user enters the empty string, which Ivy allows you to do via <kbd>C-M-j</kbd> (`ivy-immediate-done`). See the [relevant manual node](http://oremacs.com/swiper/#key-bindings-for-single-selection-action-then-exit-minibuffer) and [FAQ](https://github.com/abo-abo/swiper/wiki/FAQ#how-to-select-the-current-input-instead-of-the-current-candidate).

Having said that, I think `autoinsert` is abusing `completing-read` for this use-case. The preferred way to prompt the user for multiple candidates with completion is the function `completing-read-multiple`. You may want to consider filing this as a bug with Emacs via <kbd>M-x</kbd>`report-emacs-bug`<kbd>RET</kbd>.

**Comment by basil-conto** [comment] 2018-02-24 20:11
> The question now is why it works in your configuration?

I also have to type <kbd>C-M-j</kbd> if that's what you're referring to (I can't be sure because you haven't given a clear definition of "it doesn't work", i.e. precisely what you expect, what you type, and what the result is). That's just how `autoinsert` is programmed, and how the Ivy interface works. My previous point was that `autoinsert` can and should be programmed better by using `completing-read-multiple` rather than `completing-read` for reading multiple keywords with completion.

**Comment by basil-conto** [comment] 2018-02-24 23:19
> To understand better the behaviour of `auto-insert` it is necessary to turn `ivy-mode` off before `M-x auto-insert`

What do you mean? I can see in its source that it is calling `completing-read`, which is why...

>  In my previous configuration with ido, I did not have this issue with auto-insert.

you didn't notice different behaviour with Ido. You see, Ido doesn't override `completing-read-function` like `ivy-mode` does. But at the same time, Ivy is designed to work with functions which depend on `completing-read` returning an empty string by way of <kbd>C-M-j</kbd>, as you have seen.

In some situations, you can customise `ivy-completing-read-handlers-alist` in order to revert to the usual `completing-read-default` behaviour without first disabling `ivy-mode`, but I don't think this is possible given the way that `auto-insert` is programmed. Perhaps @abo-abo can shine some light on this.

> For that reason, I don't think it is a bug in emacs.

I wouldn't call it a bug, so much as room for improvement.

**Comment by abo-abo** [comment] 2018-02-25 15:53
> I don't see much Ivy can do, as the behaviour you are witnessing is intentional.

> I wouldn't call it a bug, so much as room for improvement.

Thanks for the comments, I agree with both. Closing this issue as not a bug.

Summary of solution alternatives:

- <kbd>C-M-j</kbd> to return the input text
- see also `ivy-use-selectable-prompt` for an option similar to <kbd>C-M-j</kbd> (i.e. you use <kbd>C-p C-m</kbd> instead).
- see `ivy-completing-read-handlers-alist` for more intricate cases (doesn't work perfectly, since it dispatches on `this-command`, which is not always reliable)

**Closed by abo-abo** 2018-02-25 15:53 UTC
