### ISSUE TITLE
C-M-m(ivy-call) not work in terminal

### ISSUE THREAD

**Issue by spavlovich001** [abo-abo/swiper#2880] opened 2021-05-28 22:16 UTC
Subj. Test in simple terminal(st) & xterm

**Comment by basil-conto** [comment] 2021-06-02 13:56
Confirmed, but what would you have Ivy do about that?

Sounds like a terminal and Emacs setup issue to me.  E.g. you can always change the default bindings to whatever works for you.

**Comment by spavlovich001** [comment] 2021-06-02 14:45
There should be uniformity in everything. Why bind functionality to those keys that do not work in the terminal?

**Comment by spavlovich001** [comment] 2021-06-02 14:45
> Confirmed, but what would you have Ivy do about that?
> 
> Sounds like a terminal and Emacs setup issue to me. E.g. you can always change the default bindings to whatever works for you.



Confirmed, but what would you have Ivy do about that?

Sounds like a terminal and Emacs setup issue to me. E.g. you can always change the default bindings to whatever works for you.

**Comment by spavlovich001** [comment] 2021-06-02 14:45
> Confirmed, but what would you have Ivy do about that?
> 
> Sounds like a terminal and Emacs setup issue to me. E.g. you can always change the default bindings to whatever works for you.

There should be uniformity in everything. Why bind functionality to those keys that do not work in the terminal?

**Comment by basil-conto** [comment] 2021-06-02 14:57
> There should be uniformity in everything.

Sorry, but that's not a realistic expectation.

> Why bind functionality to those keys that do not work in the terminal?

They work fine in GNOME Terminal, FWIW.  And Ivy's not alone: Org also makes heavy use of key bindings that don't work in all terminals.

Package authors don't always consider every possible permutation in the wild when making a choice about default key bindings, and that's a good thing.  We can't change the defaults now because that would be backward incompatible.  Luckily these things are rarely a problem in Emacs since the user has many ways to tweak things on their end.

So unless you have some concrete and backward-compatible proposal for what Ivy could do differently here, I think this issue can be closed as "won't fix".

Thanks.

**Closed** 2021-06-02 17:57 UTC
Labels: wontfix, support
