### ISSUE TITLE
ivy + org-mode refile does not display subtasks

### ISSUE THREAD

**Issue by cfuhrman** [abo-abo/swiper#444] opened 2016-03-18 18:08 UTC
When an org-mode user attempts to refile a task to another file, counsel does not display sub-headings when given a selection list as so:

![screen shot 2016-03-18 at 10 58 05 am](https://cloud.githubusercontent.com/assets/379171/13887383/a43ad3da-ecf8-11e5-8a69-4af2225a7502.png)

Notice that the selection list does not include the task titles when displaying options.  This makes it confusing for the user to understand what task to file things under.  Ideally, the counsel list would display items like this:

- Tasks/ (tasks.org)
- Tasks/Reverse the polarity of the neutron flow (tasks.org)
- Tasks/Frobnicate the foomatic machine (tasks.org)
...

I have also observed similar behavior using magit and listing stashes.

I bumped up org-max-depth and this didn't seem to have an effect.  Let me know if:

- You need a screen shot of the magit behavior
- This can be addressed through some other settings
- There is a mailing list for me to post similar issues in the future
- Configuration settings that I'm using for both org-mode and ivy/counsel/swiper

**Comment by abo-abo** [comment] 2016-03-18 18:56
Can't reproduce, works fine for me.

Please try to reproduce with `emacs -Q -l ivy.el`, and provide a simple Org file for which the bug happens.

Seems like you have a custom config, since normally the targets are displayed "Tasks (tasks.org)", not "Tasks / (tasks.org)".

**Comment by cfuhrman** [comment] 2016-03-19 02:29
I can reproduce using the following emacs config file (~/.emacs.d/init.el or ~/.emacs)

[.emacs](https://github.com/abo-abo/swiper/files/180604/init.txt)

Here's refile.org:

[refile.org](https://github.com/abo-abo/swiper/files/180607/refile.txt)

And here's tasks.org

[tasks.org](https://github.com/abo-abo/swiper/files/180606/tasks.txt)

And here's a screenshot:

<img width="1328" alt="screen shot 2016-03-18 at 7 25 40 pm" src="https://cloud.githubusercontent.com/assets/379171/13896132/45a65870-ed3f-11e5-964b-73b274309fa9.png">

Since github doesn't accept .org files or .el files as attachments, I've renamed them to *.txt.

Let me know if you need any additional information.

**Comment by cfuhrman** [comment] 2016-03-21 17:28
Any update?

**Comment by cfuhrman** [comment] 2016-03-23 16:17
If it helps, I'm using the version of org-mode as shipped with Emacs 24.5.1

**Comment by abo-abo** [comment] 2016-03-23 16:54
> '(org-refile-use-outline-path t)

That's your problem there. Just keep it to `nil`, the default value and everything should be fine.

And fixing it for `t` is out of scope of Ivy, it's strictly an Org-mode issue.

**Closed by abo-abo** 2016-03-23 16:54 UTC

**Comment by cfuhrman** [comment] 2016-03-23 17:36
That worked like a charm!  Thanks!

On Wed, 23 Mar 2016 at 9:54am, Oleh Krehel wrote:

> > '(org-refile-use-outline-path t)
>
> That's your problem there. Just keep it to `nil`, the default value and everything should be fine.
>
> And fixing it for `t` is out of scope of Ivy, it's strictly an Org-mode issue.
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/abo-abo/swiper/issues/444#issuecomment-200439215

-- 
Christopher M. Fuhrman
cfuhrman@panix.com

**Comment by z3t0** [comment] 2017-07-20 02:18
@vicek thanks so much!

**Comment by slumos** [comment] 2017-11-16 00:58
@vicek omg thank you!

**Comment by dmaniloff** [comment] 2023-11-29 16:57
> I can reproduce using the following emacs config file (~/.emacs.d/init.el or ~/.emacs)
> 
> [.emacs](https://github.com/abo-abo/swiper/files/180604/init.txt)
> 
> Here's refile.org:
> 
> [refile.org](https://github.com/abo-abo/swiper/files/180607/refile.txt)
> 
> And here's tasks.org
> 
> [tasks.org](https://github.com/abo-abo/swiper/files/180606/tasks.txt)
> 
> For the org files, you will need to create a directory "~/orgtest" and place them in there (after renaming them from *.txt to *.org)
> 
> And here's a screenshot:
> 
> <img alt="screen shot 2016-03-18 at 7 25 40 pm" width="1328" src="https://cloud.githubusercontent.com/assets/379171/13896132/45a65870-ed3f-11e5-964b-73b274309fa9.png">
> 
> Since github doesn't accept .org files or .el files as attachments, I've renamed them to *.txt.
> 
> Let me know if you need any additional information.

I noticed in your screenshot that there's a leading `^` that is pre-filled in the minibuffer. I am also seeing the same and I find that I need to backspace every time to delete it before searching for my refile target. Why is that `^` showing up, and how do I get rid of it?

**Comment by cfuhrman** [comment] 2023-12-01 17:38
Good day,

See answer inlined below:

On Wed, 29 Nov 2023 at 8:57am, Diego Maniloff wrote:

> > I can reproduce using the following emacs config file (~/.emacs.d/init.el or ~/.emacs)
> >
> > [.emacs](https://github.com/abo-abo/swiper/files/180604/init.txt)
> >
> > Here's refile.org:
> >
> > [refile.org](https://github.com/abo-abo/swiper/files/180607/refile.txt)
> >
> > And here's tasks.org
> >
> > [tasks.org](https://github.com/abo-abo/swiper/files/180606/tasks.txt)
> >
> > For the org files, you will need to create a directory "~/orgtest" and place them in there (after renaming them from *.txt to *.org)
> >
> > And here's a screenshot:
> >
> > <img alt="screen shot 2016-03-18 at 7 25 40 pm" width="1328" src="https://cloud.githubusercontent.com/assets/379171/13896132/45a65870-ed3f-11e5-964b-73b274309fa9.png">
> >
> > Since github doesn't accept .org files or .el files as attachments, I've renamed them to *.txt.
> >
> > Let me know if you need any additional information.
>
> I noticed in your screenshot that there's a leading `^` that is
> pre-filled in the minibuffer. I am also seeing the same and I find that
> I need to backspace every time to delete it before searching for my
> refile target. Why is that `^` showing up, and how do I get rid of it?

One of the awesome things about Ivy is that you can use regular
expressions[1] to search for items in a list.  For instance, say ivy gives you a
list of files and you only want to see the ones with a .org extension.  So, to
do this, you'd type in:

 *.org$

This tells ivy to search for any filename listed that ends with .org  (The '*'
is a wildcard matching 0 or more characters and the '$' indicates end-of-line).

In the above context, '^' indicates the _beginning_ of the line.  So, let's say
you wanted only those fields that start with 'a'.  In this case, you'd search
for

 ^a

to get the desired list.

Unfortunately, I don't know off the top of my head how to remove showing the '^'
as a default.   I'd consult the group settings for ivy/swiper/counsel to see if
there's a variable to control that.

HTH ...


Footnotes:
[1]  https://coderpad.io/blog/development/the-complete-guide-to-regular-expressions-regex/

-- 
Christopher M. Fuhrman
***@***.***

**Comment by basil-conto** [comment] 2023-12-18 09:27
>> I noticed in your screenshot that there's a leading `^` that is pre-filled in the minibuffer. I am also seeing the same and I find that I need to backspace every time to delete it before searching for my refile target. Why is that `^` showing up, and how do I get rid of it?

> Unfortunately, I don't know off the top of my head how to remove showing the '^' as a default. I'd consult the group settings for ivy/swiper/counsel to see if there's a variable to control that.

This can be controlled by the user options `ivy-initial-inputs-alist` (older) and `ivy-hooks-alist` (newer).

Note that `ivy-initial-inputs-alist` is (regrettably) modified when some libraries (e.g. `counsel.el`) are loaded, so don't be surprised if the value of the user option does not match its initial default value.

---

> say ivy gives you a list of files and you only want to see the ones with a .org extension. So, to do this, you'd type in:
> ```
> *.org$
> ```
> This tells ivy to search for any filename listed that ends with .org (The '*' is a wildcard matching 0 or more characters and the '$' indicates end-of-line).

Not entirely: in (Elisp) regexp syntax:
- `*` is an operator which repeats its preceding construct zero or more times, so it should always follow some other text and not appear at the start of a regexp
- `.` matches any character except a newline
- `$` matches the end of a line (not the end of the input), which means it would not match filenames containing newline characters.

So the best Elisp regexp that matches filenames ending in `.org` is:
```
\.org\'
```
or, in string syntax:
```el
"\\.org\\'"
```

Of course in many interactive cases,
```
\.org$
```
would also be fine.  The main idea is that `.` is a special character, and it is better to omit the leading `*`.

Contrast this with [glob pattern](https://en.wikipedia.org/wiki/Glob_(programming)) syntax (as used by e.g. `find-file`) which would instead be:
```
*.org
```

**Comment by dmaniloff** [comment] 2023-12-18 18:24
> This can be controlled by the user options `ivy-initial-inputs-alist` (older) and `ivy-hooks-alist` (newer).

Thank you for your answer. `ivy-initial-inputs-alist` is what I was looking for.
