### ISSUE TITLE
Mode line graphical glitch after shrinking minibuffer

### ISSUE THREAD

**Issue by ChoppinBlockParty** [abo-abo/swiper#1785] opened 2018-10-15 11:43 UTC
The issue happens when I call any Ivy command that expands minibuffer and then shrinks it. This results in a graphical glitch that does not redraw the area where the mode line was. To remove this problem I have to move cursor over all the columns where the mode line was or open/close minibuffer again with any Ivy command, basically do anything that will force emacs to redraw the area.

![selection_001](https://user-images.githubusercontent.com/28957323/46948879-c9ced700-d07f-11e8-84e3-e4e8e2d2c337.jpg)

On this picture, the "second upper mode line" (it is not really a mode line, it is just a rendering artifact) is the glitch. As you can see it appeared only in one window, no glitch on the left window.

I do not think that is it is specifically Ivy issue. There could be anything Linux, X windows, Emacs core, X toolkit, etc.
I just post it here in a hope that someone can give me some hints on what the may be the reason.
I have compiled emacs 26.1 with following X toolkits: Lucid/Athena, Gtk3, Motif. In all of them I have observed the same glitch.

Emacs version: 26.1
Operating System: Ubuntu 16.04
Graphical/Terminal: X

**Comment by basil-conto** [comment] 2018-10-15 12:35
Can you reproduce from `emacs -Q`?

**Comment by ChoppinBlockParty** [comment] 2018-10-15 12:49
@basil-conto I actually do not know how to do that without Ivy being loaded.

**Comment by basil-conto** [comment] 2018-10-15 13:35
@ChoppinBlockParty See [`(emacs) Lisp Libraries`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Libraries.html).

**Comment by ChoppinBlockParty** [comment] 2018-10-15 14:13
Thank you. No, I cannot reproduce.

**Comment by basil-conto** [comment] 2018-10-15 15:43
That means that your configuration and/or some package other than Ivy is somehow giving rise to this behaviour. Do you use a batteries-included configuration such as Doom Emacs? Can you try to bisect your configuration to see which part of it gives rise to the minibuffer issue?

**Comment by ChoppinBlockParty** [comment] 2018-10-16 18:32
> Do you use a batteries-included configuration such as Doom Emacs? 

No I dont have.

> Can you try to bisect your configuration to see which part of it gives rise to the minibuffer issue?

Yes, that is what I should do probably.

Thank you.

**Comment by basil-conto** [comment] 2018-10-16 18:46
Thanks. I mentioned Doom Emacs as an example because there was a discussion on emacs-devel not too long ago about some custom hook/advice that Doom was using which related to the window configuration, IIRC.

**Comment by ChoppinBlockParty** [comment] 2018-10-16 20:15
I have done a lot of testing, and I am 99% sure that this is powerline + all-the-icons. Any ideas?

**Comment by basil-conto** [comment] 2018-10-16 22:56
My only idea would be to bring up the issue with those packages and/or <kbd>M-x</kbd>`report-emacs-bug`<kbd>RET</kbd>, depending on reproducibility and underlying cause.

**Comment by wyuenho** [comment] 2019-02-18 19:12
Emacs on X has always had redrawing issues until very recently. Either try compiling from master or report this upstream.

**Comment by Alexander-Shukaev** [comment] 2019-02-22 17:29
I think this can be closed here.

**Comment by abo-abo** [comment] 2019-04-04 12:33
Thanks, all. Closing.

**Closed by abo-abo** 2019-04-04 12:33 UTC
