### ISSUE TITLE
`Symbol's value as variable is void: window` when trying to kill a buffer.

### ISSUE THREAD

**Issue by zilti** [abo-abo/swiper#1616] opened 2018-06-10 15:33 UTC
I installed ivy like this:

```emacs-lisp
(el-get-bundle ivy
  (progn (ivy-mode 1)
         (setq ivy-use-virtual-buffers t)
                 (setq ivy-count-format "(%d/%d) ")
                 (global-set-key (kbd "C-s") 'swiper)
                 (global-set-key (kbd "M-x") 'counsel-M-x)
                 (global-set-key (kbd "C-x C-f") 'counsel-find-file)
                 (global-set-key (kbd "<f1> f") 'counsel-describe-function)
                 (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
                 (global-set-key (kbd "<f1> l") 'counsel-load-library)
                 (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
                 (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
                 (global-set-key (kbd "C-c C-r") 'ivy-resume)

                 (global-set-key (kbd "C-c g") 'counsel-git)
                 (global-set-key (kbd "C-c j") 'counsel-git-grep)
                 (global-set-key (kbd "C-c k") 'counsel-ag)
                 (global-set-key (kbd "C-x l") 'counsel-locate)))
```

And get the error in the title when I `C-x k <return>`. Everything else works fine.

**Comment by basil-conto** [comment] 2018-06-11 15:20
I cannot reproduce this; please provide more details so that there is a better chance of debugging your issue.

First, please enable <kbd>M-x</kbd>`toggle-debug-on-error`<kbd>RET</kbd> and post the backtrace resulting from the error you get.

Second, what is <kbd>C-x</kbd><kbd>k</kbd> bound to in your setup, and, if applicable, which completion candidate is selected when you type <kbd>return</kbd>? Is it a virtual `recentf` or bookmarked file?

Third, I have looked through the Ivy sources and don't see any obvious places where the error could come from; its source could be a different package/setting of yours. Have you tried reinstalling Ivy? Are you able to reproduce the issue starting from `emacs -Q`? If not, then the issue could lie with your init file; try commenting-out parts of your configuration to see which setting(s) give rise to the error (from the setup you cite, the only thing which I think might be relevant is `ivy-use-virtual-buffers`).

**Comment by basil-conto** [comment] 2018-11-15 12:53
Any updates on this?

**Comment by abo-abo** [comment] 2018-11-22 09:16
This doesn't look like it's an issue with ivy. Closing until there's more info.

**Closed by abo-abo** 2018-11-22 09:16 UTC
