### ISSUE TITLE
`ivy-next-history-element` inserts word-boundary regexp characters that prevent search from working

### ISSUE THREAD

**Issue by patbl** [abo-abo/swiper#1916] opened 2019-02-01 01:38 UTC
When I run `swiper` and then type `M-n` to trigger `ivy-next-history-element`, `\_<Foo\_>` is inserted into the minibuffer, as I'd expect from the source code:

https://github.com/abo-abo/swiper/blob/e86cf2ecffa2061586952d78b7a95782f4957453/ivy.el#L1351-L1353

![image](https://user-images.githubusercontent.com/1735266/52097108-48dc1280-257e-11e9-9862-538d4257e5ee.png)

But as you can see above, these characters prevent the string from matching anything. Without the word-boundary characters, matches are displayed:

![image](https://user-images.githubusercontent.com/1735266/52097204-c9027800-257e-11e9-84e9-4258671155e4.png)

`\\b` also doesn't work as a word-boundary anchor.

It's possible that some other package or configuration is causing the issue.

It's a problem in `ruby-mode` and `python-mode` but not in `text-mode` (the latter of which omits the word-boundary characters when I press `M-n`).

**Comment by abo-abo** [comment] 2019-02-05 15:01
Can't reproduce in `ruby-mode`. Please try to reproduce with `make plain`.

**Comment by patbl** [comment] 2019-02-10 02:05
The behavior I described was due to this setting in my `init.el`:

    (setq search-default-mode 'char-fold-to-regexp)

I don't need it, so I just deleted it. Feel free to close this issue.

**Comment by basil-conto** [comment] 2019-02-10 13:21
Not that it makes a difference, but just to be clear: these regexp constructs are symbol, not word, boundaries.

**Comment by abo-abo** [comment] 2019-02-10 19:22
@patbl OK, closing

**Closed by abo-abo** 2019-02-10 19:22 UTC
