### ISSUE TITLE
Swiper - move to next match on same line

### ISSUE THREAD

**Issue by joelekstrom** [abo-abo/swiper#865] opened 2017-01-27 22:27 UTC
In some languages (for example, Objective-C), it's very common that the same word appears multiple times on the same line. I often want to navigate for example to the third match on a line. With isearch, this is quite simple - just press `C-s` some more times until the cursor ends up on the correct match.

I haven't figured out how to do this in Swiper. Is it possible? It seems to me that Swiper works on per-line results instead of per word/match.

If it's not possible, consider this a feature request... 😃

**Comment by ardpp** [comment] 2017-01-27 23:04
You might want to check out `(swiper-avy)` which is bound to `C-'` in the minibuffer during a swiper search.

**Comment by jaroslawr** [comment] 2017-11-26 08:23
I personally would much prefer swiper candidates corresponding to individual matches, not matching lines. It would help in interactive use, as @accatyc already explained, but also with keyboard macros - I frequently record macros based on isearching to a point and doing a bunch of operations around that point, and it is not rare that multiple matches might occur on the same line, so using swiper as a replacement for isearch broke this flow for me. Using different search systems for different use cases is a bit of a stretch, so as a result I stopped using swiper altogether, even though I otherwise preferred the user experience. 

Is there any reason to prefer the current behavior of candidate-per-matching-line over candidate-per-match?

**Comment by philiparvidsson** [comment] 2018-02-27 06:49
Status on this? I can't use swiper interactively because of this! :-(

**Comment by abo-abo** [comment] 2018-02-27 17:48
Swiper is line-based by design, there are restrictions and expectations that relate to this design.

A candidate-based command `swiper-async` is in the works, I need to find free time to refine it before it's published.

**Comment by Lenbok** [comment] 2019-11-05 04:06
`swiper-isearch` now exists, so this can probably be closed.

**Comment by abo-abo** [comment] 2019-11-05 10:35
@Lenbok Thanks, indeed. Closing.

**Closed by abo-abo** 2019-11-05 10:35 UTC
