### ISSUE TITLE
Cannot edit TRAMP protocol after "accepting"

### ISSUE THREAD

**Issue by darkfeline** [abo-abo/swiper#1227] opened 2017-10-07 03:19 UTC
After "accepting" a TRAMP protocol, there does not appear to be a way to go back and edit it.  `DEL` does nothing.

This is a huge pain if you tunnel through a few machines and discover a typo.  With default completing read, you can move point back and edit the TRAMP portion, but with ivy you have to start over from scratch it seems.

```
1 Find file: /ssh:user@some-server|ssh:user@another-server|ssh:typo@last-server:/
```

**Comment by abo-abo** [comment] 2017-10-07 09:30
I don't use TRAMP hopping in my workflows (I think it can be avoided by creating entries in `~/.ssh/config`?). If you can propose a PR that solves this in a good way, I'd gladly accept.

**Comment by edkolev** [comment] 2017-10-07 16:33
The issue is reproducible when a single host is used, without hops.

Here are the steps:
1. `C-x C-f /ssh:fake:` (assuming there's a `fake` host in ssh config)
2. now if you press`C-x C-f` you can visit files on the `fake` host, but you can't edit files on your machine (where emacs runs)

**Comment by abo-abo** [comment] 2017-10-07 17:31
> now if you pressC-x C-f you can visit files on the fake host, but you can't edit files on your machine (where emacs runs)

Press `//` or `~` to go back to local machine?

**Comment by darkfeline** [comment] 2017-10-08 06:48
You would still have to retype your TRAMP part from scratch.  It would be nice if you could go back and edit it.

**Comment by abo-abo** [comment] 2017-10-08 07:24
Once you've opened a file or direcotry, it's in the history. Use `C-x C-f M-p` then.

**Comment by darkfeline** [comment] 2017-10-08 07:37
You can't edit the TRAMP portion though.

```
1 Find file: /ssh:user@some-server|ssh:user@another-server|ssh:typo@last-server:/
```

Once you get here, you can no longer edit the `ssh:user@some-server|ssh:user@another-server|ssh:typo@last-server:` part at all.  Not even if you go back through the history. The only way I have found is to type `//` to go back to `/` then type all of `ssh:user@some-server|ssh:user@another-server|ssh:typo@last-server:` from memory, changing any necessary parts.

**Comment by edkolev** [comment] 2017-10-08 19:25
If I understand correctly, the find-file code determines what the prompt is, then ivy doesn't allow editing the prompt, which seems reasonable decision to me.

Here's a snippet which uses plain emacs completion when the visited file is remote:
```emacs-lisp
(defun evgeni-counsel-find-file ()
  (interactive)
  (let ((completing-read-function
         (if (and (buffer-file-name)
                  (file-remote-p (buffer-file-name)))
             'completing-read-default
           'ivy-completing-read)))
    (call-interactively 'find-file)))
```

Note this doesn't work if you're visiting a remote directory.

**Comment by darkfeline** [comment] 2017-10-08 21:53
> If I understand correctly, the find-file code determines what the prompt is, then ivy doesn't allow editing the prompt, which seems reasonable decision to me.

It doesn't seem reasonable to me, since ido can do it.

````
/sudo:|sudo::/$
```

`$` denotes the readonly portion of the minibuffer.  At this point, pressing `DEL` repeatedly yields:

````
/sudo:|sudo::$
/sudo:|sudo:$:
/sudo:|sudo:$
/sudo:|sudo$:
/sudo:|sudo$
/sudo:|$sudo
/sudo:|$sud
/sudo:|$su
```

Whereas for ivy, pressing `DEL` does nothing (depending on `ivy-on-del-error-function), and pressing `/` just goes back to a plain `/$`.

Thanks for the workaround, although I have simply disabled ivy-mode, binding specific commands like `counsel-find-file`, and calling `M-x find-file` whenever I encounter a corner case.  ivy is great, but there are so many corner cases. As an analogy, Emacs's default dumb minibuffer read is like a command line, and ivy is like a GUI. It's awesome for a lot of cases, but sometimes you need a dumb command line that makes no assumptions on what you're trying to input.

**Comment by abo-abo** [comment] 2017-10-09 12:40
> As an analogy, Emacs's default dumb minibuffer read is like a command line, and ivy is like a GUI. It's awesome for a lot of cases, but sometimes you need a dumb command line that makes no assumptions on what you're trying to input.

Rather than shell-vs-GUI, I'd like to think of it as assembler-vs-C. Just imagine we're designing C right now: we should make it easy to do everything in C and not have the user resort to asm when things are lacking.

What IDO did is to make it easy to fall back to asm from C (via <kbd>C-c C-f</kbd>) which is a huge anti-pattern: I've spent years un-learning that key binding. I don't want `counsel-find-file` to have <kbd>C-c C-f</kbd>.

As a user, I'm already very happy the subset of functionality that `counsel-find-file` offers. I'd like other users to be happy with their workflows as well. But then improvements to `counsel-find-file` should be done by the person that wants them.
So I invite @darkfeline or @edkolev or anyone else to contribute.

**Comment by darkfeline** [comment] 2017-10-10 03:57
Well, I have already bound `find-file` to `C-u C-x C-f`.  

What you say may be good, but making a change to a large library like ivy is no small endeavor, and in the meantime, I need Emacs to actually work.  Of course, once I have a workaround, I am less motivated to improve ivy.

I do not have an answer, sorry. Software development is hard.

**Comment by abo-abo** [comment] 2017-10-10 07:22
> Software development is hard.

True that.

**Comment by edkolev** [comment] 2017-10-12 15:06
I don't mind implementing a change in counsel-find-file's behaviour.

I'm trying to implement the following behaviour:
- with prompt `Find file: /ssh:fake:/` pressing `C-<backspace>` should set the prompt to `/`, clear ivy candidates, and set the minibuffer contents to `ssh:fake:/` so the user can edit as necessary.

I'm modifying `counsel-up-directory ` to get the above behaviour. Note that I'm planning to preserve the current behaviour of `C-<backspace>` on input such as `Find file: /ssh:fake:/path/to/file`.

@abo-abo could you help me out with pointers (no C pun intended) how to:
- set the prompt to `/` without triggering ivy completion; i.e. do what `ivy--cd ` does but without making ivy list files in `/`
- set minibuffer contents programatically, I see minibuffer.el has `minibuffer-completion-contents` and `delete-minibuffer-contents` but no function to set the contents

Thank you

**Comment by abo-abo** [comment] 2017-10-12 15:48
> set the prompt to / without triggering ivy completion; i.e. do what ivy--cd does but without making ivy list files in /

See `ivy-set-prompt`. You can attach a custom prompt function and display whatever is needed.

> set minibuffer contents programatically, I see minibuffer.el has minibuffer-completion-contents and delete-minibuffer-contents but no function to set the contents

With Ivy, the minibuffer contents are always:

1. prompt (customizable)
2. user input
3. candidates that match user input (customizable)

Use `:re-builder` and `:matcher` arguments to `ivy-read` to customize item 3.

- `:re-builder` is `str -> str` and transforms `ivy-text` to a regex
- `:matcher` is `str * str list -> str list` and transforms a regex and a list of candidates to a list of candidates that "match" the regex. Use can just ignore all input arguments and return whatever you want - that will be inserted into the minibuffer.

**Comment by edkolev** [comment] 2017-10-16 14:04
Thanks, abo-abo!

Here's what I've come up with, not sure if this is the best implementation.

In the following gif I press `C-x C-f` then `C-backspace` twice, then edit the ssh host:

![10](https://user-images.githubusercontent.com/1532071/31615851-a39bd476-b293-11e7-8ced-d6897acc2692.gif)

This is the only changed function:

```emacs-lisp
(defun counsel-up-directory ()
  "Go to the parent directory preselecting the current one."
  (interactive)
  (let* ((dir-file-name
          (directory-file-name (expand-file-name ivy--directory)))
         (up-dir (file-name-directory dir-file-name)))

    (if (string-equal dir-file-name up-dir)
        (progn
          (setq ivy--old-cands nil)
          (setq ivy--old-re nil)
          (ivy-set-index 0)

          (setq ivy--directory "")
          (setq ivy--all-candidates nil)
          (setq ivy-text "")
          (delete-minibuffer-contents)
          (insert up-dir))
      (ivy--cd (file-name-directory dir-file-name))
      (setf (ivy-state-preselect ivy-last)
            (file-name-as-directory (file-name-nondirectory dir-file-name)))))) 
```

@darkfeline is this behaviour something you consider better over the current one?

**Comment by darkfeline** [comment] 2017-10-17 03:24
@edkolev Thanks, that looks great.

**Comment by abo-abo** [comment] 2017-10-17 08:27
@edkolev Could you open a PR with this?

**Comment by edkolev** [comment] 2017-10-17 10:16
Sure, I just opened one.

**Closed** 2017-10-17 17:31 UTC

**Comment by PhilHudson** [comment] 2019-09-25 17:34
I still have the same old problem when I try to `insert-file` a local file into a remote one. I instrumented `counsel-up-directory` for edebug; apparently, bafflingly, it is *not* called during completion for `insert-file`.

    ;; Package-Version: 20190830.1557
    ;; Version: 0.12.0

**Comment by abo-abo** [comment] 2019-09-26 09:00
@PhilHudson I think this can be solved with:

```elisp
(define-key ivy-minibuffer-map (kbd "C-DEL") 'counsel-up-directory)
```

**Comment by PhilHudson** [comment] 2019-09-26 09:21
Tried it, thanks, but didn't work. I've now found a workaround: `/
C-j` takes me to the local root directory.

On 26/09/2019, Oleh Krehel <notifications@github.com> wrote:
> @PhilHudson I think this can be solved with:
>
> ```elisp
> (define-key ivy-minibuffer-map (kbd "C-DEL") 'counsel-up-directory)
> ```
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/abo-abo/swiper/issues/1227#issuecomment-535410758


-- 
phil.hudson@iname.com                      PGP/GnuPG ID: 0x887DCA63

**Comment by kolen** [comment] 2019-12-08 17:00
It works for me, however when using `(kbd "<C-backspace>")` (I didn't research details of `DEL` vs `<DEL>` vs `backspace` vs `deletechar`, etc).

**Comment by abo-abo** [comment] 2019-12-17 12:10
@kolen The difference could be between using Emacs in the terminal vs the graphical one.

**Comment by dgentry** [comment] 2023-12-08 05:26
How does one type C-backspace?  Backspace is C-h, at least on every keyboard I'm familiar with?  I'm getting by with the `/ C-j` workaround posted by @PhilHudson.  This comes up rarely, but when it does, it's extremely frustrating, because it's hard to (re-)discover how to just edit my *$&$% minibuffer.  Sometimes `//` or `~` seem to work, but mostly not.
